### ISSUE TITLE
[Proposal] Make an official tech lead process

### ISSUE THREAD

**Issue by catblade** [cncf/tag-env-sustainability#114]
#### Description
Make an official tech-lead process.

#### Impact

This will give us transparency in how these leads are chosen, and what expectations are to get there.

#### Scope

Minimal, but will need community discussion and TOC approval.

### TODO

- [ ] TAG Environmental Sustainability lead representative:  All TAG Chairs/leads
- [ ] Project leader(s):  @leonardpahlke 
- [ ] Project Members:  N/A
- [ ] _Fill in addition TODO items here so the project team and community can see progress!_
- [ X ] Scope 
- [ ] Deliverable(s):  Documentation added to TAG

**Comment by leonardpahlke** [comment]
This document already describes the process around becoming a TL: https://github.com/cncf/tag-env-sustainability/blob/main/governance/tech-lead-proposal-process.md

I opened a PR to make some small updates without changing the process or guidelines..: https://github.com/cncf/tag-env-sustainability/pull/121

This PR adds some guidelines on how to mature as a contributor inside the TAG: https://github.com/cncf/tag-env-sustainability/pull/124

**Comment by mkorbi** [comment]
Can be closed?
