### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] Meeting with Local Meetup Organizers

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#144]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

To make sure the local meetup organizers are aware of the latest information about the cloud native sustainability week, it would be good to organize a meeting for all to ask questions. 

There are likely two meetings scheduled to make sure all timezones are covered. 

- [x] Schedule two meetings for end of July to discuss the overall event (1xUS friendly, 1xAsia friendly)
- [ ] Schedule two meeting three weeks before the event (1xUS friendly, 1xAsia friendly)

**Comment by guidemetothemoon** [comment]
I can help out here, both with preparation for the meetings and hosting/assisting during the meetings😊

**Comment by leonardpahlke** [comment]
Yes! Thanks 🙏

**Comment by leonardpahlke** [comment]
Thanks, everyone, for attending today's meetings! You can find the slides here: 
[2023-08-10 cloud-native-sustainability-week-sync.pdf](https://github.com/cncf/tag-env-sustainability/files/12315572/2023-08-10.cloud-native-sustainability-week-sync.pdf)
YT recording https://youtu.be/m9uf9m5rI9k

**Comment by leonardpahlke** [comment]
- [ ] reach out to the LF regarding the badges so they are aware
- [ ] prepare the welcome slides
- [ ] prepare links to the survys
- [ ] Explain how we promote the event
- [ ] get the discount codes for attendees and organizers
- [ ] sustainability week outline (these are the events on monday, these are the blog posts etc.)
- [ ] general artworks they can use on any of the resources for the meetup

**Comment by AntonioDiTuri** [comment]
I created a to-do list for the local event organizers: I hope it can be helpful to everybody

https://github.com/cncf/tag-env-sustainability/issues/224

Feel free to provide inputs :)
