### ISSUE TITLE
[Tracking, Green Reviews WG] Design Green Reviews WG pipeline workflow

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf/tag-env-sustainability#182]
### Description

Following from the proposal ["Proof of Environmental Sustainability activities and best practices for CNCF projects"](https://github.com/cncf/tag-env-sustainability/issues/64), the [Green Reviews WG](https://github.com/cncf/tag-env-sustainability/tree/main/working-groups/green-reviews) is setting up infrastructure to measure the sustainability footprint of CNCF projects. This issue tracks the design & implementation of this technical work.

### Milestones

- Create a document to start outlining the sections above.
- Discuss the progress during Green Reviews WG meetings.
- Identify the starting point (or multiple points in parallel) that can be worked on.
- Break down work into actionable items that folks can take on.

### [Tracking] Epic

- [x] https://github.com/cncf-tags/green-reviews-tooling/pull/2
- [x] https://github.com/cncf/tag-env-sustainability/issues/220
- [x] https://github.com/cncf/tag-env-sustainability/issues/183
- [x] https://github.com/cncf-tags/green-reviews-tooling/issues/1

Co-Authored By: Kristina D @guidemetothemoon

**Comment by AntonioDiTuri** [comment]
I have few comments/questions: 

Here it is the google doc tracking the implementation details and related discussion: 

https://docs.google.com/document/d/19fzZW-IMv2kDNatKFHeHh7wqcEN0e2N60wzxvCGZd48/edit?usp=sharing 

Could you please clarify what we would need k6 for? I am not an expert and it is not so clear to me :) 

I would maybe need add a step which I think it would be to install the project we would like to test.
e.g. In the test server we would need to install the target project (Falco for the moment)

Does Prometheus handle the remote write? Where can I read some doc on how?

Can't wait to start!

**Comment by nikimanoledaki** [comment]
>  I have seen some steps to trigger GH actions between different repos. Is it a valid approach?

This is the way to go, yes. The workflow to build and deploy the CNCF project should trigger the GH Action workflow in the [green-reviews-tooling](https://github.com/cncf-tags/green-reviews-tooling) repo.

To achieve this, we need to add a [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) in the CNCF project build pipeline (assuming they use GH Action). Then, we need to add a a [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) in the tooling repo. This will be the trigger for the load tests.

> Could you please clarify what we would need k6 for?

These should be benchmark tests that perform an action against the CNCF Project. To use an example more familiar to me, in the example of a GitOps benchmark test, we create and deploy an application which Flux/ArgoCD then reconcile in the cluster. This would be the equivalent to the [SCI Functional Unit](https://sci-guide.greensoftware.foundation/R), in theory:
> The functional unit defines how your application scales. For instance, if your application scales by APIs then choose API as your functional unit.

This will look different for each CNCF Project. Unsure what this looks like for Falco - it is what we are trying to figure out next :)

In this scenario, the benchmark tests run in the same Node as Kepler is running, so that we can measure the energy consumption of the Functional Unit.

> Does Prometheus handle the remote write?

[devstats](https://github.com/cncf/devstats) is a Grafana dashboard so we should be able to use the Prometheus instance running on our Node as a data source. TBD :)

**Comment by leonardpahlke** [comment]
@nikimanoledaki, @AntonioDiTuri the Falco project tests their deployments on Equinix using this Ansible config https://github.com/falcosecurity/kernel-testing/tree/main. Perhaps this could be a good starting point for us? We could copy the resources, deploying the setup (for testing purposes, -> running the Falco tests) then reducing the deployment (remove all settings we do not need) and adding new configuration (to enable assessing the SCI score, measuring energy etc.). We likely need to build a small project (in Go or so) next to the Ansible config to make some calculations.

cc @incertum

**Comment by incertum** [comment]
@leonardpahlke, our Falco core maintainers meeting is on October 5th. Will check with the other maintainers (@FedeDP, @Andreagit97) to see how we can generalize the Ansible setup so that it can be used for more future projects beyond Falco. Voting in favor of creating a Go project that we can all contribute to. This may come in handy for future setup configurations and other aspects.

**Comment by incertum** [comment]
I see that this ticket is referenced: https://www.bbb.org/us/il/aurora/profile/window-installation/green-t-windows-0654-88593900

Does this mean that we plan to run Kubernetes on a bare-metal Equinox cluster, without a hypervisor like EKS?

Do we plan to deploy each project directly on the hosts, or in the Falco case as a daemonset?

> Alternatives such as Firecracker microVMs are being considered to work with Falco's setup: https://github.com/cncf-tags/green-reviews-tooling/issues/1#issue-1926319038)

Please note that the Firecracker VM setup you are referencing is used to test different kernel versions. For the Green Reviews WG efforts, one kernel version is sufficient, and we would like to deploy Falco realistically, as the goal here is currently slightly different: we want to test performance.

**Comment by nikimanoledaki** [comment]
@incertum that is correct, Equinis is our infrastructure so we will be running on a BM cluster without a hypervisor. We are currently evaluating the pros/cons of different tooling and cluster setups. We have not decided on any yet. We're looking into CAPI for GitOps but we're still evaluating how 

> Do we plan to deploy each project directly on the hosts, or in the Falco case as a daemonset?

This is a great question - we are still in the process of designing the E2E flow. We need to think about how we will scale when we test each project separately, with an emphasis on isolation so that we can run the tests for each project in an isolated way. This could be done with CAPI by running a new worker cluster for each test. However this could be too much overhead. We could also achieve this degree of isolation within a single cluster if we run each CNCF Project and its test on a dedicated Node if we do a combination of Namespace + Node taint/isolation for each project that we test. So Falco would run as a Daemonset but the Pod would only run on 1 Node. Please let me know what you think about this idea.

In order to make a decision about the above it would also help us first to decide what and how we will run the tests for each CNCF Project. With regard to _what_ we test, I agree with @leonardpahlke's idea that we could reuse the existing Falco test steps with some changes to fit our use case.

With regard to _how_ we run these tests, we should discuss whether we will use the Project's existing test tooling or a unified test tooling. For example, we could use the tooling that each CNCF Project uses, such as Ansible in the case of Falco. Alternatively, we would use a unified testing tooling such as k6, which has been brought up before but we are not sure yet that k6 is the right tool for testing Falco. Before we move forward, it would be good to establish whether k6 is a good tool to use to test Falco. @incertum, do you think it would be possible to collaborate with you and the other Falco maintainers to do a spike on this?

@immavalls works with k6 and brought up the following, [here](https://docs.google.com/document/d/19fzZW-IMv2kDNatKFHeHh7wqcEN0e2N60wzxvCGZd48/edit?disco=AAAA58bb6qM):
> Will this be using [https://github.com/marketplace/actions/k6-load-test](https://www.google.com/url?q=https://github.com/marketplace/actions/k6-load-test&sa=D&source=docs&ust=1696853494018894&usg=AOvVaw1PAbzUSU9lh24Ng58z1uFS)? or is the plan to run the tests in a k8s cluster using [https://github.com/grafana/k6-operator](https://www.google.com/url?q=https://github.com/grafana/k6-operator&sa=D&source=docs&ust=1696853494018997&usg=AOvVaw1HMN2z-KjUdbViP78lLRLW)? I can help figure this part out with more information

> we would like to deploy Falco realistically, as the goal here is currently slightly different: we want to test performance.

Could you expand further on what you mean with regard to deploying Falco realistically? Is there something we are missing or should look out for in your experience of how Falco is deployed?

**Comment by rossf7** [comment]
@incertum I've been looking at https://github.com/falcosecurity/kernel-testing with @nikimanoledaki to see if we can reuse the approach you're using with GitHub Actions and Ansible.

I may well be missing something but high level AIUI the test is triggered by Falco's Prow instance which runs the Ansible playbook that connects to an Equinix machine using SSH.

Is the Equinix machine running Kubernetes and how do you manage it?

I ask because in our case we need to run the tests on a K8s node. This is so Kepler can attribute the energy consumption from the CPU socket to the Falco pods.

**Comment by incertum** [comment]
@rossf7

GitHub Actions + Ansible Kubernetes module could be a valid solution.
Any alternative will work for us, Ansible is not required from our side.

I'd like to clarify that our kernel testing involved spinning up VMs to test different kernels, and yes, SSH was used, along with some other setup requirements. However, for the Green Reviews WG + Falco, VMs and SSH are not necessary. I shared our setup to demonstrate how we successfully established a robust pipeline using GitHub Actions + Ansible against an Equinix machine. My intention was to illustrate that the steps of our pipeline could potentially inspire the Green Reviews workflow. Realizing maybe it complicates the discussion, apology for any confusion caused.

**Comment by rossf7** [comment]
@incertum No worries and thank you this is very helpful!

> GitHub Actions + Ansible Kubernetes module could be a valid solution.
> Any alternative will work for us, Ansible is not required from our side.

We're looking into using Ansible and the Kubernetes module could be useful for our pipeline but good to know other tooling is an option.

For the cluster we can use the Equinix Ansible module but we still need to provision K8s. CAPI / CAPEM is a challenge without a management cluster. Kubeadm is also an option but it would be good to see other CNCF projects solve this.

**Comment by nikimanoledaki** [comment]
Closing this issue since we are tracking more specific work in the WG repository: https://github.com/cncf-tags/green-reviews-tooling
