### ISSUE TITLE
[BLOG] Cloud Native Sustainability Week 2023

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#191]
- **Authors**: @leonardpahlke @guidemetothemoon 
- **Reviewers**: *TBD* 
- **TAG ENV Lead**: @leonardpahlke  

## Abstract

Announcement blog post about the cloud native sustainability week, see http://tag-env-sustainability.cncf.io/cloud-native-sustainability-week/ ref tracking issue #95 

## Scope

event: cloud native sustainability week

## Expected audience

we plan to publish it to on the TAG blog and the CNCF blog. This blog post should serve as reference point to anyone in the community to get info about the event.

## Goals and Non Goals

- goal: intro the event
- goal: starting point to learn about the event
- non goal: dive into decision etc.

## Tasks

A more complete summary of tasks are described on XYZ.

- [x] Outline Blog post
    - [x] [**Author**] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
    - [x] [**Author**] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
    - [x] [**TAG ENV Lead**] One of the TAG ENV leads assigned themselves to wrangle the blog
    - [x] [**TAG ENV Lead**] Blog post outline and theme has been discussed
- [x] [**Author**] Blog post written and ready for review
- [x] Review
    - [ ] [**Author**] blog post PR opened (blog posts are added to the [`website/content/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/blog) folder, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
    - [ ] [**Author**] notified TAG ENV community for review via Slack on the `tag-env-sustainability` channel.
    - [ ] [**Author**] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
    - [ ] [**Author**] Feedback and comments have been resolved.
    - [ ] [**Reviewers**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] ready to get published.
    - [ ] [**TAG ENV Lead**] notified one of the ToC liaisons to sign off the blog post.
    - [ ] [**TAG ENV ToC Liaison**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] merged blog post.
    - [ ] _optional_ [**TAG ENV Lead**] schedule the blog post on the CNCF blog next to the TAG ENV blog
    - [ ] [**Author**] Wrote feedback about the blog post process as a comment under this issue

## Comments 

document: https://docs.google.com/document/d/1cKIlwes0Ws6H1y9LTXHDE-mQ6anNkDDeHUiRxWItS4Q/edit?usp=sharing

**Comment by leonardpahlke** [comment]
blog post published to the TAG ENV blog for tomorrow (sep 6) https://tag-env-sustainability.cncf.io/blog/
