### ISSUE TITLE
[BLOG] Introduction to Cloud Native Sustainability

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#213]
- **Authors**: *TBD*
- **Reviewers**: *TBD* 
- **TAG ENV Lead**: *TBD* 

## Abstract

This blog post provides a detailed introduction to what cloud native sustainability is, why it's important and what the current cloud native sustainability landscape (tools, initiatives, research) looks like. It should also provide suggestions on how one can contribute to the cloud native sustainability space (f.ex. through TAG ENV contributions). The blog post should also be clear on what cloud native sustainability is and isn't. The goal of the blog post is to be an introduction for beginners so that it's easier to learn about and navigate the cloud native sustainability space for those who have none or little knowledge about it.

## Scope

Beginner-friendly introduction to what cloud native sustainability is and isn't, what value it brings to cloud native and open source ecosystem and how the current landscape looks like.

## Expected audience

- Beginners who have none or little knowledge about cloud native sustainability, or may have misconceptions about what it is

## Goals and Non Goals

Goals:
- Provide introduction to what cloud native sustainability is and isn't, and what value it has in the cloud native and open source space
- Provide overview of its landscape to make it easier to navigate for beginners
- Highlight how one can dive deeper and potentially contribute to the cloud native sustainability space

Non-Goals:
- Get too technical or deep dive into the topic since this should be a beginner-friendly introduction, that should also be understandable for less technical folks
- Go into details of TAG ENV projects, working groups, etc. since there are other dedicated resources for that

## Tasks

A more complete summary of tasks are described on XYZ.

- [ ] Outline Blog post
    - [x] [**Author**] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
    - [x] [**Author**] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
    - [ ] [**TAG ENV Lead**] One of the TAG ENV leads assigned themselves to wrangle the blog
    - [ ] [**TAG ENV Lead**] Blog post outline and theme has been discussed
- [ ] [**Author**] Blog post written and ready for review
- [ ] Review
    - [ ] [**Author**] blog post PR opened (blog posts are added to the [`website/content/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/blog) folder, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
    - [ ] [**Author**] notified TAG ENV community for review via Slack on the `tag-env-sustainability` channel.
    - [ ] [**Author**] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
    - [ ] [**Author**] Feedback and comments have been resolved.
    - [ ] [**Reviewers**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] ready to get published.
    - [ ] [**TAG ENV Lead**] notified one of the ToC liaisons to sign off the blog post.
    - [ ] [**TAG ENV ToC Liaison**] reviewed blog post.
    - [ ] [**TAG ENV Lead**] merged blog post.
    - [ ] _optional_ [**TAG ENV Lead**] schedule the blog post on the CNCF blog next to the TAG ENV blog
    - [ ] [**Author**] Wrote feedback about the blog post process as a comment under this issue

## Comments 

Document: https://docs.google.com/document/d/11y-j8QMR4UbZXY5v2yoiO7SBAGMipwwDJJkqB7xOqPI/edit?usp=sharing
Somewhat built upon the discussion from this issue: #61

**Comment by guidemetothemoon** [comment]
@by-d-sign were you interested in contributing to this blog post? Would you be interested in taking the lead on outlining it?😊

**Comment by sergioarmgpl** [comment]
It would love to participate on this :) @guidemetothemoon

**Comment by guidemetothemoon** [comment]
Great that you're interested in contributing to this @sergioarmgpl ! I haven't heard anything from @by-d-sign regarding this yet so I'm not sure if he has capacity to take a lead on this. 

In the meantime I'll see if I can improve the suggested outline a bit and add some more details on the topics and scope that we want to cover with the blog post so that we can start adding content to it. You're also welcome to add any suggestions, thoughts or draft content to the Google Doc linked in the issue description☺️

**Comment by savitharaghunathan** [comment]
Follow up:  @by-d-sign, are you still interested in contributing to this blog post?

**Comment by ATREAY** [comment]
Hey @guidemetothemoon, can I also work on this blog?

**Comment by guidemetothemoon** [comment]
@ATREAY thanks for your interest, added you to the assignees!
I will be on the reviewer and guidance side together with the blog lead @savitharaghunathan who's in the shadow role for this blog post.

I suggest that we adjust the timeline for this blog post to be published after we've published version 2 of the landscape document that @by-d-sign is working on together with others as part of #302 

Some text was already added to the draft doc by @mkorbi and I added some points that the blog post can be structured into. @sergioarmgpl @ATREAY can you please take a look and see if it's understandable?

@mkorbi @sergioarmgpl @ATREAY can one of you take the coordination lead on this blog post, i.e. distribute and assign sections, follow up on progress, etc.?

If you have any questions, please let me know. Thanks again for your time and effort on this☺️🙌

**Comment by sergioarmgpl** [comment]
I will take a look today, just back from some vacations :)

**Comment by leonardpahlke** [comment]
this may be an out from #52 (cc @mkorbi)

**Comment by claire-fletcher** [comment]
Hey! What is the status on this blog?
