### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] To-do list for local MeetUp organizers

### ISSUE THREAD

**Issue by AntonioDiTuri** [cncf/tag-env-sustainability#224]
#### Description

I would like to create a to-do/check list that can be used by every local meetup organizer.
...

### Input
Please let me know if I forgot something, and help me to extend the list. 
Is it enough to have it as a markdown or should we create a Google Form?
...

### Outcome
The to-do/check list:

#### Before the MeetUp
- [ ]  Read the [Creative Brief](https://docs.google.com/document/d/1hZql6BoZtFxET1_mBQ-Eks8k-nXkxPjzzzBFK2yyF9U/edit#heading=h.8fjbo973qqrk)
- [ ] Check out the artWork
- [ ] Check out the welcome slide: if you come up with something better share it with the community. Slides can be found [here](https://docs.google.com/presentation/d/1m745pRC6-x-7OuCwnl3N9YD3mKxlHwN0/edit#slide=id.p1)
- [ ] Check out the survey for the attendees [(QR code available here)](https://drive.google.com/drive/folders/1JUtrZr-Aajv7j7gJtA4NC04eYxEydRqR): something is missing? Willing to extend some point? Your input are always welcome
- [ ] (if possible, not mandatory) Organize the video-recording of the MeetUp
- [ ] You have done something really cool other people might use? Share it!
- [ ] Communicate the MeetUp and share it on the Social Media channels: use the hastag `#CloudNativeSustainabilityWeek` and tag the [linkedin](https://www.linkedin.com/company/cncf-tag-environmental-sustainability) or twitter/x (`@CNCFEnvTAG`) official accounts

#### At the MeetUp
- [ ] Share the gift with the attendees
- [ ] Save the number of the people who came somewhere, it is an important KPI for the success of the event.
- [ ] Have fun

#### After the MeetUp
- [ ] Share the number of people at the event with the TAG
- [ ] Share the video of the MeetUp (if possible)
- [ ] Fill out the organizer survey: this will help organization next year
- [ ] Ask for the MeetUp Organizer badge  

...

#### Todos
- [ ] Review the list
- [ ] Publish it somewhere
...

**Comment by leonardpahlke** [comment]
Thanks Antonio 👍 

The tasks under "After the MeetUp" will be all asked via the survey we send to the organizers afterward. So we could update it to

- [ ]: fill out organizer survey
    [ ] Share the number of people at the event with the TAG
    [ ] Share the video of the MeetUp (if possible)
    [ ] Do the organizer survey: this will help organization next year
    [ ] Ask for the MeetUp Organizer badge

**Comment by AntonioDiTuri** [comment]
Updated: I changed "Do the organizer survey" with "Fill up organizer survey". 
Shall I do something to make it visible in the project board?

**Comment by guidemetothemoon** [comment]
Great check-list, @AntonioDiTuri, thanks for creating it!☺️

Regarding **"Communicate the MeetUp and share it on the Social Media channels"** I think we can add that in order for us to discover all announcements easier, organizers should both use the `#CloudNativeSustainabilityWeek` hashtag and tag the TAG ENV accounts on LinkedIn (https://www.linkedin.com/company/cncf-tag-environmental-sustainability) and Twitter/X (`@CNCFEnvTAG`).

I have updated the issue so that it pops ups on the Cloud Native Sustainability Week board, but we could maybe link this checklist on the event page on the TAG ENV website? And mention it in #134 , #144

**Comment by AntonioDiTuri** [comment]
Looks like a good idea to me!

**Comment by guidemetothemoon** [comment]
@AntonioDiTuri do you have a possibility to create a PR to add the checklist to https://github.com/cncf/tag-env-sustainability/blob/main/website/content/cloud-native-sustainability-week/_index.md and also add a comment to mention the checklist explicitly on the issues I linked in previous comment?

**Comment by AntonioDiTuri** [comment]
Done: https://github.com/cncf/tag-env-sustainability/pull/235

**Comment by leonardpahlke** [comment]
Thanks @AntonioDiTuri, we will send comms to the local meetup organizers today or tomorrow about the event once again. This will be a summary of everything they need to know. Every meetup has a folder [here](https://drive.google.com/drive/u/0/folders/1dWotkN8ycGasu02u3nTKnTmsgWBtMXm3) with all the resources they need. The folder is also used to upload recordings and pictures and any other information after the event. All the steps "after the event" are asked for in the organizer survey, which we will share. 

@AntonioDiTuri could you update the list, thanks:

#### Before the meetup
- [ ] Check out your local meetup folder, which we created with all the resources you can use for your meetup ([link](https://drive.google.com/drive/u/0/folders/1dWotkN8ycGasu02u3nTKnTmsgWBtMXm3))
- Please use the welcome slides to introduce the event. The template in the folder has empty slides at the end, which you can use to transition over to your meetup agenda.
- [ ] (if possible, not mandatory) Organize the video-recording of the meetup
- [ ] Communicate the meetup and share it on social media channels. Use the hashtag `#CloudNativeSustainabilityWeek` and tag the [LinkedIn](https://www.linkedin.com/company/cncf-tag-environmental-sustainability) or twitter/x `@CNCFEnvTAG` official accounts.

#### At the meetup
- [ ] Share the survey for the attendees. A QR Code is on the welcome slides. This survey is essential to us to better understand the cloud native sustainability landscape. If possible, you can also print out the QR code (see `.png` in the folder). After filling out the survey, the attendees claim a gift code.
- [ ] Record the number of attendees at your meetup
- [ ] Take some pictures

#### After the meetup
- [ ] Fill out the local meetup organizer survey, which we will share after the event
