### ISSUE TITLE
[BLOG] cloud native sustainability week wrap up blog post

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#279]
- **Authors**:  @akelity @xamebax @Nancy-Chauhan @guidemetothemoon @leonardpahlke
- **Reviewers**: @leonardpahlke @guidemetothemoon 
- **TAG ENV Lead**: @leonardpahlke 

* **Abstract**: The cloud native sustainability week was a big success with a lot of meetups and event around cloud native sustainability. This blog post looks back at the event and summarizes the learning we had during the events. This blog also explores the attendee survey results. 
* **Scope**: Cloud native sustainability week event
* **Expected audience**: cloud native community
* **Goals**:
    * provide references to events that happened
    * communicate the success of the event
    * communicate insghts form the attendee survey 

## Tasks

- [x] Outline Blog post
  - [x] [**Author**] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
  - [x] [**Author**] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
  - [x] [**TAG ENV Lead**] One of the TAG ENV leads assigned themselves to wrangle the blog
  - [x] [**TAG ENV Lead**] Blog post outline and theme has been discussed
- [x] [**Author**] Blog post written and ready for review
- [ ] Review
  - [ ] [**Author**] blog post PR opened (blog posts are added to the [`website/content/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/blog) folder, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
  - [ ] [**Author**] notified TAG ENV community for review via Slack on the `tag-env-sustainability` channel.
  - [ ] [**Author**] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
  - [ ] [**Author**] Feedback and comments have been resolved.
  - [ ] [**Reviewers**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] ready to get published.
  - [ ] [**TAG ENV Lead**] notified one of the ToC liaisons to sign off the blog post.
  - [ ] [**TAG ENV ToC Liaison**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] merged blog post.
  - [ ] *optional* [**TAG ENV Lead**] schedule the blog post on the CNCF blog next to the TAG ENV blog
  - [ ] [**Author**] Wrote feedback about the blog post process as a comment under this issue

## Comments

* Blog post draft document: https://docs.google.com/document/d/1FAM-0GW5Xynpyh5maw1KW6NHCjSeAx1fPfJdpMWnrqQ/edit?usp=sharing
* Survey results (across multiple sheet views): https://docs.google.com/spreadsheets/d/18x2Vt7v4JNRW9Lavf2LGRPF9nd46nIrzG2JYi0-hTJ8/edit?usp=sharing

**Comment by akelity** [comment]
I'm here to help with drafting and/or collecting some testimonials. :)

**Comment by Nancy-Chauhan** [comment]
I am happy to help you with the blog, collecting tweets, photos or recordings

**Comment by ams0** [comment]
Supporting all the way

**Comment by guidemetothemoon** [comment]
Happy to help out in any way, also on the review side! 😊

**Comment by krol3** [comment]
Happy to support with photos and content of the local Sao Paulo meetup :)

**Comment by leonardpahlke** [comment]
Awesome 🤩 

ad-hoc capters:
1. Intro & event overview (@leonardpahlke, @guidemetothemoon)
2. Insghts form the attendee survey (@ams0,  @akelity, @leonardpahlke)
3. A global community (1xphoto per meetup, tweets, testimonials) (@akelity, @Nancy-Chauhan, @krol3)
4. outro & cloud native sustainability week 2024 (@leonardpahlke, @guidemetothemoon)

Review: @guidemetothemoon, @leonardpahlke and everyone else if you like 🙌 

How does this look like? does it work for all?

**Comment by leonardpahlke** [comment]
We can name the chapters differently 😄 just wrote something to capture the chapter so we can start ^^

**Comment by guidemetothemoon** [comment]
> How does this look like? does it work for all?

Looks like a great plan for me!👍Added myself and Leo to reviewers in the issue description, we can update it accordingly if more will join as reviewers.

**Comment by guidemetothemoon** [comment]
@ams0, @akelity, @Nancy-Chauhan, @krol3 do you think that you will be able to add some content for the suggested sections in the coming weeks so that we can publish this blog post some time during January and kick-off 2024 with a blast? If you have challenges with capacity, please let me know so that we can work it out together 🙂

This week I will work on the intro/outro and event overview as assigned in the suggested plan above.
@leonardpahlke FYI.

**Comment by akelity** [comment]
I'll set aside a slot to work on this next week! 
Sorry, but it's been a holiday period and I had missed the notification. :)

**Comment by guidemetothemoon** [comment]
Thanks for the feedback @akelity ! 😊

Since many were on vacation last week and may have missed the notification as mentioned here earlier, this is a gentle reminder: will you still be able to contribute to this blog post in the coming days, @ams0 @Nancy-Chauhan @krol3 ?

**Comment by Nancy-Chauhan** [comment]
Hey @guidemetothemoon , apologies I missed the notifications, I will take a look and suggest additions from my end. Thank you for following up 🌱✨

**Comment by xamebax** [comment]
I learned during today's ENV TAG meeting that there's work left on this blog post. I've experience with writing and quite a few hours I can contribute with in the next two weeks. I haven't participated in the event as it happened, but I read the draft and I can see that the insights from the user survey are missing, and so are some photos from meetups. I'm happy to work on either. 🙂

**Comment by leonardpahlke** [comment]
@xamebax thank you so much! Your support is very much appreciated 👍 

If you could help us with the insights from the user survey, that would be great.

* https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/
* survey results (multiple pages) https://docs.google.com/spreadsheets/d/18x2Vt7v4JNRW9Lavf2LGRPF9nd46nIrzG2JYi0-hTJ8/edit#gid=2131262798

**Comment by xamebax** [comment]
@leonardpahlke great! I'm setting aside time for that on the weekend. I'll write here once I updated the Google document.

**Comment by leonardpahlke** [comment]
Thanks!

**Comment by xamebax** [comment]
@leonardpahlke I think I'm done, but please let me know if you'd like me to shorten, expand, or rephrase.

Here's how I reached the conclusions outlined in the blogpost.

I copied all responses into a new spreadsheet to make aggregation easier. For questions with a scale ("how likely are you..."), I looked at the median and the average to figure out if respondents were (very) satisfied (4-5). I also separately looked at survey answers from the outliers (those who answered with a lower score to any of the questions) to see how their other answers stand out and how they can be incorporated into the insights. I personally think these outliers are important.

For the open text question:

> What was the most interesting thought transported at the meetup to better understand cloud native sustainability?

I read through all answers and divided them into themes (data collection/transparency, concrete tools, community, guidelines, different approaches, accountability/responsibility, awareness, and cost). I counted how many times each theme appears in the answers, and then found a quote from the top 3.

**Comment by akelity** [comment]
I wrote the "A global community" paragraph. I hope it's okay! 
I've also added a collage of photos from the local meetups, the original is in the local meetup drive folder (I've included the link in the file)

**Comment by leonardpahlke** [comment]
i will take a look. thanks so much  @xamebax @akelity.

**Comment by leonardpahlke** [comment]
Awesome, this is great! Made some minor changes. @ams0 @Nancy-Chauhan if you have a couple of minutes to review the blog - that would be very much appreciated.

The CNCF releases a survey now’ish / anytime now (should have released already 😄) about cloud native sustainability. It goes into more depth. I will mention it at the end of the blog after its released.

**Comment by guidemetothemoon** [comment]
Did a review as well - this looks very very good, awesome work @xamebax @akelity ! Thank you for your time and contribution💚
Added a few minor improvements to the wording, but other than that, it looks good to me ☺️

@leonardpahlke thank you for reviewing!

**Comment by Nancy-Chauhan** [comment]
Hey @leonardpahlke , I just took a look at the blog, and it looks really nice! 👏 I was wondering if we could add information about upcoming events and talks since the Kubecon schedule is now live. This way, people can meet the TAG and attend the talks on that day.

**Comment by leonardpahlke** [comment]
@Nancy-Chauhan good idea, we can tease that in a sentence or two. Feel free to update the blog! Thanks 🙌

**Comment by leonardpahlke** [comment]
send the blog to the CNCF
