### ISSUE TITLE
[BLOG] Reduce, Reuse, Rebase: Sustainable Containers with Buildpacks

### ISSUE THREAD

**Issue by jkutner** [cncf/tag-env-sustainability#281]
- **Authors**: @jkutner
- **Reviewers**: @hone @natalieparellano
- **TAG ENV Lead**: *TBD* 

## Abstract

[Cloud Native Buildpacks](https://buildpacks.io) are the greenest choice for container builds because the rebaseable layers and advanced caching mechanisms they provide can prevent many images from being rebuilt at all. That's a big shift from many cloud native technologies that assume unlimited resources are available in the cloud. In this post, you'll learn how Buildpacks rebase mechanism can dramatically reduce environment impact at scale.

## Scope

An overview of the Buildpacks rebase mechanism and it's resource usage. 

## Expected audience

Anyone building container images.

## Goals and Non Goals

To bring awareness to the wasteful resource usage required to maintain container images at scale. Our goal is not to convert every Docker build to use buildpacks, but rather to encourage the use of buildpacks where it makes sense. 

## Tasks

A more complete summary of tasks are described on XYZ.

- [x] Outline Blog post
  - [x] [**Author**] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
  - [x] [**Author**] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
  - [ ] [**TAG ENV Lead**] One of the TAG ENV leads assigned themselves to wrangle the blog
  - [ ] [**TAG ENV Lead**] Blog post outline and theme has been discussed
- [x] [**Author**] Blog post written and ready for review
- [ ] Review
  - [x] [**Author**] blog post PR opened (blog posts are added to the [`website/content/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/blog) folder, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
  - [ ] [**Author**] notified TAG ENV community for review via Slack on the `tag-env-sustainability` channel.
  - [ ] [**Author**] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
  - [ ] [**Author**] Feedback and comments have been resolved.
  - [ ] [**Reviewers**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] ready to get published.
  - [ ] [**TAG ENV Lead**] notified one of the ToC liaisons to sign off the blog post.
  - [ ] [**TAG ENV ToC Liaison**] reviewed blog post.
  - [ ] [**TAG ENV Lead**] merged blog post.
  - [ ] *optional* [**TAG ENV Lead**] schedule the blog post on the CNCF blog next to the TAG ENV blog
  - [ ] [**Author**] Wrote feedback about the blog post process as a comment under this issue

## Comments

`NONE`

**Comment by leonardpahlke** [comment]
Cc @caradelia @patricia-cahill

**Comment by jkutner** [comment]
PR opened at https://github.com/cncf/tag-env-sustainability/pull/283

**Comment by leonardpahlke** [comment]
Blog post published: https://tag-env-sustainability.cncf.io/blog/2023-12-reduce-reuse-rebase-buildpacks/

**Comment by leonardpahlke** [comment]
Thank you @jkutner!

**Comment by leonardpahlke** [comment]
Blog is scheduled to be release on the CNCF Blog Jan.10

**Comment by guidemetothemoon** [comment]
Blog published on CNCF website: https://www.cncf.io/blog/2024/01/11/reduce-reuse-rebase-sustainable-containers-with-buildpacks/

@leonardpahlke are we ok with closing this issue?
