### ISSUE TITLE
[Project Tracking] Cloud Native Sustainability Week 2024

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#290]
Hello all, after the success of the Cloud Native Sustainability Week 2023 (issue https://github.com/cncf/tag-env-sustainability/issues/95) we would like to continue the event on a yearly basis. Event information can be found on our website https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/.

**We are looking for a lead organizer who will take over the main organization of the event.** You will be supported by TAG ENV and the local Meetup organizers will take responsibility for organizing their personal event. However, as the main organizer, it is a lot of work to pull all the strings together. It is also possible to divide the responsibility between several people. If you are interested in leading the event, post a comment, you can also message @leonardpahlke via Slack if you are unsure.

Links:
* cloud native sustainability week 2024 event doc: https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/

cc TAG ENV leads @cncf/tag-env-sustainability 

Additional material to learn more about the event and its organization:

- Cloud Native Sustainability Week Event page: https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week
- Cloud Native Sustainability Week 2023 Re-cap blog post: https://tag-env-sustainability.cncf.io/blog/2024-wrap-up-cloud-native-sustainability-week-2023
- Local Meetup organizer guide: https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit?usp=sharing 
- Local Meetup organizer 2023 organizer session recordings: https://youtube.com/playlist?list=PL_3_oSSuNpD7_mljq_sOLl9bBvFt2mA89&si=wO17CdzM52nbj9-e
- Retro cloud native sustainability week 2023: https://github.com/cncf/tag-env-sustainability/issues/261

**Comment by ams0** [comment]
I would like to propose myself as lead organiser, if not globally at least for the EMEA timezone. I suggest we start with:

- [ ] Analyse feedback from 2023
- [ ] Choosing a week around October
- [ ] Create the materials (website, docs, blogs)
- [ ] Start promoting and recruiting local chapters
- [ ] Offer structured support to local chapters
- [ ] Prepare surveys and collect feedback

If we start now we'll have enough time to make it an even bigger than last year! And be ready for KubeconNA 2024 where we can share our collective learnings

**Comment by leonardpahlke** [comment]
@ams0 assigned you to the issue! Thanks

**Comment by guidemetothemoon** [comment]
Great that you would like to step up as a lead for organizing the 2024 event @ams0 ! I would be happy to be part of this in the TAG tech lead capacity and help out with the planning where it's needed.

It would be good to have a few more folks joining in on taking the lead and helping out with planning - maybe we can have a meeting where we can talk about the details of organizing the event, share our experiences from organizing 2023 event and just help with aligning expectations for those who may be interested in contributing, maybe even leading the event organization? WDYT @leonardpahlke @ams0 ?

Regarding analysis of the 2023 survey results - I know that @xamebax has done an amazing job of aggregating the data and highlighting the overall feedback for the Cloud Native Sustainability Week 2023 wrap-up blog post. Could you maybe share the spreadsheet with the aggregation work that you've done so that organizers for the 2024 event can take a closer look @xamebax?☺️

**Comment by leonardpahlke** [comment]
That is a great idea 👍 @guidemetothemoon would you mind looking setting up a meeting for next or the following week?

**Comment by guidemetothemoon** [comment]
Yes, I can make that happen @leonardpahlke !😊

**Comment by guidemetothemoon** [comment]
Created two meetings on the 21st of February to accomodate different time zones. Also, the date is after the Lunar calendar vacation time for China to make sure that as many as possible can join.

**Comment by immavalls** [comment]
I'd love to be a part of this in 2024, the local meetup in Barcelona was a great way to restart the Cloud Native groups and I would love to contribute more this time.

**Comment by guidemetothemoon** [comment]
Awesome that you would like to be a part of this @immavalls! I hope that you will be able to join our organizer intro meeting on the 21st of February (it's already in the TAG ENV Google calendar), but if not, we'll also share the recording afterwards☺️

**Comment by xamebax** [comment]
@guidemetothemoon I'm sorry for this delayed response, I haven't figured out github notifications properly yet. 😬 I think I made my process sound more sophisticated than it was (it was quite manual), but anyway having all responses in a single sheet was a time saver, so here it is: https://docs.google.com/spreadsheets/d/1ObdNzv1hehmZboMdgdCizAlmGAP3Wjt9yEmf94d5cfs/edit?usp=sharing

**Comment by Spazzy757** [comment]
Hi,

We are looking at doing a 1 day in-person conference around green tech in Amsterdam

cc @muemich @gabibeyer @pinireznik

**Comment by wrkode** [comment]
I'm ready to help out in any capacity.

**Comment by truthtrap** [comment]
we are eager to help organizing the global part and we can help @ams0 (et al.). once my colleague is back i'll direct her to this issue. in the meantime i am your person :)

**Comment by pchunyayev** [comment]
I'm ready to help :) a full-day conference in Amsterdam is a terrific idea!

**Comment by Nancy-Chauhan** [comment]
Hey folks! I really enjoyed volunteering last year for the global remote mini conference and organizing a mini conference in India during Sustainability Week 🌱 With this experience, I would like to contribute and support as a co-lead organizer. I will be able to work in the Eastern Time zone 🚀

I am looking forward to getting more people involved and advocating for it 💜

**Comment by guidemetothemoon** [comment]
This is awesome, @Nancy-Chauhan ! I will add you as an assignee here as well, and we can start looking into this after KubeCon+CloudNativeCon Europe😊

**Comment by sergioarmgpl** [comment]
I want to contribute again with Cloud Native Guatemala too, like last year.

**Comment by immavalls** [comment]
Hi team, shall we get this started now that KubeCon Europe is behind us? I'm not usually able to make it to the TAG calls as they collide with my team calls at work, though very happy to help with this asynchronously.

**Comment by leonardpahlke** [comment]
Yes, we talked in todays TAG ENV meeting about the cloud native sustainability week. We created a new channel tag-env-cloud-native-sustainability-week to collaborate async. @Nancy-Chauhan we need to start a meeting series to start planning the event. @JulieChenadec mentioned interest supporting with the organization of the global event 🙌.

**Comment by karenhchu** [comment]
👋 hello! glad to have been a part of last year's event! would love to be more involved this year if you'll have me :) i've joined the CNCf slack channel for now

**Comment by JulieChenadec** [comment]
Hello everyone! Indeed, I'm happy to support the global organisation! I have joined the Slack channel too :)

**Comment by Nancy-Chauhan** [comment]
> Yes, we talked in todays TAG ENV meeting about the cloud native sustainability week. We created a new channel tag-env-cloud-native-sustainability-week to collaborate async. @Nancy-Chauhan we need to start a meeting series to start planning the event. @JulieChenadec mentioned interest supporting with the organization of the global event 🙌.

Hey @leonardpahlke Sure, I would be discussing this over #tag-env-cloud-native-sustainability-week slack channel. @JulieChenadec Thank you for showing interest in supporting with the organization. Looking forward to it 🚀

**Comment by sunya-ch** [comment]
Hello, team. I'm eager to bring this fantastic event to Japan this year 💚 
Please count me in 🤙

**Comment by SamYuan1990** [comment]
Keep eye on this for now. Once the event been set, I will try to organize in China.

**Comment by xamebax** [comment]
I would like to help with organizing events in Norway, and I have capacity to contribute to this starting May. (cc @guidemetothemoon)

**Comment by guidemetothemoon** [comment]
Yes, we will organize a meetup in the GSF Oslo meetup group as part of Cloud Native Sustainability Week, like we did last year! Great that you would like to help out with organization this year, @xamebax, I'll be happy to pair up with you on this🤩

**Comment by sunya-ch** [comment]
Please count me in. I would like to organize the local event in Japan as part of sustainability week this year 💚

**Comment by Nancy-Chauhan** [comment]
Hey, Folks 👋 Thank you for showing interest. We have shared [doodle](https://doodle.com/meeting/participate/id/erMZrmpd) link in #tag-env-cloud-native-sustainability-week slack channel (CNCF Slack) to set up weekly calls from next week to kickstart our discussions for Cloud Native Sustainability Week. Please feel free to have a look.

**Comment by JulieChenadec** [comment]
I would like to help in organizing events in the Netherlands - and supporting the global event with @Nancy-Chauhan !

**Comment by krol3** [comment]
Happy to help like last year with Cloud Native sao paulo 🇧🇷 too.

**Comment by Nancy-Chauhan** [comment]
Thank you @JulieChenadec @akelity for showing interest! I have added you in the [meeting notes](https://docs.google.com/document/d/1GoYda1d6nE0rqpI5ubIBFeBdgHTtapX_1-DEGW4h2o0/edit#heading=h.myyff6uor7mu) doc 🙌 

Thank you @krol3 🚀 We are looking forward to it. We have started syncing biweekly on Monday's 16 CET. Here is the [TAG ENV calendar ](https://calendar.google.com/calendar/u/0/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1@group.calendar.google.com&ctz=America/Chicago)

**Comment by Nancy-Chauhan** [comment]
Awesome @krol3 @vallss , This is awesome! Thank you for reaching out 🚀

**Comment by saiyam1814** [comment]
I and Divya Mohan did sustainability week on Kubesimplify and I think we would like to do it again this time. We can even get the best presentations in for this superstream series!

**Comment by Santosh-Kumar-Perumal** [comment]
### 🌍 Interested in Hosting Local or Virtual Meetups on Sustainability and Net Zero Carbon Emissions in London 🌿

---

I am **excited** to host local or virtual meetups in London focusing on **sustainability** and **net zero carbon emissions**.

---

### 🔧 Professional Experience

- **10 years of IT experience**
- Nearly **5 years in the UK**
- Currently a **Senior Consultant** specializing in cloud-native technologies:
  - **Kubernetes**
  - **Docker**
  - **Opentelemety**
 

---

### 🎤 Community Engagement
#
- **Speaker** at notable forums:
  - **Kubernetes Community Days**
  - **DevFest London**

---

### 🤝 Volunteering and Organizing

- Strong track record of **volunteering** and **organizing**:
  - Local meetups
  - Significant events such as the **OpenUK SocCon** event

### 🏅 Honours

- **Calico Big Cat**
- **Linux Foundation CD Ambassador**
- **Google Women Techmakers Ambassador**

### 🌐 Website

Sessionize Link: [Santosh Kumar Perumal](https://sessionize.com/santosh-kumar-perumal/)
🌟 **Join me in making a difference!** Let's work together towards a sustainable future.

@Nancy-Chauhan @JulieChenadec

**Comment by sestegra** [comment]
I will organized a local meetup in Luxembourg.
https://community.cncf.io/luxembourg/

**Comment by ams0** [comment]
Amsterdam update: we're locking the University of Amsterdam venue (https://www.sustainalab.nl/) for the 10th of October, long format (12:00 to 19:00), with light lunch, plenty of speakers (possibly 2 rooms, and inviting University professors and local sustainability heroes). Keep you posted! 

cc @JulieChenadec

**Comment by mitul3737** [comment]
Hey folks, I would like to arrange for Cloud Native Dhaka this year. Please do let me know if I need to share any more details.

Thank you

**Comment by JulieChenadec** [comment]
@Santosh-Kumar-Perumal @vinodsr007 
Doing a bit of matchmaking here :) You are both based in London and eager to organize a session there.  Or perhaps you have already started planning it? @Nancy-Chauhan and I can support you in any way you want.

**Comment by Santosh-Kumar-Perumal** [comment]
Hi @JulieChenadec and @Nancy-Chauhan 
Yes, both @vinodsr007 and I are based in London and know each other through our frequent collaboration on community volunteer events. We are happy to participate in any activity but would appreciate your guidance on how to choose and begin contributing to communication efforts, blog posts, or any other needed tasks. I believe the following tasks need to be addressed:

**Local Meetup Organizers:**
   - Locating a suitable venue for the event
   - Identifying and inviting speakers
   - Finding a sponsor for food and drinks
   - Establishing the chapter within the CNCF community groups
   - Hosting the meetup in person
   - Planning and scheduling the session
   - If feasible, recording the sessions

**Event Week Organizers:**
   - Developing welcome slides to introduce the event, CNCF, and TAG ENV, which can be used during the local meetup.
   - Creating a feedback survey for organizers to gather their input and suggestions, aligning with the mentioned goals. Evaluate the survey.
   - Creating a survey to collect feedback from end users attending the meetups, aligning with the mentioned goals. Evaluate the survey.
   - Issuing credly badges to recognize and acknowledge meetup organizers (and potentially speakers).
   - Collaborating with the CNCF to promote the meetups on social media platforms.
   - Coordinating the virtual TAG ENV meetup.
   - Establishing a dedicated website page for the event, either using the TAG ENV website or creating a new domain like cloudnative-sustainability.com.
   - Uploading the sessions to YouTube, using the CNCF TAG ENV channel.
   - Providing support in reviewing talk submissions for local meetups.

**Comment by Nancy-Chauhan** [comment]
Hello Folks 👋 We have created an issue template to help track and manage local meetup organization tasks. This new template is designed to provide a clear and structured way for organizers to detail their event plans, ensuring that all necessary information is included and the process is streamlined. 

It would be nice & helpful if you could create an issue that will help us manage better - You can create a new issue and use a template named "Cloud Native Sustainability Week Local Meetup Tracking Issue"

**Comment by leonardpahlke** [comment]
Yes! If you are thinking about or are already planning to host a meetup during the cloud native sustainability week please open up an [issue](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=issue%2Fneeds-triage%2Cproject%2Fcloud-native-sustainability-week&projects=cncf%2F10&template=10-local-meetup.yml&title=%5BTracking%5D+Cloud+Native+Sustainability+Week+%3CYear%3E+%3CMeetup+Location%3E) 🙌

**Comment by JulieChenadec** [comment]
@sergioarmgpl Earlier, you showed interest in organizing a meetup in Guatemala! 
You can create a new issue here: https://github.com/cncf/tag-env-sustainability/labels/project%2Fcloud-native-sustainability-week
@Nancy-Chauhan

**Comment by JulieChenadec** [comment]
Hi Michel @akelity, would you like to create a new issue for your meetup in Milan so we can keep track of all the planned events? :) 
https://github.com/cncf/tag-env-sustainability/labels/project%2Fcloud-native-sustainability-week
(FYI @Nancy-Chauhan)

**Comment by JulieChenadec** [comment]
Hey @mitul3737 Great to see you want to organise a meetup in Dhaka, please feel free to open a new issue so we can keep track of all the events https://github.com/cncf/tag-env-sustainability/labels/project%2Fcloud-native-sustainability-week

**Comment by sergioarmgpl** [comment]
Issue created @JulieChenadec

**Comment by vallss** [comment]
Issue created for Milan meetup @JulieChenadec @akelity :smile:

**Comment by mrchrisadams** [comment]
oh sweet. it looks like there is!

https://www.youtube.com/watch?v=9gHoTJ4wbbs&list=PL_3_oSSuNpD7I2OHgywlAuKnJf700wcXH

are the talk decks easily accessible at anywhere too?

**Comment by claire-fletcher** [comment]
cc @Nancy-Chauhan 

> oh sweet. it looks like there is!
> 
> https://www.youtube.com/watch?v=9gHoTJ4wbbs&list=PL_3_oSSuNpD7I2OHgywlAuKnJf700wcXH
> 
> are the talk decks easily accessible at anywhere too?
