### ISSUE TITLE
[Project Tracking] Rework the TAG ENV landscape document

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#302]
Draft of the landscape document v2 is available in following Google Doc: https://docs.google.com/document/d/1-zZYAGyTB59GeVoM7NDCYGtDpB6mH0i3jt8EOAZ5VCI/edit?usp=sharing

This issue is a followup action which we discussed in GitHub Discussion: https://github.com/cncf/tag-env-sustainability/discussions/276

### Q: Explore options on how to move forward with the TAG ENV landscape document

<div type='discussions-op-text'>

<sup>Originally posted by @leonardpahlke November 15, 2023 ([link](https://github.com/cncf/tag-env-sustainability/discussions/276))</sup>
Hey all, the TAG ENV worked on a [landscape document](https://tag-env-sustainability.cncf.io/landscape/). The landscape was published as an early preview, with gaps we knew about. After we published the document (early 2023) not a lot changed. The landscape document is an important artifact which can help the community. We should find a way how we can move forward. 

1. Which purpose serves the landscape in the community, and does the current form solve this purpose best?
2. How can we drive the landscape document as a project to make sure it has some velocity (perhaps velocity will be achived if we get the purpose question right)
3. Who takes ownership
</div>

---

### A: Path to move forward

<sup>Commented by @by-d-sign December 6, 2023 ([link](https://github.com/cncf/tag-env-sustainability/discussions/276#discussioncomment-7776811))</sup>

To the 1. question: I believe the landscape document should:

1. provide an overview over the current state of sustainable cloud tech. This includes:
     a.     an introduction of central ideas, concepts, and practices,
     b.     anything that goes beyond an introduction should be moved into a separate document, which is then referenced by the landscape document, for further reading,
     c.     Maybe it could also highlight not only the achievements and best-practices, which we have and know, but also where we are currently lacking and what we are researching/working on, plus links to how and where to contribute, 
2. be targeted towards readers with prior knowledge about cloud technology. It should specifically target:
     a.     Data Center Operators,
     b.     Cloud Service Providers,
     c.     Cloud and Software Engineers,
     d.     Perhaps End Users too.
 
To the 2. and 3. question: I have some ideas on how to restructure, refocuse and ultimately rewrite the landscape document.
I propose the following structure (This should only be an overview of the rough layout and not the actual headlines):

1. Introduction
2. General Concepts and Fundamentals
4. Shared responsibility model
5. Topics for Cloud Services Providers & Data Center Operators
6. Topics for (Cloud) Software Engineers
7. Aspects for End Users 
8. Further Reading

I’d be happy to write something up as a first draft for a landscape version V1.0, if you are interested.
I know that this is no long-term solution to provide velocity, but perhaps it can kick-start it? I believe that for the future the landscape doc must find a home at a TAG WG.

Note: As one of the co-authors of the original landscape document, I may be biased. So let me know what you think.

### Project Details

- **Project leads**:
  - @by-d-sign 
  - tbd
- **TAG ENV Lead representative**: @catblade 
- **Project started**: 2024-12-07
- **Project completed at**: *XX-XX-XX*
- **Project drive folder**: [link](https://drive.google.com/drive/folders/1akSjtf5sL09GrQcqwvVvbVu4RrPGcfdF?usp=share_link)
- **Meeting Details**: 
  - *link*: `77777`
  - Meeting Notes: [link](https://docs.google.com/document/d/1WU3TDMLDUPatNLH9KXAU9xI4uMSAhCJ2DGdNJ4AJmvM/edit?usp=sharing)
  - Schedule: *every two weeks tbd….* see [calendar](https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com)
  - Past Meetings:
    - XX-XX: meeting title - YT recording link 

### TODO

- **Starting up**:
  - [ ] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
  - [ ] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
  - [x] Project Google Drive folder created 
    - [x] Meeting Notes document created
  - [ ] Meeting Time & Day scheduled 
- **Report to the TAG ENV every two weeks**:
  - Update summary given on *XX-XX*: *update summary*
  - ...
- **Closing the project**:
  - [ ] Reached out to the TAG Lead representative to complete the project deliverables
  - [ ] Deliverables releases to the community if applicable
  - [ ] Project retrospective [issue opened](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=presentation%2C+triage-required&projects=&template=retrospective.md&title=%5BRETRO%5D+project+title)
  - [ ] Project retrospective completed

**Comment by leonardpahlke** [comment]
@by-d-sign, if you have a draft version available, that would be great to see to get early feedback in and allow collab!

**Comment by guidemetothemoon** [comment]
I decided to not make any changes to the existing version of the landscape document since @by-d-sign is making quite extensive rewrite and restructuring so it would just become chaotic.

+1 to what @leonardpahlke said: I'll be happy to review and help out with merging the new version on the dedicated `landscape-document` branch. Please reach out if you need help with getting the draft version out and publicly available @by-d-sign ☺️

**Comment by leonardpahlke** [comment]
@by-d-sign could you share the current status of development here? So we can support!

**Comment by by-d-sign** [comment]
Yes, absolutely thank you (@leonardpahlke and @guidemetothemoon) for the reminder/help. I just finished the first of three major parts, but I belief that the remaining two parts will be less time consuming to write. However, I also think that the landscape document would really benefit from good visuals, which I am currently struggling with. Therefore, I will share a status with placeholders instead of proper images/graphics.

**Comment by by-d-sign** [comment]
You can find my draft/work in progress document here: https://github.com/by-d-sign/wg-env-sustainability/blob/landscape-document/website/content/en/landscape/landscape%20V2.md

**Comment by catblade** [comment]
What are sections 2 and 3, that you are planning?

**Comment by by-d-sign** [comment]
@catblade , I was hoping that mentioning them in the table of contents, would be descriptive enough. However, I can see that it is not nearly enough information. My general plan was to split the document into 3 parts:

1. overview
2. what is sustainable cloud and how can cloud sustainability be measured
3. how can the measured numbers (status-quo) be optimized

Since there is a lot in the current landscape document about these topics already, I am trying to reuse, restructure and reduce the content we already have and add parts of the puzzle that I think are currently missing. However, this is more challenging than I anticipated. 😅

**Comment by guidemetothemoon** [comment]
@by-d-sign there has been a lot of interest to contribute to the new version of the landscape document and during discussion in the WG Comms it has bee clear that it's quite challenging to collaborate and contribute in an efficient manner in GitHub.

Therefore I have taken your current changes and moved them to a Google Doc where we can collaborate in the TAG until the new version is ready to be moved to the repo. I hope that it's OK with you😊

Here's the doc (also linked to the issue description): https://docs.google.com/document/d/1-zZYAGyTB59GeVoM7NDCYGtDpB6mH0i3jt8EOAZ5VCI/edit?usp=sharing
 
FYI @catblade @leonardpahlke @caradelia @patricia-cahill

**Comment by leonardpahlke** [comment]
Thanks @guidemetothemoon!!

**Comment by leonardpahlke** [comment]
We discussed in the TAG ENV meeting April 3rd to start a meeting series and try to engage more folks in this project.

I’ve updated the issue description with some details including todo items.

> ### TODO
> 
> - **Starting up**:
>   - [ ] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
>   - [ ] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
>   - [x] Project Google Drive folder created 
>     - [x] Meeting Notes document created
>   - [ ] Meeting Time & Day scheduled 

@by-d-sign could you add the project to the website & take a look at the other items above. @catblade we need to get meetings setup - maybe every two weeks or so until we finalized the v2 landscape version. I would propose moving this after the v2 version to WG Comms & perhaps have a dedicated Tech Lead focusing on maintaining the document (cc @claire-fletcher @patricia-cahill).

**Comment by leonardpahlke** [comment]
I am closing this issue since the project around rewriting the current landscape document was closed. We will continue improving the landscape document - this will be discussed in another issue.
