### ISSUE TITLE
[Action] TAG 2024 Roadmap Planning

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#321]
We previously initiated a discussion to gather project ideas in #277 and have since reviewed these proposals in the latest TAG meetings (see below for proposed and ongoing projects). The goal is to compile a realistic set of objectives for the TAG to focus on. This could be visualized in a histogram-like view, categorizing projects as core objectives, planned initiatives, or optional endeavors. While formulating this discussion, it's crucial to recognize that these are generally substantial initiatives. Routine activities like writing blog posts, presenting maintainer talks, enhancing the website, or inviting projects to our meetings, although time-consuming, are not the primary focus here but are still integral parts of our operations. 

- [ ] 1. Review / clarify outstanding project proposals (until end of Jan).
- [ ] 2. Get leads for each project (until end of Jan).
- [ ] 3. Plan deadlines and write mini project outlines, with a clear scope, goals non goals and deliverables (until first week of Feb).
- [ ] 4. Request for comment on the list of accepted project proposals (mid Feb).

## Projects already planned

* WG Green Reviews work (https://github.com/cncf-tags/green-reviews-tooling)
* WG Comms work
    * Kubecon EU presence
    * Kubecon NA presence
    * Cloud Native Sustainability Week 2024 (https://github.com/cncf/tag-env-sustainability/issues/290)
    * + a couple of smaller scoped projects which are discussed in the WG context
* Landscape document rewrite (https://github.com/cncf/tag-env-sustainability/issues/302)
* Cloud Native Sustainability learning path (https://github.com/cncf/tag-env-sustainability/issues/52)

#### Sustainability Certification Badge after SEED Proposal (scope:❌, status: rejected)
* **Proposed by [brianirish](https://github.com/brianirish)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7623911)): Design a certification process for sustainable software. Idea came up by looking into the System Energy and Environmental Design (SEED) Program, similar to the LEED program for the construction industry, to rate companies based on sustainability.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8181959)): The proposal exceeds the TAG's scope, aligning more with for example the Green Software Foundation's objectives. The TAG lacks the resources for such a large-scale undertaking and we should also be cautious about potential "greenwashing" risks. Moreover, pursuing this project could diverge from the TAG's core mission and might be better handled through collaboration with organizations specializing in this field.

#### Benchmarking (scope:✅, status: to be evaluated for 2024)
* **Proposed by [felipehuici](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7631292) & [ArneTR](https://github.com/ArneTR)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7631292), [link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7627032)): Conduct benchmarking and diving into deployment efficiency, including metrics like image size, build times, memory consumption, server density, performance and network.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182083)): The idea was noted to fall within the scope of TAG and is feasible. It relates to WG Green Reviews but could be considered a separate project to avoid disturbing the development flow of the WG. We suggested focusing on a limited scope, like just networking, and possibly writing a whitepaper on the topic. This may lead into a more research focused WG.

#### Sustainability Card in CNCF Landscape (scope:✅, status: to be evaluated for 2024)
* **Proposed by [mbianchidev](https://github.com/mbianchidev)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7631481)): Create a sustainability card in the main CNCF Landscape to showcase tools for measuring and reducing the carbon footprint of cloud-native workloads.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182101)): We discussed this in the past and might be a good follow-up action depending on the outcome of the current landscape document rewrite ([#302](https://github.com/cncf/tag-env-sustainability/issues/302)).

#### Asia, Internationalization and Global Inclusion (scope:✅, status: accepted)
* **Proposed by [SamYuan1990](https://github.com/SamYuan1990)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7631487)): Implement i18n and different timezone meetings to include a wider global audience and possibly have a keynote at Kubecon China/Asia in 2024.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182137)): We support the idea, and we mentioned plans to start Asia-friendly meetups  in Q1 and are considering participation in Kubecon China depending on TAG folks attending the conference.

#### Metrics and Peaks for Sustainable Computing (scope:❓, status: to be evaluated for 2024)
* **Proposed by [SamYuan1990](https://github.com/SamYuan1990)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7631896)): Collect metrics for projects like Kepler to use in training ML models for scheduling k8s pods by energy consumption.
* **Feedback**: Asked for clarification and expansion on the idea of collecting metrics and building a database. Perhaps its close to the benchmarking idea.

#### Documenting User Stories for Tools and Patterns (scope:✅, status: accepted for 2024)
* **Proposed by [nikimanoledaki](https://github.com/nikimanoledaki)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7635965)): Continue documenting user stories for tools and patterns discussed in TAG ENV, focusing on carbon, energy, and cost savings, and how cloud-native tools are implemented for optimization.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182219)): We emphasized the need for improved communication and interaction with other community groups. A couple of ideas are proposed that we already integrate / discuss in WG Communications.

#### Kubetrain as an Official TAG Project (scope:❌, status: rejected)
* **Proposed by [mbianchidev](https://github.com/mbianchidev)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7755094)): Consider making Kubetrain an official project for the TAG, with a working group, especially if the pilot project at KubeCon Paris 2024 is successful.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182341)): While Kubetrain is a great initiative, the TAG's focus is on technical advice for cloud-native sustainability, not activism, and therefore the scope of Kubetrain as it stands now does not align with the TAG's mission.

#### Project idea around a “Rosetta Stone” for CO2 intensity by region (scope:❓, status: to be evaluated for 2024)
* **Proposed by [wrkode](https://github.com/wrkode)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7755162)): Expand the effort in CO2 emission calculation and Power Usage Efficiency, possibly creating a "Rosetta Stone for CO2 intensity by region."
* **Feedback**: No feedback just yet. 

#### Projects Around Food Sustainability (scope:❌, status: rejected)
* **Proposed by [sergioarmgpl](https://github.com/sergioarmgpl)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7778581)): Implement an architecture diagram for farmers to take advantage of, pushing the idea through speaking sessions at events.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182378)): While food sustainability is interesting, it is out of scope for the TAG, which focuses on technical advice for cloud-native sustainability. It may be a topic for the upcoming [UN/KCCN EU 2024 Hackathon](https://www.cncf.io/blog/2023/12/20/kubecon-cloudnativecon-europe-hackathon-challenges-brought-to-you-by-the-united-nations/).

#### Engagement with OpenTelemetry for Sustainability Metrics (scope:✅, status: to be evaluated for 2024)
* **Proposed by [musingvirtual](https://github.com/musingvirtual)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7791912)): Engage with the OpenTelemetry project to define and implement sustainability metrics.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8181862)): We responded positively, discussing possible collaborations and scheduling meetings to further the engagement. We yet need to discuss which steps to take.

#### Newsletter for TAG (scope:✅, status: to be evaluated for 2024)
* **Proposed by [octonawish-akcodes](https://github.com/octonawish-akcodes)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7833937)): Create a newsletter for the TAG to highlight key factors influencing environmental sustainability in the cloud-native ecosystem.
* **Feedback** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-8182404)): We suggested for now that WG Comms look into this proposal and share their thoughts.

#### Best Practices for Running Sustainable Kubernetes Clusters (scope:✅, status: accepted for 2024)
* **Proposed by [xamebax](https://github.com/xamebax)** ([link](https://github.com/cncf/tag-env-sustainability/discussions/277#discussioncomment-7865987)): Pick up work on best practices for sustainable Kubernetes clusters, possibly creating a project led by [xamebax](https://github.com/xamebax) and [JacobValdemar](https://github.com/JacobValdemar).
* **Feedback**: The idea of exploring sustainability issues specificially in the K8s context is a great idea to pick up again. We have asked if [xamebax](https://github.com/xamebax) and [JacobValdemar](https://github.com/JacobValdemar) could lead/co-lead the project with the support of other TAG members, which [JacobValdemar](https://github.com/JacobValdemar) has answered positively so far.

CC @catblade @mkorbi

**Comment by SamYuan1990** [comment]
We just broad cast the survey on Chinese local social media with help from LF member. :-)
