### ISSUE TITLE
[Action] Kubecon EU 2024 Booth Schedule

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#338]
Hey all, this year the TAG ENV has a mini booth.

## Information shared with us

AM Shift Schedule
* Wednesday, 20 March: 10:45 - 15:00
* Thursday, 21 March: 10:30 - 13:30
* Friday, 22 March: 10:30 - 12:30

**In-Person Project Kiosk**:

* Kiosk with one (1) monitor, one (1) locked cabinet for storage, and project logo signage only
* **Project Requirements**: Staff the booth during the outlined showcase hours. 
* **CNCF Event Team Assistance**: The CNCF events teams will ensure that the kiosk is set-up correctly and will be available for any assistance needed. 
* **When planning for the kiosk, please keep in mind**: Complimentary passes will NOT be included with hosting a kiosk in the Project Pavilion and custom graphics are not permitted.
* **Promote Your Project**: Let the community know you will be at KubeCon + CloudNativeCon by posting on socials and updating your website
     * Generate buzz about your project's participation at KubeCon + CloudNativeCon by leveraging our [toolkit ](https://linuxfoundation-dot-yamm-track.appspot.com/2wbFe9jqY8rjgOIDs6WnbMUkHTSARyUsYhtsb65MMpoXLjfR7jQEVQ9cRdV2j31ZYpcEkP4AD7ptPvkV0dZeGTaU2OmRiEX0lp6Nw-gAufsXld8WwyVp-4BVF_-2knncuXe4JerOsK8Zo9LZoBd8CN4tPUH8TR2Z_zX1O73yfEQ9GUvz3Ilfwguo4vWuVnyMao14apK5KqbO6SWdyJbyl_Kcs7SsIsr3sSh3-If_FIlX5-P6WE4sOu624tAzjqBVspQ) to craft engaging social media posts.
     * Showcase your commitment by updating your website with an eye-catching banner, inviting the community to engage with your project firsthand at the event.

## To-do

- [ ] We need to know who's at the conference of TAG contributors
- [ ] Defining a schedule, having 2 persons at the booth during booth hours.
- [ ] Get some material on the screen (either our website, or some sort of slideshow)
- [ ] Discuss if we like to have a print out / sticker or so at the booth
- [ ] Communicate the schedule to the community and ask to meet us there!

—

ref related issue conference checklist: https://github.com/cncf/tag-env-sustainability/issues/270

cc @caradelia @patricia-cahill @mkorbi
cc @claire-fletcher

**Comment by claire-fletcher** [comment]
Suggestion that timeslots can be around 30mins to 1hr slots. We will make a shift schedule in a google sheet with roles for people to sign up to. I'll combine it with a message about attendees. 

Could we get a google sheet created in the drive @leonardpahlke?

**Comment by leonardpahlke** [comment]
Sure, created the google sheet file: https://docs.google.com/spreadsheets/d/1iOSa8f7RM76Cf0tYvxMdyEb08bW_Mv7ag7k-1IRUGE0/edit?usp=sharing

**Comment by vallss** [comment]
@leonardpahlke @claire-fletcher Is someone already taking care of the point `Communicate the schedule to the community and ask to meet us there!`? During wg-comms meeting a couple of weeks ago I offered myself to gather the list of speakers and a small bio of each talk but on the KubeCon schedule there isn't the "Sustainability" or similar filter. Do we already have at least the speakers' names so it's easier to find them on the schedule?

Also, do you think it would be better to create a dedicated issue?

**Comment by leonardpahlke** [comment]
cc @ams0

**Comment by leonardpahlke** [comment]
> @leonardpahlke @claire-fletcher Is someone already taking care of the point Communicate the schedule to the community and ask to meet us there!? During wg-comms meeting a couple of weeks ago I offered myself to gather the list of speakers and a small bio of each talk but on the KubeCon schedule there isn't the "Sustainability" or similar filter. Do we already have at least the speakers' names so it's easier to find them on the schedule?

> Also, do you think it would be better to create a dedicated issue?

@caradelia @patricia-cahill ^

**Comment by guidemetothemoon** [comment]
@claire-fletcher I saw that Max already added himself in the time sheet so I did as well, but it seems like you wanted to make some adjustments to it, like adding the roles and such? We should probably post it in our Slack channel soon so that folks get enough time to add themselves and adjust for their schedules. Do you need any help with getting the time sheet ready and if it's ready do you have some capacity to post about it in our Slack channels and encourage folks to join?☺️

**Comment by claire-fletcher** [comment]
I was wondering also (@leonardpahlke ?) if we have any stickers. I know there was some at KubeCon NA 2023, would be great to have them at this conference if there are any left.

**Comment by wrkode** [comment]
I have added myself to the sheet

**Comment by leonardpahlke** [comment]
@claire-fletcher i have a few stickers left. I can bring some.

@claire-fletcher @caradelia @guidemetothemoon what do you think, should we create some special stickers specific for this conference? Some kind of variation of our TAG logo with KCCN EU 2024.

**Comment by claire-fletcher** [comment]
If we have time then totally! People love stickers. I think someone else has mentioned they are bringing some of our normal stickers as well.

**Comment by catblade** [comment]
STICKERS!!!!

**Comment by guidemetothemoon** [comment]
> @claire-fletcher i have a few stickers left. I can bring some.
> 
> @claire-fletcher @caradelia @guidemetothemoon what do you think, should we create some special stickers specific for this conference? Some kind of variation of our TAG logo with KCCN EU 2024.

If someone can help with the design (my talent there is minimal😁) then I'm all for it! I can help out with printing if needed, but we should do it pretty soon since it will take a few days to produce those.
I tried to test out something in Canva, maybe it can give some inspiration to whoever would like to do some designer-mind magic with it😅
![Design_uten_navn-removebg-preview](https://github.com/cncf/tag-env-sustainability/assets/47773700/233e6cb4-0b96-4f95-963e-2dd7451bdf8b)

**Comment by Bamistand** [comment]
@guidemetothemoon I am just seeing this but I am happy to help. Should I still work on it? Or it's late already?

**Comment by guidemetothemoon** [comment]
@Bamistand no worries! I think that it's too late unfortunately now that it's only a few days left till the event start. But maybe that's something we can look into this for future events :)

**Comment by guidemetothemoon** [comment]
Added the spreadsheet to the "Templates" folder in WG Comms -> EVENTS Google Drive folder for future re-use: https://drive.google.com/drive/folders/1lhNeobXAVhv_R7cXXZM0Xj4a2S7UcbAk?usp=drive_link
Closing this issue.
