### ISSUE TITLE
[PROJECT PROPOSAL] Best practices for environmentally sustainable Kubernetes clusters

### ISSUE THREAD

**Issue by xamebax** [cncf/tag-env-sustainability#339]
### Description

To quote the description from an earlier proposal on this subject ([https://github.com/cncf/tag-env-sustainability/issues/54](https://github.com/cncf/tag-env-sustainability/issues/54)):

> Kubernetes is the key driver and foundation of the cloud native universe. Within this project, we will work on the basic capabilities, best practices and scheduling mechanism as well as extensions to improve the K8s GHG impact.

> Where [there] are patterns, there are anti-patterns, where we improve for speed, resistance and security, there is space for configurations and setting with a negative impact on power consumption and the following chain.

Our ambition is to provide Kubernetes operators with basic, but useful recommendations for running Kubernetes clusters that do less damage to the environment. We want to start small and create a base to expand on in the future.

### Impact

Sustainability is still difficult to prioritize in tech organizations. We hope to have the following impact in organizations that adopt green practices:

- Organizations reduce risks related to capacity in a world with growing need for computing power.
- Achievable, measurable success stories increase confidence of Kubernetes operators and management in larger emission-reducing projects.

### Scope

**In Scope**:
- Kubernetes flavors: Cloud-based Kuberbernetes clusters.
- Target audience: Kubernetes Administrators.
- Refer to other people’s data (“we implemented X and saved Y”) where possible.

**Out of Scope**:
- Kubernetes flavors: bare-metal Kubernetes.
- Target audience: developers running applications on Kubernetes.
- Running rigorous experiments (want to rely on other success stories for data, or on experience-based estimations instead).
- Creating new tools.

#### Goals

Enabling Kubernetes administrators to run more sustainable clusters and identify the best actions to lower their clusters carbon intensity / carbon footprint.

Summarize and vet available information. CNCF is a trustworthy source of information in the cloud-native landscape.

#### Non Goals

We do not have an ambition for a complete, exhaustive list of all actions, as we will try to focus on the highest impact, lowest effort actions (where possible).

### Deliverables

- a guide / actionable list of best practices,
- extra material: background information.

We want to provide actions and optional extra context for operators with extra capacity. We are coming from an understanding of tight time budgets that can be spent on sustainability efforts.

### Additional info and comments

- Reference to supporting material: 
	- Previously gathered tips on the subject: https://docs.google.com/document/d/1lgXe-37JKeIxrRQan9vzVdjzAu8SQzGXKiTOmU2jWkE/edit#heading=h.73pgf6pbinj0 
- Slack channel for discussion and collaboration on the project: #tag-env-k8s-best-practices

## TODO

- [x] Project proposal / suggestion details added to this issue (all section above filled out)
- [x] Project Leads found (one or more)
  - Project Leads: @JacobValdemar, @xamebax
- [x] Project proposal discussed in the TAG
  - Discussed in the TAG ENV meeting on `21-02-2024`
- [x] Project proposal accepted / rejected by the TAG leads
  - Proposal: `accepted`
- [x] Project sponsor found (TAG Chair / TAG TL)
  - @mkorbi is sponsor
- [x] Project tracking issue opened

cc @cncf/tag-env-sustainability

**Comment by leonardpahlke** [comment]
👍, added this to the TAG ENV agenda 21st of Feb.

**Comment by mkorbi** [comment]
Might have some overlap or first good input fro GSF https://patterns.greensoftware.foundation/catalog/cloud/

**Comment by mkorbi** [comment]
Think we are good to go to get the project running

**Comment by xamebax** [comment]
Added a project tracking issue: https://github.com/cncf/tag-env-sustainability/issues/347

Does this mean we can close this proposal issue now?

**Comment by guidemetothemoon** [comment]
Yes, we can close this issue. Thanks!
