### ISSUE TITLE
[PROJECT TRACKING] Green Scraper for automatic event list generation for the TAG ENV website

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#345]
#### Description

This project tracking issue is a follow-up from the initial issue #214 
There is a need to track conferences that focus on environmental sustainability, have green tracks, or may be relevant in terms of speaking opportunities/outreach for the TAG Environmental Sustainability.
We have had some initial discussions in https://github.com/cncf/tag-env-sustainability/issues/59 and this issue is an action that came out of that discussions.

The ideal scenario here would be to have an automated process where a tool/script scrapes sustainability-related sessions and conferences, adds those to the list that is published to the TAG ENV website: https://tag-env-sustainability.cncf.io/events

### Deliverables

Automated GitHub workflow that continuously aggregates a list of sustainability-related conferences, meetups, events, sessions and adds those to the list in one of the pages in the Events section of the TAG ENV website: https://tag-env-sustainability.cncf.io/events

List entries should include (in addition to the event name): session title, speaker names, session description, session date, session location, session link.

**Tools:**
https://github.com/cncf-tags/tag-env-tooling/tree/main/greenscraper
https://github.com/cncf-tags/tag-env-tooling/tree/main/green-talks-scraper

### Project Details

- **Project leads**:
  - @wrkode
  - @Al-HusseinHameedJasim
- **TAG ENV Lead representative**:  @guidemetothemoon 
- **Project started**: *02-04-2024*
- **Project completed at**: *TBA*
- **Project drive folder**: TBA
- **Meeting Details**: TBA
  - *link*: TBA
  - Meeting Notes: TBA
  - Schedule: TBA
  - Past Meetings: TBA
    - XX-XX: meeting title - YT recording link 

### TODO

- **Starting up**:
  - [ ] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
  - [ ] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
  - [ ] Slack Channel created (only if needed) 
  - [ ] Project Google Drive folder created 
    - [ ] Meeting Notes document created
  - [ ] Meeting Time & Day scheduled 
- **Report to the TAG ENV every two weeks**:
  - Update summary given on *XX-XX*: *update summary*
  - ...
- **Closing the project**:
  - [ ] Reached out to the TAG Lead representative to complete the project deliverables
  - [ ] Deliverables releases to the community if applicable
  - [ ] Project retrospective [issue opened](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=presentation%2C+triage-required&projects=&template=retrospective.md&title=%5BRETRO%5D+project+title)
  - [ ] Project retrospective completed

cc @cncf/tag-env-sustainability

**Comment by guidemetothemoon** [comment]
@wrkode @Al-HusseinHameedJasim I have added you both as project leads with support from myself. We will pick up work on this after KubeCon+CloudNativeCon Europe. Please comment on this issue so that I can also assign you to the GH issue directly.

If you have any objections regarding being assigned as a project lead, please let me know and we can follow it up. Other than that, looking forward to getting this project up and running, thanks for your time, engagement and effort till now🤗

**Comment by Al-HusseinHameedJasim** [comment]
Sounds like a plan!

Thank you, @guidemetothemoon for coordinating this.

**Comment by Al-HusseinHameedJasim** [comment]
> Sounds like a plan!
> 
> Thank you, @guidemetothemoon for coordinating this.

Sounds like a plan!

Thank you, @guidemetothemoon for coordinating this.

**Comment by Al-HusseinHameedJasim** [comment]
> @wrkode @Al-HusseinHameedJasim I have added you both as project leads with support from myself. We will pick up work on this after KubeCon+CloudNativeCon Europe. Please comment on this issue so that I can also assign you to the GH issue directly.
> 
> If you have any objections regarding being assigned as a project lead, please let me know and we can follow it up. Other than that, looking forward to getting this project up and running, thanks for your time, engagement and effort till now🤗

Sounds like a plan!

Thank you, @guidemetothemoon for coordinating this.

**Comment by wrkode** [comment]
> @wrkode @Al-HusseinHameedJasim I have added you both as project leads with support from myself. We will pick up work on this after KubeCon+CloudNativeCon Europe. Please comment on this issue so that I can also assign you to the GH issue directly.
> 
> If you have any objections regarding being assigned as a project lead, please let me know and we can follow it up. Other than that, looking forward to getting this project up and running, thanks for your time, engagement and effort till now🤗

LGTM

**Comment by claire-fletcher** [comment]
Hey! We used the green scraper for gathering the sustainability talks from the kubecon schedule. I had some feedback, where would the best place be to leave it? Great work on the tools all! 💚

**Comment by guidemetothemoon** [comment]
Hi @claire-fletcher , please add the feedback here. We will start up the work on this project after Easter and can include the feedback you provide into our planning. Thanks☺️

**Comment by claire-fletcher** [comment]
Feedback:

The scraper was super useful for grabbing all of the talks from Sched. It picked up tonnes and made it much much quicker to create talk lists! One issue I had was that it picked up a couple of talks that weren't actually related to environmental sustainability due to a speaker's company - e.g. " x energy company".

**Comment by Al-HusseinHameedJasim** [comment]
> @wrkode @Al-HusseinHameedJasim I'm ready to kick off further development on this project if you are😊 I suggest that we have a quick sync and align on what remains to be done and how we should do it, as well as see if any distribution of tasks is needed. What dates and times would work for you to have such a meeting in the coming days/weeks? I can facilitate the invitation.

Sounds like a good idea! 😊 
I am available on Mondays and Fridays from 17:00 CEST onwards, and pretty much any time on the weekends would work for me too.

**Comment by guidemetothemoon** [comment]
@Al-HusseinHameedJasim great, thank you! I will set up a meeting for Monday next week in the TAG calendar and reach out to you for an email to send out a personal meeting invite😊

Since @wrkode notified that he doesn't have capacity to lead this project I will join you as a co-lead for now. If anyone else mentions their interest we can always change that. Since it's a project with a small scope I think that it should be ok.

@wrkode you're very much welcome to contribute to this project and join any upcoming meetings whenever you have time and capacity😊

**Comment by vallss** [comment]
Hi everyone! I would like to contribute to this project. Is there anything already "in plan" and/or I can help with?

**Comment by guidemetothemoon** [comment]
Hi @vallss, great that you're interested!😊 We'll have our first meeting on Monday, 22nd of April at 17:00 CET (see TAG ENV's calendar) where we'll plan what needs to be done and how. You're welcome to join if you can, otherwise we will create some tasks based on the outcome from the meeting.

**Comment by vallss** [comment]
@guidemetothemoon I should be able to join on Monday at 17 CET! :blush:
