### ISSUE TITLE
[PROJECT TRACKING] Best practices for environmentally sustainable Kubernetes clusters

### ISSUE THREAD

**Issue by xamebax** [cncf/tag-env-sustainability#347]
## Description

To quote the description from an earlier proposal on this subject ([#54](https://github.com/cncf/tag-env-sustainability/issues/54)):

> Kubernetes is the key driver and foundation of the cloud native universe. Within this project, we will work on the basic capabilities, best practices and scheduling mechanism as well as extensions to improve the K8s GHG impact.

> Where [there] are patterns, there are anti-patterns, where we improve for speed, resistance and security, there is space for configurations and setting with a negative impact on power consumption and the following chain.

Our ambition is to provide Kubernetes operators with basic, but useful recommendations for running Kubernetes clusters that do less damage to the environment. We want to start small and create a base to expand on in the future.

### Impact

Sustainability is still difficult to prioritize in tech organizations. We hope to have the following impact in organizations that adopt green practices:

- Organizations reduce risks related to capacity in a world with growing need for computing power.
- Achievable, measurable success stories increase confidence of Kubernetes operators and management in larger emission-reducing projects.

#### In Scope

- Kubernetes flavors: Cloud-based Kubernetes clusters. Public cloud only.
- Target audience: Kubernetes Administrators.
- Refer to other people’s data (“we implemented X and saved Y”) where possible.

#### Out of Scope

- Kubernetes flavors: 
  - bare-metal Kubernetes,
  - cloud-vendor specific flavors (like EKS, GKE, AKS),
- Target audience: developers running applications on Kubernetes.
- Running rigorous experiments (want to rely on other success stories for data, or on experience-based estimations instead).
- Creating new tools.

#### Goals

Enabling Kubernetes administrators to run more sustainable clusters and identify the best actions to lower their clusters carbon intensity / carbon footprint.

Summarize and vet available information. CNCF is a trustworthy source of information in the cloud-native landscape.

#### Non Goals

We do not have an ambition for a complete, exhaustive list of all actions, as we will try to focus on the highest impact, lowest effort actions (where possible).

### Deliverables

- a guide / actionable list of best practices,
- extra material: background information.

We want to provide actions and optional extra context for operators with extra capacity. We are coming from an understanding of tight time budgets that can be spent on sustainability efforts.

### Additional info and comments

- Reference to supporting material: 
	- Previously gathered tips on the subject: https://docs.google.com/document/d/1lgXe-37JKeIxrRQan9vzVdjzAu8SQzGXKiTOmU2jWkE/edit#heading=h.73pgf6pbinj0 
- Slack channel for discussion and collaboration on the project: #tag-env-k8s-best-practices

### Project Details

- **Project Leads**: 
    - [@JacobValdemar](https://github.com/JacobValdemar)
    - [@xamebax](https://github.com/xamebax)
- **TAG ENV Lead representative**: [@mkorbi](https://github.com/mkorbi)
- **Project started**: *2024-03-04*
- **Project completed at**: *N/A*
- **[Project drive folder](https://drive.google.com/drive/folders/1KVJGOtCGJk9WFn_iS5AxOCyfKa_CM0He)**
- **Meeting Details**: 
  - [Meeting link](https://zoom.us/my/cncftagenvsustainability): password `77777`
  - [Meeting notes on Google Drive](https://docs.google.com/document/d/17mNgY5JNAraTWhOTY_18NQziFKd2UI0bLz4lb2Avcxs/edit)
  - Schedule: *every two weeks on Monday at 13:00 CEST* see [calendar](https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com)
  - Past Meetings (newest on top):
    - 06-05-2024: [CNCF TAG ENV Project Kubernetes Best Practices Meeting 2024-05-06](https://youtu.be/tXpaKZSNQfQ?si=3BsX5bAyHs37_bWy)
    - 15-04-2024:
    - 25-03-2024: [CNCF TAG ENV Meeting 2024-03-25T11:55:31Z](https://www.youtube.com/watch?v=y65--IG7crM)

### TODO

- **Starting up**:
  - [x] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
  - [x] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
  - [x] Slack Channel created (only if needed)
  - [x] Project Google Drive folder created
    - [x] Meeting Notes document created
  - [x] Meeting Time & Day scheduled
- **Report to the TAG ENV every two weeks**:
  - Update summary given on *19-06-2024*: Not much progress on tasks since the TAG meeting June 12th. We had a meeting this Monday with no new attendees. We have discussed how to get new contributors and how to retain contributors for longer.
  - Update summary given on *29-05-2024*: Still collecting feedback on first recommendation, considering to publish recommendations incrementally, new contributors
  - Update summary given on *15-05-2024*: [We're gathering feedback on our first contribution](https://github.com/cncf/tag-env-sustainability/issues/364)
  - Update summary given on *01-05-2024*: We got our first contribution, we have someone new on each meeting
- **Closing the project**:
  - [ ] Reached out to the TAG Lead representative to complete the project deliverables
  - [ ] Deliverables releases to the community if applicable
  - [ ] Project retrospective [issue opened](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=presentation%2C+triage-required&projects=&template=retrospective.md&title=%5BRETRO%5D+project+title)
  - [ ] Project retrospective completed

cc @cncf/tag-env-sustainability

**Comment by xamebax** [comment]
Could someone with permissions add labels to this issue? It's missing `issue/tracking` and maybe its own `project/xxx` label?

**Comment by catblade** [comment]
@leonardpahlke  can you please add tracking to this?  @xamebax  could you please explain this in a meeting?

**Comment by leonardpahlke** [comment]
@catblade the project leads Jacob  & Marta mentioned in Slack that they would like to take a back seat here. So the project dev stopped. There are several issues & a document that were created. We can use the work done to fuel new projects.

**Comment by leonardpahlke** [comment]
Closing this issue as part of the project archival process https://github.com/cncf/tag-env-sustainability/issues/500
