### ISSUE TITLE
[PROJECT PROPOSAL] Illustrated Children's Guide to Green Cloud Native Computing

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#355]
### Description

Just an idea coming up from in person meeting at KubeCon Paris. more details needs to be added.

### Impact

...

### Scope

**In Scope**: ...

**Out of Scope**: ...

### Goals and Non Goals

...

### Deliverables

- *Deliverable A*
- *Deliverable B*

### Additional info and comments

- Reference to supporting material: `NONE`
- Links to related site: `NONE`
- Feel free to delete this section if you don't have more info: `NONE`

## TODO

- [ ] Project proposal / suggestion details added to this issue (all section above filled out)
- [ ] Project Leads found (one or more)
  - Project Leads: *link project leads here*
- [ ] Project proposal discussed in the TAG
  - Discussed in the TAG ENV meeting on `XX-XX`
- [ ] Project proposal accepted / rejected by the TAG leads
  - Proposal: `accepted` / `rejected`
- [ ] Project sponsor found (TAG Chair / TAG TL)
- [ ] Project tracking issue opened

cc @cncf/tag-env-sustainability

**Comment by AntonioDiTuri** [comment]
That's a great idea! I would like to follow up :)

**Comment by by-d-sign** [comment]
Cool proposal! I have some ideas already :).

**Comment by mkorbi** [comment]
I opened a Miro board, think that suits better the creative process :D 
https://miro.com/app/board/uXjVKYwshxw=/?share_link_id=613213648092

Passcode the same as for Zoom just 8 times.
