### ISSUE TITLE
[Tracking/Action] Repair: how broken Kubernetes workloads lead to higher emissions

### ISSUE THREAD

**Issue by xamebax** [cncf/tag-env-sustainability#365]
(ticket is part of sustainable k8s practices project work)

#### Description

What is the carbon cost of leaving broken workloads to run on Kubernetes? What is the untapped potential of making sure workloads repair themselves better, or that broken workloads aren't allowed to run for a long time? Is there a good "Kubernetes hygiene" around repairing workloads that can lead to lowering a cluster's carbon cost?

#### Outcome

A recommendation in our [working document](https://docs.google.com/document/d/12EAPH2vTM7tgqbQOv-9XizlMgQyIWp5LlBsHdry-Dxg/edit) that helps the reader make a choice on how to repair their workloads, with an effort estimation (small, medium, large). Optional extra reading material with extra context if the reader's interested.

#### To-Do

- [ ] add relevant labels to this issue when possible,
- [ ] research if this is a worthy recommendation,
- [ ] if yes, write a recommendation,
- [ ] share it for review, implement feedback.

#### Comments

- Only public cloud is in scope here.
- I'm gonna work on writing this recommendation. 🙂

@mkorbi I'd love your input on this issue description, do you feel this captures the fullness of what we talked about?

(cc @JacobValdemar)

**Comment by xamebax** [comment]
Just an update that I did start working on this and should hopefully have a draft by the end of the week.

**Comment by xamebax** [comment]
@mkorbi thanks for extra context. So there are two repair paths:
- the ones internal to Kubernetes:
	- can we make any gains by setting a specific `restartPolicy`?
	- liveness and readiness checks: we cat make sure the liveness checks we define for Pods are actually measuring what we think they are
	- something else?
- the ones where we need to have a good understanding that liveness/readiness checks are not enough and we should rather use external metrics that can alert us about broken workloads:
	- use request rate and latency metrics exposed by the ingress (for example nginx) together with resource usage metrics to hint at unhealthy ratios
	- other use cases:
		- running outdated or misconfigured software

I would argue choices around programming language / outdated software is outside of the scope of this project in its first run, since if I remember correctly we agreed to not cross the Pod barrier.

Does this make sense?

**Comment by xamebax** [comment]
I wrote a high-level introduction to this [in the working document](https://docs.google.com/document/d/12EAPH2vTM7tgqbQOv-9XizlMgQyIWp5LlBsHdry-Dxg/edit#heading=h.8yhbvswmo2mv). It's difficult for me to gauge if the level of detail is ok. The next step will be describing examples.

The challenge for me here is that it's quite difficult to be specific about carbon cost since workloads can be very different, so I am hoping to provide a few high-level examples.

This is very, very much a work in progress so all feedback is more than welcome, good or bad. 🙂

**Comment by leonardpahlke** [comment]
> [...] Does this make sense?

&

> [...] This is very, very much a work in progress so all feedback is more than welcome, good or bad. 🙂

cc @mkorbi @saiyam1814

**Comment by saiyam1814** [comment]
I will have a look

Founder, Kubesimplify
<https://saiyampathak.com/youtube>
<https://www.linkedin.com/in/saiyampathak/>
<https://twitter.com/saiyampathak>

**Comment by guidemetothemoon** [comment]
Updated the issue to be a blog post idea. We can look into transferring this as a content creation opportunity as part of the upcoming Community Group for example.
