### ISSUE TITLE
[PROJECT PROPOSAL] Sustainability in AI working group

### ISSUE THREAD

**Issue by catblade** [cncf/tag-env-sustainability#372]
### Description
AI is awesome, cool, amazing, BUT both the accelerators and the models are increasing in size, taking increasing amounts of power for each run.  SOMETIMES generative AI may be the answer to a task, but often it isn't.

This group would take a critical look at the use cases of AI and make recommendations on when, and when not, to use AI.  It may also measure the amount of power needed to run particular workloads to allow for easy determination of "is the power worth the expected output."  It may also make recommendations on tooling to reduce power use; for instance, reducing power in accelerators when not in use.
...

### Impact
This will help us be intentional about our AI use.  It will come up with tooling to help with measuring the actual power cost of a model.  It will help entities determine whether the cost of a particular workload is justified.

...

### Scope

**In Scope**: ...
Measurement tools for AI
Power reduction tools targeting accelerators
Recommendations for where AI is (currently) most useful vs. where it is not

**Out of Scope**: ...
Ethical recommendations

### Goals and Non Goals

**Goals:** ...
Explore the space and understand what the actual impact is of various workloads.

**Non Goals**:...
...

### Deliverables

- *Measurement tooling for a single AI workload*
- *Whitepaper/recommendations on when to use AI*

## TODO

- [] Project proposal / suggestion details added to this issue (all section above filled out)
- [ ] Project Leads found (one or more)
  - Project Leads: *link project leads here*
- [ ] Project proposal discussed in the TAG
  - Discussed in the TAG ENV meeting on `XX-XX`
- [ ] Project proposal accepted / rejected by the TAG leads
  - Proposal: `accepted` / `rejected`
- [ ] Project sponsor found (TAG Chair / TAG TL)
- [ ] Project tracking issue opened

cc @cncf/tag-env-sustainability

**Comment by raravena80** [comment]
I believe this could be an "Exploratory WG" or/and some of the deliverables could be released under the the existing [Cloud Native AI Working Group](https://tag-runtime.cncf.io/wgs/cnaiwg/charter/).

**Comment by leonardpahlke** [comment]
The TOC is discussion how to deal with topics like AI in Emerging Tech Groups / Exploratory Groups https://github.com/cncf/toc/issues/1279. AI plays a role in a lot of TAGs. We may want to hold on until there is some more clarity around these topics.

**Comment by raravena80** [comment]
FYI.  If you are interested you can also join the [exploratory groups Slack channel](https://cloud-native.slack.com/archives/C06V0C8E2J3).

**Comment by zanetworker** [comment]
@catblade brought this up in this week's call, Adam pointed me here. We would love to chat (AI WG).

**Comment by catblade** [comment]
@zanetworker  we should figure out what to do.  Looking at the exploratory groups may be a good place to start.

**Comment by SamYuan1990** [comment]
@rootfs , do you think how should we as kepler community to aline with this issue?

**Comment by leonardpahlke** [comment]
As mentioned, we already have a WG AI in TAG Runtime which this initiative could be part of. The introduction already mentions sustainability.

> It is a responsibility of the WG to identify cloud functionality, performance, security and **sustainability** gaps brought by AI workloads, and construct mechanisms to judiciously assess and guide on this progress, focusing on enabling cloud native projects and infrastructure that support AI workloads and services.

It would be awesome to see a WG TL with a focus on sustainability joining this WG.

**Comment by rootfs** [comment]
Thank you @catblade initiating this! AI has many impacts on sustainability, good and bad. It is critical to raise the awareness among our community. 

@raravena80 @zanetworker @leonardpahlke I would be pleased to be the bridge between AI WG and the TAG.

**Comment by rootfs** [comment]
@leonardpahlke @zanetworker @raravena80 @SamYuan1990:

We will present a version of Sustainable AI during the May 23rd Cloud Native AI WG meeting. Will update here after the meeting.

**Comment by catblade** [comment]
Issue here was opened in the tag runtimes group:  https://github.com/cncf/tag-runtime/issues/168#issue-2405770168

**Comment by catblade** [comment]
https://docs.google.com/document/d/154mBlTykdZPrR11TmvMjffv0-JZHDT82zN2blmg15Qk/edit

**Comment by catblade** [comment]
We've agreed to work with them, and have both @zanetworker and Vincent lead this.  I will be helping, and running the meetings, as needed.  Meeting times TBD.

**Comment by catblade** [comment]
Copied the doc over to the Env Sustainability drive: https://docs.google.com/document/d/1tNfR5yxnqfu9fduEb3108oBGXQ6spyRzA6cBTs9zbnQ/
