### ISSUE TITLE
[Action] Refining the Comms WG Goal and Roadmap

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#374]
#### Description
As discussed in the WG comms meeting, we want to further refine our goals and guide the group with a roadmap including where we want to be at the end of the year. 

### Outcome
This issue is to track to creation of the roadmap and figuring out what we want to achieve this year!

#### To-Do

- [x] Create Roadmap for the rest of the year
- [x] Review all issues
- [x] Consider projects under the WG
- [x] Consider the meeting format and if projects can be helped in there

#### Comments

We can also consider which projects/work can be "adopted" into the WG!

**Comment by vallss** [comment]
If this https://github.com/cncf/tag-env-sustainability/issues/361 gets accepted ( :crossed_fingers: ) I think we should definitely include it in the Roadmap for Comms.
