### ISSUE TITLE
[Tracking] How can you rightsize your Kubernetes workloads to optimize for environmental sustainability?

### ISSUE THREAD

**Issue by xamebax** [cncf/tag-env-sustainability#392]
### Description

There are multiple ways to scale your workloads inside Kubernetes.

There is a tension between scaling workloads horizontally and vertically. Being too conservative when scaling can lead to throttling and slow performance, with the risk of Pods being OOMKilled. Being too liberal, on the other hand, can lead to wasting resources by either running Pods that are too big, or running too many Pods.

What's the most environmentally efficient way to rightsize workloads running on Kubernetes? Can this be achieved with default Kubernetes behavior? Or is a custom autoscaler a necessary addition?

In [another issue](https://github.com/cncf/tag-env-sustainability/issues/364), contributors suggested looking into:
- [kube-green](https://kube-green.dev/), which can scale workloads down to 0 when there's no activity,
- [rekuberate-io/sleepcycles](https://github.com/rekuberate-io/sleepcycles), "*which is similar to kube-green but it covers a broader range of Kubernetes resources: **Deployments**, **CronJobs**, **StatefulSets** and **HorizontalPodAutoscalers**.*"
- In our brainstorming session, Max brought up [Keda](https://keda.sh), which allows for event-driven autoscaling.

Note: this could turn out to be a substantial piece of work to do on one's own.

### Outcome

A recommendation in our [working document](https://docs.google.com/document/d/12EAPH2vTM7tgqbQOv-9XizlMgQyIWp5LlBsHdry-Dxg/edit) that helps the reader make a choice on how they can rightsize their workloads with environmental sustainability in mind. Would using kube-green, sleepcycles, or Keda offer benefits here? How would that look? It would be great to say a few words about expected effort if changes to the cluster are required, and how big that effort could be (small, medium, large). Additionally, if possible, it would be great to add optional, extra reading material with added context if the reader's interested and has time.

### To-Do

- [ ] research if this could be a worthy recommendation,
- [ ] if yes, write a recommendation,
- [ ] share it for review, implement feedback.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Comments

@mkorbi, @JacobValdemar - I'd love your input on this task's wording and scoping. Do you think it's actionable enough, or too vague? Anything worth adding?

**Comment by graz-dev** [comment]
Hi, as my mext contribution to the project I can start working on this issue by the end of this week and the star of the next one. 
Is ok for you? 

@JacobValdemar @xamebax

**Comment by JacobValdemar** [comment]
@graz-dev Fine with me, but let's hear what @xamebax thinks. After all, she is the assignee on this issue ☺️

**Comment by xamebax** [comment]
@graz-dev this is great, go for it! I'm assigned as the creator, and I haven't done any work on this other than create the ticket. :D I'm sorry it took me so long to reply, I am hoping this wasn't demotivating. I can go ahead and assign you!

**Comment by graz-dev** [comment]
Yep @xamebax assign it to me!
I can work on it in the following days 😁

**Comment by xamebax** [comment]
@graz-dev done!

@akyriako do I remember correctly you were interested in participating in this one?

**Comment by akyriako** [comment]
Hi @xamebax , yes you do remember correct :+1: Please let me know where/how I could assist.

**Comment by guidemetothemoon** [comment]
**This should be combined for a single blog post together with** #394 
Updated the issue to be a blog post idea. We can look into transferring this as a content creation opportunity as part of the upcoming Community Group for example.
