### ISSUE TITLE
Add sustainability newsletter - It can fall under a project - Suggestion and also I can help

### ISSUE THREAD

**Issue by saiyam1814** [cncf/tag-env-sustainability#393]
### Description

A sustainability focus newsletter across the stack from hardware to software level innovation, developments and enhancements being done around the globe and organizations. 
I think we can start off monthly and then slowly take it to biweekly. 

### Impact

once place to read about the latest innovations, enhancements and developments wrt cloud native. 
All the stuff that the  sustainability WG is doing plus any global events that is happening and this will be recorded and can be tracked down to the first edition. 

### Scope

**In Scope**: ...
In scope is everything technical 
**Out of Scope**: ...
Political aspects are out of scope

### Goals and Non-Goals

**Goals**: ...
To provide uptodate information from the TAG and also outside world that is important to know
**Non Goals**: ...
No political agenda and the information has to be latest like within 30 days

### Deliverables

Plan 
- Identify the platform or website where we want to add the newsletter section , it can be same format is kubeweekly and same concept where we have 3-4 individuals who curate it and then one lead who does the final YEs/No with edits. 
- Publishing monthly once and then moving to biweekly
- Need a subscribe mechanism
- Publish mechanish in place or we can use existing thing like substack

### To-Do List

- [X] Project proposal / suggestion details added to this issue.
- [ ] Project Leads found (link project leads here).
- [ ] Project proposal discussed in the TAG.
- [ ] Project proposal accepted / rejected by the TAG leads.
- [ ] Project sponsor found (TAG Chair / TAG TL).
- [ ] Project tracking issue opened (see templates).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Comments

cc @leonardpahlke

**Comment by leonardpahlke** [comment]
I like this! We discussed a newsletter at some point before. Let’s discuss the wg comms meeting (may 2nd) if you are available @saiyam1814 (could you add this to the wg comms [agenda](https://docs.google.com/document/d/1TT-Yxgc2bSQHAutguMyGtyywZBl_x1_wWGQAM5SWeHk/edit#heading=h.myyff6uor7mu)? Thanks! 🙌) 

cc @claire-fletcher @patricia-cahill (wg comms chairs)
cc @guidemetothemoon (social media posts)
cc @savitharaghunathan (blogs)
