### ISSUE TITLE
[Action] Cluster autoscaling/rightsizing

### ISSUE THREAD

**Issue by JacobValdemar** [cncf/tag-env-sustainability#394]
### Description

The set of nodes available in a cluster should be reasonable when considering the resource demand from workloads. It should not be so low that it reduces the quality of the service provided by the cluster's workloads (whatever that is). Nor should it be so high that it wastes compute resources. In fact, the set of nodes in a cluster should enable the cluster to meet its demands with the smallest environmental footprint possible.

### Outcome

How do a Kubernetes Administrator fulfill the above description? The goal of this action item is to create a recommendation in our [working document](https://docs.google.com/document/d/12EAPH2vTM7tgqbQOv-9XizlMgQyIWp5LlBsHdry-Dxg/edit) that helps a Kubernetes Administrator fulfill the above description.

### To-Do

- [ ] Research methods for manual rightsizing of cluster
- [ ] Research tools available for automatic cluster rightsizing
- [ ] Write down recommendation
- [ ] Include relevant sources
- [ ] Include background information

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Comments

If you are interested in collaborating on this recommendation with me, then feel free to comment on this issue. Everyone are welcome!

cc @xamebax

**Comment by thpang** [comment]
Hi @JacobValdemar would like to participate. Thanks for starting this one. ;)

**Comment by JacobValdemar** [comment]
Awesome to hear @thpang! 🤩 Any specific part of the To-Do you would like to participate in? 🙌 Also, I would love to see you at our next project meeting on Monday, 6th May, 13:00 CEST (11:00 UTC) if you can. I realize that it's a bit little early in the morning in your time zone 😅

**Comment by thpang** [comment]
That's 7:00 AM here. I am usually up around 5:00-6:00 so should not be a problem. Dropping on my calendar now. I'll look over the to-do items as well. Thx again.

**Comment by guidemetothemoon** [comment]
Updated the issue to be a blog post idea. We can look into transferring this as a content creation opportunity as part of the upcoming Community Group for example.
