### ISSUE TITLE
[BLOG] Sustainability week 2024

### ISSUE THREAD

**Issue by savitharaghunathan** [cncf/tag-env-sustainability#399]
### GitHub tag of Blog Authors

@Nancy-Chauhan @akelity @JulieChenadec 

### GitHub tag of Blog Reviewers

@savitharaghunathan, @Nancy-Chauhan, @guidemetothemoon , @claire-fletcher 

### GitHub tag of TAG ENV Lead that sponsors the blog

TBD

### Abstract

Add a blog post on
* What is sustainability week
* How to participate
* Glimpse into last year's achievements
* Events planned for this year - 2024
* CTA - need for volunteers etc

Related to - https://github.com/cncf/tag-env-sustainability/issues/380 

### Scope

Introduction to what cloud native sustainability week is and create awareness about the same.
Audience: Any

### Goals and Non Goals

Goals:
* Provide info about sustainability week
* How to participate/volunteer

Non goals:
* This blog will not have details on how to run the events, or logistics. 

### Todo items starting the blog post process

- [ ] [Author] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
- [ ] [Author] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
- [ ] [TAG ENV Lead] One of the TAG ENV leads assigned themselves to wrangle the blog
- [ ] [TAG ENV Lead] Blog post outline and theme has been discussed
- [ ] [Author] Blog post written and ready for review

### Todo items reviewing the blog post

- [ ] [Author] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
- [ ] [Author] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
- [ ] [Author] Feedback and comments have been resolved.
- [ ] [Reviewers] reviewed blog post.
- [ ] [TAG ENV Lead] reviewed blog post.
- [ ] [TAG ENV Lead] ready to get published.
- [ ] [TAG ENV Lead] notified one of the ToC liaisons to sign off the blog post.
- [ ] [OPTIONAL TAG ENV ToC Liaison] reviewed blog post.

### Todo items reviewing the blog post

- [ ] [TAG ENV Lead] merged blog post.
- [ ] [OPTIONAL TAG ENV Lead] schedule the blog post on the CNCF blog next to the TAG ENV blog
- [ ] [Author] Wrote feedback about the blog post process as a comment under this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by savitharaghunathan** [comment]
@Nancy-Chauhan: would you like to take a lead on this blog I am happy to help in anyway I can.

**Comment by savitharaghunathan** [comment]
cc: @guidemetothemoon @patricia-cahill @claire-fletcher @leonardpahlke FYI. If I have missed any details, feel free to edit the issue. Thanks

**Comment by SamYuan1990** [comment]
Sustainability week 2024?

**Comment by savitharaghunathan** [comment]
@SamYuan1990 yes. Thanks for catching it. Updating the issue now

**Comment by sergioarmgpl** [comment]
I will love to help with @Dianmz

**Comment by vallss** [comment]
I would like to help with this! We can also talk about it during wg-comms meeting on Thursday.

**Comment by leonardpahlke** [comment]
Great idea @savitharaghunathan 🙌

**Comment by JulieChenadec** [comment]
happy to support too!

**Comment by guidemetothemoon** [comment]
Great initiative and thanks for driving it! I'm happy to support this blog from the TAG ENV lead team.

**Comment by akelity** [comment]
Hello everyone,
@Nancy-Chauhan and I are starting to work here: https://docs.google.com/document/d/19aHbVfRLlIXpk9FP3cNH55L80bVmhQHX8QQdZYfascY/edit
@savitharaghunathan, can you add it to the description of this issue to increase visibility?



I believe a good structure is the one proposed by @savitharaghunathan in the description of this issue. 
I would create a paragraph for each of these sections.

Any contribution is welcome. If you want to write a specific paragraph, please write it here and mark it on the Google Docs!

**Comment by Nancy-Chauhan** [comment]
Hey @savitharaghunathan We can look forward to publish the blog this week along with the video !

**Comment by claire-fletcher** [comment]
Is everything set up for publishing the video? If not I can lend a hand!

**Comment by Nancy-Chauhan** [comment]
Hey @savitharaghunathan Yes it is ready from our end.  Should we make PR to https://tag-env-sustainability.cncf.io/blog/ as next step ?

**Comment by savitharaghunathan** [comment]
> Hey @savitharaghunathan Yes it is ready from our end.  Should we make PR to https://tag-env-sustainability.cncf.io/blog/ as next step ? 

Yes please. cc: @claire-fletcher @guidemetothemoon please comment if there is a different process that needs to be followed.

**Comment by guidemetothemoon** [comment]
No, the process is pretty straightforward - once all comments are resolved and authors feel that the blog post is ready to be added, then it's just to go ahead and create a PR😊

**Comment by Nancy-Chauhan** [comment]
> Is everything set up for publishing the video? If not I can lend a hand!

Hey Yes @claire-fletcher everything is set for video as well, we can make it public as soon as we release the blog

**Comment by akelity** [comment]
I'm preparing the PR to add the article. I will update you here as soon as it is submitted.

**Comment by akelity** [comment]
The PR is here: https://github.com/cncf/tag-env-sustainability/pull/424 

it should be okay (but double-check to be sure), we were thinking of publishing on Thursday (the dates I have put are all May 30th).

**Comment by savitharaghunathan** [comment]
Merged PR - https://github.com/cncf/tag-env-sustainability/pull/424

closing this issue
