### ISSUE TITLE
[Tracking/Cloud Native Sustainability Week 2024] Enhancing Outreach and Engagement for Cloud Native Sustainability Week 2024

### ISSUE THREAD

**Issue by Nancy-Chauhan** [cncf/tag-env-sustainability#401]
### Description

As we prepare for Cloud Native Sustainability Week 2024, we recognize the importance of effective communication, collaboration with organizations, and reaching new regions for representation. Additionally, ensuring early awareness of the event is crucial for maximum participation and impact. This issue aims to tackle these challenges and devise strategies to achieve our goals.

Goals 

1. Increase awareness about Cloud Native Sustainability Week 2024 through social media communication and collaboration with relevant organizations.
2. Expand reach to new regions that were not represented in the previous year
3. Engage with Organizations in the cloud-native sustainability space 

### Outcome

By proactively addressing these challenges and implementing effective strategies, we aim to significantly enhance the outreach, engagement, and visibility of Cloud Native Sustainability Week 2024, thereby maximizing its impact and participation.

### To-Do

- [ ] Develop a social media communication plan highlighting key aspects and benefits of Sustainability Week.
- [ ] Create social media posts to create more reach. We need to get it reviewed by @guidemetothemoon @JulieChenadec @Nancy-Chauhan 
- [x] Create a video on sustainability @Nancy-Chauhan @JulieChenadec 
- [ ] Identify & reach out to organizations/communities for collaboration in advocating the event. @JulieChenadec 
- [ ] Research and identify regions that were not represented last year and reach out to local communities. ( refer to https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/) @Nancy-Chauhan 
- [ ] Call to Action in community organizers slack group. Spread the word about Sustainability Week
- [x] Blog post https://github.com/cncf/tag-env-sustainability/issues/399 
- [x] Create a list of ideas/resources to facilitate early awareness of Sustainability Week.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jes14** [comment]
Hi @Nancy-Chauhan I would like to help here

**Comment by JulieChenadec** [comment]
I will support!

**Comment by sunya-ch** [comment]
In Japan, we will have a meetup of GreenSoftwareFoundation group soon in June 24 6:30 PM JST.
Some organizers of this event are  also helping to organize the sustainability week this year.
It would be great if we can have some of the lead joining and giving a talk (it is a hybrid event).

https://www.meetup.com/gsf-tokyo/events/300942974/
https://connpass.com/event/318642/

**Comment by leonardpahlke** [comment]
> It would be great if we can have some of the lead joining and giving a talk (it is a hybrid event).

Happy to join :)

**Comment by saiyam1814** [comment]
Happy to join as well

**Comment by guidemetothemoon** [comment]
Closing this issue as Cloud Native Sustainability Week 2024 has finished.
