### ISSUE TITLE
[Action] Project Green Scraper - Integrate Green Scraper GitHub Actions workflow in the TAG ENV repo

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#403]
### Description

Events page that we want to populate data from the Green Scraper tool to will be located in the [TAG ENV website events folder](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/events) in this repository. We would need to integrate the Green Scraper GitHub Actions workflow located in [cncf-tags/tag-env-tooling](https://github.com/cncf-tags/tag-env-tooling/blob/main/.github/workflows/green-talks-scraper.yml) to being triggered on a schedule in the TAG ENV (this) repository.

### Outcome

Green Scraper GH Actions workflow is integrated to be triggered on a schedule in the TAG ENV (this) repository.

### To-Do

- [ ] Integrate the Green Scraper GitHub Actions workflow located in [cncf-tags/tag-env-tooling](https://github.com/cncf-tags/tag-env-tooling/blob/main/.github/workflows/green-talks-scraper.yml) to being triggered on a schedule in the TAG ENV (this) repository.
- [ ] Define a schedule that the tool will be triggered on. Should be possible to trigger manually, but also once in a few months maybe. TBD.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guidemetothemoon** [comment]
I think that we should be able to use it as a reusable workflow since both repositories are public: https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-to-reusable-workflows
Updating files in the TAG ENV repo should also be relatively easy with reusable workflows. 
From the GitHub docs:

> If you reuse a workflow from a different repository, any actions in the called workflow run as if they were part of the caller workflow. For example, if the called workflow uses actions/checkout, the action checks out the contents of the repository that hosts the caller workflow, not the called workflow.

Will do a proof of concept on this and confirm.

**Comment by guidemetothemoon** [comment]
Update. 

The workflow code is ready in a feature branch in `tag-env-tooling` repo: https://github.com/cncf-tags/tag-env-tooling/pull/7
Also, workflow code in the TAG ENV repo: https://github.com/cncf/tag-env-sustainability/tree/add-green-scraper-workflow

To test the workflow in the `tag-env-tooling` repo I requested a fine-grained token with necessary permissions that is pending approval from the `cncf-tags` organization admin: 
![image](https://github.com/user-attachments/assets/21fca3e0-1377-4e30-a2c8-3eefcacff506)

We need to create/re-use if already exists a GitHub workflow token for the `tag-env-sustainability` repo as well, but I'm not a member of CNCF organization so I can't request a fine-grained token for the `tag-env-sustainability` repo that they own. @leonardpahlke is this something you can help me with or tag someone from CNCF who can help?

Below are the permissions I've requested for the token for the `tag-env-tooling` repo:

![image](https://github.com/user-attachments/assets/3b257abb-0323-4d4a-aec7-601ddc736ed3)

**Comment by leonardpahlke** [comment]
@RobertKielty could you help us with the token?

> @leonardpahlke is this something you can help me with or tag someone from CNCF who can help?

> Below are the permissions I've requested for the token for the tag-env-tooling repo:

**Comment by RobertKielty** [comment]
I'll take a look.

**Comment by RobertKielty** [comment]
@guidemetothemoon @leonardpahlke 

Approved!
