### ISSUE TITLE
[Action] Project Green Scraper - Green Scraper tool should only add events that don't exist in the events page from before

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#404]
### Description

Right now the Green Scraper tool overwrites the target file with the data that it scrapes. This is not the most resource-efficient way, and the execution time will potentially be extended as the events page and the amount of events grow. The PR review would also be easier if only parts of the file are modified instead of the whole file.
We should look into possibility to adjust the Green Scraper tool implementation so that it only adds event entries to the page if those don't exist from before. 

### Outcome

The Green Scraper tool creates PRs with changes that only add entries for events that haven't been previously added to the events page.

### To-Do

- [ ] Analyse if we can implement adding non-existent entries only instead of full file overwrite.
- [ ] Update Green Scraper tool to only add entries for events that haven't been previously added to the events page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
