### ISSUE TITLE
[Action] Project Green Scraper - Testing

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#405]
### Description

Suggested by Nandish N, who was also interested in contributing to this item.

For the Green Scraper tool and its GitHub Actions workflow, we should look into if we need to implement some testing to ensure that it's working as expected and secure the implementation against any future faulty changes.
Is there a need to implement testing for the Green Scraper tool itself? Should we test if the result from the workflow is valid and populates valid changes for the event page. Can we test and validate that the resulting events page is valid and looks as expected?

This is something that we need to analyse and implement if applicable.

### Outcome

Implemented validations that are being triggered continuously as part of the Green Scraper tool development and as part of changes that are done by the tool's workflow to the events page.

### To-Do

- [ ] Decision on types of testing that is to be implemented in this project.
- [ ] Implementation of the respective tests.
- [ ] Documentation on what kind of testing is performed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nandishnagaraj** [comment]
I can pick this up

**Comment by nandishnagaraj** [comment]
@guidemetothemoon please assign this to me.

**Comment by guidemetothemoon** [comment]
Thank you, @nandishnagaraj !

**Comment by nandishnagaraj** [comment]
Implementing continuous testing as part of the tool's development process and workflow changes will help in identifying and addressing any issues. initiating with Functional Testing seems appropriate for the initial phase. We should also consider the necessity of other types of testing as the project progresses. To proceed, let's prioritize deciding on the testing environment. @guidemetothemoon

**Comment by guidemetothemoon** [comment]
@nandishnagaraj we discussed this a little bit more in the last meeting and from what we could see, right now the scope of the Green Scraper project is quite small to have a need for extensive testing. In a way, the GitHub workflow itself and the PR with changes that it generates with Green Scraper tool will show us if there are any issues with resulting data. Maybe if we extend the tool a lot long-term or even migrate it from a Bash script to a bigger project in Go or similar programming language it would make sense to create some unit tests or similar. But for now, with a single, relatively small Bash script it would probably be too much overhead to do.

But if you had any specific thoughts around what kind of tests the project can benefit from, please let us know!

@Al-HusseinHameedJasim FYI.
