### ISSUE TITLE
[Action] Project Green Scraper - Events page design on the TAG ENV website

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#406]
### Description

We will need to define the outline of the events page on the TAG ENV website that the Green Scraper tool will add events data to. Currently the tool produces a plain list of talks in a markdown file - see [example](https://github.com/Al-HusseinHameedJasim/green-talks-scraper/blob/main/talks.md).

We need to define if it's enough or if we need a better structure for the page. Also, we need to define what information each session entry and each even section should contain. Events must contain information about event type, speakers, session titles and descriptions and direct link to the event. Any additional information will need to be considered.

Finally, we would need to update the Green Scraper tool implementation accordingly to ensure that pull requests with new changes added by the tool comply with the established events page outline.

### Outcome

A user-friendly outline of the events page on the TAG ENV website where it's easy and understandable for anyone to navigate to and get an overview of the past and upcoming events and navigate between events on the page.

### To-Do

- [ ] Outline how the events page will look like.
- [ ] Outline what kind of information each event section and each session entry will include.
- [ ] Modify the Green Scraper tool to add changes according to the events page outline.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guidemetothemoon** [comment]
@vallss this one was of interest to you, right?

**Comment by vallss** [comment]
@guidemetothemoon yes, I can help with this! ☺️

**Comment by guidemetothemoon** [comment]
Thank you, @vallss ! I will assign you to this task, but we will support you of course😊

**Comment by vallss** [comment]
During today's meeting after some brainstorming, we decided to try the following approach: creating a new markdown file that will be updated by the Greenscraper tool his file will be a markdown file similar to [this](https://github.com/Al-HusseinHameedJasim/green-talks-scraper/blob/main/talks.md) one and can be reached by clicking on a link positioned at the top of the landing page Events.

Since it will be a markdown file we have some limitations on the layout but we aim to give it a structure that will make it easier for users to find what they are looking for in one of the following ways:
- each event schedule (for reference the section starting from "_Conference schedule link..."_ + list of talks) could be a collapsible element
- a table of content at the start of the output file

+1 for adding the following information: event name, link of each session and recording (if available)


cc @guidemetothemoon

**Comment by guidemetothemoon** [comment]
Thank you for summing up our preliminary plan, @vallss !🤗
