### ISSUE TITLE
[Action] Project Green Scraper - Fine-tune data that's being included to the event list

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#416]
### Description

Right now the [event list](https://github.com/Al-HusseinHameedJasim/green-talks-scraper/blob/main/talks.md) that's being generated by Green Scraper includes conference agenda link, session title and session speakers. To make the content more useful and helpful for the users we need to look into what additional information should be included by the tool and modify implementation accordingly.

After initial discussions we have identified that following information also needs to be added to the event list:

- Conference name
- Session description
- Direct link to the session page on the agenda website
- Link to the session recording, if applicable

### Outcome

Green Scraper tools generates the event list that contains the most relevant and helpful information, as per the community feedback.

### To-Do

- [ ] Identify what information is lacking from the current content that's generated by the tool
- [ ] Update Green Scraper to include data that was identified in the previous point

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by claire-fletcher** [comment]
Something else to consider here is picking up talks by people that work for energy companies. Sometimes their company names will include the word "energy" making the green scraper pick their talk up. However, sometimes their talks _are_ relating to sustainability!
