### ISSUE TITLE
[Action] Project Green Scraper - Markdown formatting for the event list generated by the tool

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#417]
### Description

Currently Green Scraper tool generates a very simple Markdown file, without any subheaders or any other type of formatting - see [example](https://github.com/Al-HusseinHameedJasim/green-talks-scraper/blob/main/talks.md)

Since we want the events page to be more user-friendly, helpful, easy to navigate and view, we will need to have some kind of formatting in the respective Markdown file to support things like table of contents for example.

We need to investigate how we can do it and implement changes accordingly. Some possibilities may be to implement this logic as code in the Green Scraper tool itself so that for every entry it scrapes it should add needed Markdown file formatting to the file where the content is being saved.
Or we could have a template file with the necessary Markdown formatting already implement, with placeholders for the type of content to be added, and then use a GitHub Action to replace placeholders with the respective content. For example, something like https://github.com/marketplace/actions/readme-replacer-readme-workflows or https://blog.jakelee.co.uk/fetching-youtube-metadata-in-github-actions-and-persisting

Based on the chosen approach we will need to either modify the implementation in the Green Scraper tool or GitHub Actions workflow.

### Outcome

Content that's generated by the Green Scraper tool is formatted and populated according to the Markdown outline that will result into what we want the events page to look like on the TAG ENV's website.

### To-Do

- [ ] Look into the options for handling Markdown formatting according to the outline for the events page on the TAG ENV website
- [ ] Based on the strategy identified in the previous point, implement the changes accordingly either in the Green Scraper tool or the GitHub Actions workflow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
