### ISSUE TITLE
[Tracking] Refusing workloads from running on Kubernetes

### ISSUE THREAD

**Issue by xamebax** [cncf/tag-env-sustainability#420]
### Description

Running workloads on Kubernetes can give developers the freedom and velocity they need, but that freedom can also give operators a headache.

There are mechanisms like admission webhooks and operators that can enforce human-defined criteria and prevent certain workloads from being deployed to Kubernetes at all. Kyverno is an example of such an operator, but other tools also exist.

This is a vague question that might be worth exploring first before digging in to write a recommendation: 

- what kind of criteria for refusing deploying Pods on Kubernetes can we potentially adopt to increase environmental sustainability? These could be criteria around for example making sure resource requests and/or limits are set, or making sure an HPA object is deployed also, or something completely different.
- what kind of tools can be used to aid refusal?

### Outcome

A preliminary list of ideas that can be made concrete further, outlined in the [working document](https://docs.google.com/document/d/12EAPH2vTM7tgqbQOv-9XizlMgQyIWp5LlBsHdry-Dxg/edit#heading=h.sqr0dt2i30gd).

### To-Do

- [ ] dig into Kubernetes to find out which configuration of Deployments, StatefulSets, HPAs, etc. is often suboptimally set and needlessly increases a cluster's carbon footprint
- [ ] research operators and other mechanisms that can refuse objects being deployed to Kubernetes
- [ ] submit the outline for feedback

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guidemetothemoon** [comment]
Updated the issue to be a blog post idea. We can look into transferring this as a content creation opportunity as part of the upcoming Community Group for example.
