### ISSUE TITLE
[<Tracking>/<Action>] Update Website for CNCF Cloud Native Sustainability Week 2024

### ISSUE THREAD

**Issue by Nancy-Chauhan** [cncf/tag-env-sustainability#423]
### Description

We need to update the website for this year's event https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/ 

### Outcome

We have this year's edition live 

### To-Do

- [x] [Author] Raise the PR & create changes 
- [x] [TAG ENV Chair] Review & Feedback from the team 
- [x] [TAG ENV] Merge the changes 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sunya-ch** [comment]
[@naonishijima](https://github.com/naonishijima) is interested to help for Japanese version.

**Comment by naonishijima** [comment]
@sunya-ch  Thanks! I am interested in contributing to this.
