### ISSUE TITLE
[Action] Onboard Sergio and Diana as Website co-leads WG Comms

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#426]
### Description

@sergioarmgpl and @Dianmz have volunteered as our Website Leads for the WG Comms! There will be a few things they need adding to, updating information to list them as leads, and any information/logins they may need.

As we develop this role in the role review we can also create handbooks with them.

### Outcome

New WG Comms Website leads added to the relevant places and have the tools to get going.

### To-Do

- [x] Add to the wg notes
- [x] Add to the website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sergioarmgpl** [comment]
Nice to see this :) @Dianmz @guidemetothemoon @leonardpahlke

**Comment by leonardpahlke** [comment]
@sergioarmgpl & @Dianmz would be good to get your input here https://github.com/orgs/cncf/projects/10/views/13?pane=issue&itemId=59010094 WG Comms is working on defining the lead roles within comms

**Comment by guidemetothemoon** [comment]
@leonardpahlke @claire-fletcher I guess this item can be closed? With regards to upcoming TAG restructuring this may not be applicable anymore.
Ref. #589
