### ISSUE TITLE
[Action] Creation of WEBSITE_DEVELOPMENT.md

### ISSUE THREAD

**Issue by Dianmz** [cncf/tag-env-sustainability#430]
### Description

By creating the file WEBSITE_DEVELOPMENT.md we want to achieve a documentation guide for the usage of the autodetection of pending translations in the different supported languages.

### Outcome

We will create a new documentation file named: WEBSITE_DEVELOPMENT.md in which we can have a development guide for the website to describe the translations section.

### To-Do

- [ ] Create the file 
- [ ] Add the essential aspects for the translations section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sergioarmgpl** [comment]
@claire-fletcher I think that you can assign @Dianmz

**Comment by leonardpahlke** [comment]
@Nancy-Chauhan @claire-fletcher added this issue to needs triage

**Comment by guidemetothemoon** [comment]
Closing this task as it will not be applicable anymore due to upcoming TAG restructuring, ref. #589 
See last comment in #429 for more details.
