### ISSUE TITLE
[BLOG] Idle Power Matters: Kepler Metrics for Public Cloud Energy Efficiency

### ISSUE THREAD

**Issue by sunya-ch** [cncf/tag-env-sustainability#434]
### GitHub tag of Blog Authors

@sunya-ch, @marceloamaral, @rootfs

### GitHub tag of Blog Reviewers

updated once people start reviewing the blog

### GitHub tag of TAG ENV Lead that sponsors the blog

updated once a TAG ENV lead assigned themselve

### Abstract

This blog post aims to highlight the impact of idle power and the need of its transparency in software energy attribution and accounting, particularly in multi-tenant environments such as public cloud.

### Scope

Focus on the need of idle power transparency
Audience: Any who interested in energy metrics

### Goals and Non Goals

Goal
- understand the importance of idle power transparency in energy measurement
- understand the challenge of idle power attribution
Non goals
- conclusion of idle power attribution solution

### Todo items starting the blog post process

- [X] [Author] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
- [X] [Author] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
- [x] [TAG ENV Lead] One of the TAG ENV leads assigned themselves to wrangle the blog
- [ ] [TAG ENV Lead] Blog post outline and theme has been discussed
- [X] [Author] Blog post written and ready for review

### Todo items reviewing the blog post

- [x] [Author] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
- [x] [Author] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
- [x] [Author] Feedback and comments have been resolved.
- [x] [Reviewers] reviewed blog post.
- [x] [TAG ENV Lead] reviewed blog post.
- [x] [TAG ENV Lead] ready to get published.
- [ ] [TAG ENV Lead] notified one of the ToC liaisons to sign off the blog post.
- [ ] [OPTIONAL TAG ENV ToC Liaison] reviewed blog post.

### Todo items reviewing the blog post

- [x] [TAG ENV Lead] merged blog post.
- [ ] [OPTIONAL TAG ENV Lead] schedule the blog post on the CNCF blog next to the TAG ENV blog
- [ ] [Author] Wrote feedback about the blog post process as a comment under this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by savitharaghunathan** [comment]
PR #435 merged!
