### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Tokyo

### ISSUE THREAD

**Issue by sunya-ch** [cncf/tag-env-sustainability#459]
### Description

* **Location/Region:** Tokyo, Japan
* **Hosting Local Community:** [Cloud Native Community Japan (CNCJ)](https://community.cncf.io/cloud-native-community-japan/)
* **Organizers:** @sunya-ch @marceloamaral @tatsuhirochiba @rinana @trent-s @YaSuenag @naonishijima @tiwatsuka @nttDamien @bahung @inductor 
* **Sponsors:** NTT DATA, Hitachi, the Linux Foundation
* **Date:** 4th October 2024
* **Event link:** [community.cncf.io/e/m4m4je/](https://t.co/lgvcWZUzEZ)
* **Call For Speaker:** https://sessionize.com/cncj-sustainability-week-japan/?e=3c84e9
* **Social networks**:
   *  Twitter: https://x.com/CloudNativeComm/status/1810953041916612826

### Details

To connect people who work in cloud space and care about the environmental sustainability, make an awareness, and have a discussion about how can we realize the green cloud computing together and so on. 

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [X] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [x] Announce the event.
- [X] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Thank you @sunya-ch for creating this 🚀

**Comment by Nancy-Chauhan** [comment]
Hello @sunya-ch 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything.

**Comment by sunya-ch** [comment]
## To-Do (During Execution)
What specific actions to do during event execution?


- [ ] Use the [Artworks](https://www.figma.com/design/gydAB5esFpNxO3smhZTCkl/Sustainability-Week-Layouts---Shared?node-id=8-90&node-type=canvas) and [Presentation Template](https://docs.google.com/presentation/d/15Ywyw2YjNyckXs7lEWySrjC4fh7pLglUkDZOipLDQB4/edit#slide=id.g302f22217e4_2_173). You can use some slides in the template at the begining of the event for introducing the cloud native sustainability week event.

- [ ] Distribute the feedback survey to attendees. Use the [Survey Blueprint](https://docs.google.com/forms/d/e/1FAIpQLSeIsz3T5XHhQf9ZMhfmHAchvGX5_enteQ5j9ZmIsMoFjshfGg/viewform).

Record the event with photos or video recordings.

## To-Do (After Event)
What specific actions to do after the event?


- [ ] Share the event records, summary via blog post, recordings to `#tag-env-cloud-native-sustainability-week` slack channel.

- [ ] Share the survey summary from attendees.

- [ ] Leave feedbacks/comments (KEEP DOING, MORE OF, START DOING, STOP DOING, LESS OF, IDEAS) about organzing the event in this issue.

- [ ] Submit the information of organizers, speakers to issue the credly badges. [to put the submission form here]

**Comment by sunya-ch** [comment]
Pictures uploaded on event page: https://community.cncf.io/events/details/cncf-cloud-native-community-japan-presents-cncf-cloud-native-sustainability-week-2024-local-meetup-tokyo/
Blog post: https://github.com/cncf/tag-env-sustainability/issues/547
Youtube Video Recording: https://www.youtube.com/playlist?list=PLP6cDU-AhHU6CI6VpFQ11XigCt3kqFDLT

**Comment by sunya-ch** [comment]
## Feedback from Organizers

KEEP DOING
- cooperate with TAG ENV
MORE OF
- promoting together in large event
- promoting CFS/demos/LTs
- checking live video (event issue: cannot seen screen, video lag)
START DOING
- fix format of presentation for smooth flow (all PDF?)
STOP DOING
- expecting prompt engagement from participants
LESS OF
- food overestimation
IDEAS
- add pre-event form to get real first name, last name, and company name
- co-located with OSS japan or GSF event next year

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by sunya-ch** [comment]
> Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

Thank you @vallss. Done :)

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
