### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 China

### ISSUE THREAD

**Issue by SamYuan1990** [cncf/tag-env-sustainability#466]
### Description

* **Location/Region:** tbd
* **Organizers:** @SamYuan1990 
* **Sponsors:** tbd
* **Date:** tbd
* **Event link:** tbd

### Details

I had a discussion with LF member for host/organize sustainable week meet up in China this week.
As a retrospect for previously year's event, for this year.

Here are the things we want to improve this year as local community build up:
We want to engage local community members to help us host and organize this event.
So that we can extend our scopes, to have more topics and more session.
For example, any topic from CNCF end user?
and encourage people contribute back to our community with any kind of Sustainability Initiatives, as our landspace page mentioned.

> ## Sustainability Initiatives
>
>There are a number of sustainability initiatives ongoing, if we've missed one please contribute to this list by filing a pull request!

Meanwhile, consider we have half day(4 hours) session last year. In this year, if we can find sponsors and engaged with local community.

Is it possible that we make it as a KCD with sustainble topic/specific with sustainble topic this year?
To be optimistic, considering that 1st week of Oct is local holiday, by default we want to host this session after 1st week of Oct, so that we can pick up some best session from global sessions and play the recordings?

to call for sponsor and engage with local community memebers, we need to?
as in China we have local social media networks, and to engage with people more widely. Such as CNCF member in other SIGs, potential sponsors, potential speackers etc.
We need to create a blog on sustainable TAG's web site, and transition in to Chinese, publish the transited version on the local social media.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [ ] Find a sponsor for the event.
- [ ] Find a location for the event.
- [ ] Set a date for the event.
- [ ] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamYuan1990** [comment]
link to https://github.com/cncf/tag-env-sustainability/pull/427

**Comment by SamYuan1990** [comment]
or maybe this link https://tag-env-sustainability.cncf.io/blog/2024-cncf-cloud-native-sustainability-week-2024-is-underway-and-why-you-should-care/

**Comment by Nancy-Chauhan** [comment]
Hello @SamYuan1990 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by JulieChenadec** [comment]
Hi @SamYuan1990 ! Do you need help in finalizing your event? We are here to support if necessary, please let us know!

**Comment by JulieChenadec** [comment]
Hi, @SamYuan1990, I'm sorry to hear that; take all the time you need. Good luck!

**Comment by vallss** [comment]
Closing this as no meetup took place, unfortunately.
