### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Barcelona

### ISSUE THREAD

**Issue by immavalls** [cncf/tag-env-sustainability#468]
### Description

* **Location/Region:** Europe, Barcelona
* **Organizers:** @immavalls 
* **Sponsors:** Hosted at the Microsoft offices
* **Date:** October 9th
* **Event link:** tbd

### Details

A regular meetup (3h) under https://meetu.ps/c/2NtSS/sJyPP/a. 

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by immavalls** [comment]
Event published: https://www.meetup.com/cloud-native-bcn/events/303352183 and https://community.cncf.io/events/details/cncf-cloud-native-barcelona-presents-cloud-native-sustainability-week-2024-barcelona-edition/

**Comment by Nancy-Chauhan** [comment]
Hey @immavalls 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything.

**Comment by immavalls** [comment]
Thanks, we seem to be on our way 🤞 I'll do the PR this week to add to the website. And I will also share with our social networks and and if you can help amplifying on slack. Niki and I should have some stickers for the event as well, so hopefully all covered.

**Comment by immavalls** [comment]
@Nancy-Chauhan and @guidemetothemoon, created https://github.com/cncf/tag-env-sustainability/pull/524, let me know if it's ok to merge or if it needs any changes. Thanks!

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
