### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Munich

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#472]
### Description

* **Location/Region:** Munich, Germany
* **Organizers:** Kubernetes & Cloud Native Meetup Munich & Green Software Foundation Munich
* **Sponsors:** Liquid Reply
* **Date:** 16th October 2024
* **Event link:** tbd

### Details

We will host a meetup like last year, but maybe we will change the format to be more interactive.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [ ] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [ ] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [ ] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonioDiTuri** [comment]
Interested in helping out here!

**Comment by AntonioDiTuri** [comment]
hi @Nancy-Chauhan I am checking with Max the details about the date, I will come back to you asap :)

**Comment by AntonioDiTuri** [comment]
We have a date and a place, details will follow about the sponsor and the link for the event :)

**Comment by JulieChenadec** [comment]
Hi @AntonioDiTuri That's amazing !! Congratulations on the last minute actions :) Any support needed?

**Comment by vallss** [comment]
Hi @AntonioDiTuri! Do you have any updates on the event? Can you please open a PR as suggested in point three of the To Do list?

> Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example https://github.com/cncf/tag-env-sustainability/pull/170. 

This way we can track and show the event along with all the others on the Website.

**Comment by vallss** [comment]
Closing this as no meetup took place, unfortunately.
