### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 London

### ISSUE THREAD

**Issue by rohitg00** [cncf/tag-env-sustainability#473]
### Description

* **Location/Region:** London
* **Organizers:** Rohit Ghumare (@rohitg00)
* **Sponsors:** Isovalent
* **Date:** 24th October
* **Event link:** https://community.cncf.io/events/details/cncf-cloud-native-westminster-presents-cncf-sustainability-week-2024-london-meetup/

@Audra Montenegro

### Details

We plan to launch Cloud Native Sustainability Week in London in 2024, as previously discussed in the TAG on the Slack community.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anewmandev** [comment]
hi @rohitg00 

I just created #497 for hosting event in Brighton, UK. We have a venue and date - no speaker. @JulieChenadec suggested we could chat about combining efforts. Am happy to discuss. Equally if you already organised and set then we can host separately as South East siblings :) All the best.

**Comment by rohitg00** [comment]
Hey @anewmandev, This seems like a good idea. If possible, we're planning to host it in London close to the KCD UK event. Any suggestions or involvement are appreciated.

**Comment by anewmandev** [comment]
Hi @rohitg00. 
We already have venue and date sorted in Brighton as we host monthly community events for https://greensoftwarebrighton.co.uk. We could host the same event but in two different locations on two different evenings. Which would be interesting but would involve a lot more coordination. My suggestion is that, on this occasion we opt to host separete events, but I would be up for chatting about collaborating on a future event - feel free to ping me on adam@rootandbranch.io for a chat. 
Or if you have other ideas I am all ears. 
All the best
Adam

**Comment by Nancy-Chauhan** [comment]
Hello @rohitg00 @anewmandev 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by claire-fletcher** [comment]
Hey @Nancy-Chauhan, we have a meeting tomorrow (friday) to discuss and make some plans. I'll make sure we update the relevant details as needed!

**Comment by seekasra** [comment]
I'm an Academic in London South Bank University, please let me know if I can be of any help?

**Comment by anewmandev** [comment]
Hi @Nancy-Chauhan I have updated separately for Brighton event in #497. 
I need to jump on one of the calls soon, how do I find when the next meeting will be, I saw on slack possibly next Monday 23rd? 
Thanks

> Hello [@rohitg00](https://github.com/rohitg00) [@anewmandev](https://github.com/anewmandev)
> 
> I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by anewmandev** [comment]
> I'm an Academic in London South Bank University, please let me know if I can be of any help?

Hi @seekasra. 

I imagine you were asking about the London event so possibly @rohitg00 maybe can respond re: that? 

In other news: perhaps you and I will cross paths through LSBU at some point as I may be around in some very small capacity this year through Ian Mackie who has just joined from Sussex, which is where we are based. Adam

**Comment by claire-fletcher** [comment]
We have confirmed a location and date (October 24th) in London

**Comment by rohitg00** [comment]
Agenda is up: https://lu.ma/1yx3wzsk

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by rohitg00** [comment]
Any update on our blog? https://github.com/cncf/tag-env-sustainability/issues/567
