### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Sao Paulo - Brazil

### ISSUE THREAD

**Issue by krol3** [cncf/tag-env-sustainability#478]
### Description

* **Location/Region:** tbd
* **Organizers:** @krol3, @tiagoReichert
* **Sponsors:** tbd
* **Date:** tbd October
* **Event link:** tbd

### Details

We plan to launch Cloud Native Sustainability Week in Sao Paulo in 2024, as previously discussed in the TAG on the Slack community.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).  - https://github.com/cncf/tag-env-sustainability/pull/505/
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [ ] Find a sponsor for the event.
- [ ] Find a location for the event.
- [ ] Set a date for the event.
- [ ] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Hello @krol3 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by tiagoReichert** [comment]
Hey @Nancy-Chauhan, we secured the date and place for the event. 
I will create a PR to update the page in the following days.

**Comment by JulieChenadec** [comment]
Hi @tiagoReichert Any update on your event? if you can update this task, it will help us with planning content :) Thanks!

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
