### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Milan

### ISSUE THREAD

**Issue by vallss** [cncf/tag-env-sustainability#479]
### Description

* **Location/Region:** Milan (Retex) + online event
* **Organizers:** @vallss @akelity @Ludovik95 
* **Sponsors:** Improove, Mia Platform, Green Software Foundation Meetup Milano, Kubernetes & Cloud-Native Milano, Retex, JUG Milano, Digital Platform Builders
* **Date:** tbc - 30th September and 7th October (online)
* **Event link:** [In person](https://www.meetup.com/digital-platform-builders/events/303350215) / [Virtual](https://www.meetup.com/digital-platform-builders/events/303350378)

### Details

Similar to last year we will have a meetup in Milan and additionally an online event. Cfp is open until August 23rd and we plan to select some talks for both events. 

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [x] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

To-Do (During Execution)

- [x] Use the [Artworks](https://www.figma.com/design/gydAB5esFpNxO3smhZTCkl/Sustainability-Week-Layouts---Shared?node-id=8-90&node-type=canvas) and [Presentation Template](https://docs.google.com/presentation/d/15Ywyw2YjNyckXs7lEWySrjC4fh7pLglUkDZOipLDQB4/edit#slide=id.g302f22217e4_2_173). - [ ] You can use some slides in the template at the begining of the event for introducing the cloud native sustainability week event.
 - [x]  Distribute the feedback survey to attendees. Use the [Survey Blueprint](https://docs.google.com/forms/d/e/1FAIpQLSeIsz3T5XHhQf9ZMhfmHAchvGX5_enteQ5j9ZmIsMoFjshfGg/viewform).
 - [x]  Record the event with photos or video recordings.

To-Do (After Event)
 - [ ]  Share the event records, summary via blog post, recordings to #tag-env-cloud-native-sustainability-week slack channel.
 - [x] Share the survey summary from attendees.
 - [ ]  Leave feedbacks/comments (KEEP DOING, MORE OF, START DOING, STOP DOING, LESS OF, IDEAS) about organzing the event in this issue.
 - [x]  Submit the information of organizers, speakers to issue the credly badges. [to put the submission form here]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Hello @vallss 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by vallss** [comment]
Hi @Nancy-Chauhan!
We actually forgot to update the to-do section but things are going pretty good.

As stated above in the issue description, we will have two events: one in-person and one online. For the in-person event we had to find another location from the first we chose and we are waiting for a confirmation.

We closed the CfP and we are arranging the agenda for both events. 

Yesterday we created the two Meetup events:
- in-person https://www.meetup.com/digital-platform-builders/events/303350215
- online https://www.meetup.com/digital-platform-builders/events/303350378

We can add these links in the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/) with a PR in the next few days.  

Even though the location is not confirmed yet, we know that the in-person event will take place in Milan so I think we can already promote the event. 

If I'm missing something, please add anything here
cc @akelity @Ludovik95

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
