### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week <Year> <Meetup Location>

### ISSUE THREAD

**Issue by sergioarmgpl** [cncf/tag-env-sustainability#480]
### Description

* **Location/Region: Guatemala** tbd
* **Organizers: @sergioarmgpl @Dianmz ** 
* **Sponsors:** tbd
* **Date: October** tbd
* **Event link:** tbd

### Details

Basic topics around tag env sustainability

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [ ] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [ ] Find a sponsor for the event.
- [ ] Find a location for the event.
- [ ] Set a date for the event.
- [ ] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Comments

In progress

**Comment by Nancy-Chauhan** [comment]
Hello @sergioarmgpl 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by sergioarmgpl** [comment]
@Dianmz lets work on this today

**Comment by sergioarmgpl** [comment]
This is the PR for the website in the env sustainability week https://github.com/cncf/tag-env-sustainability/pull/517 cc: @JulieChenadec

**Comment by JulieChenadec** [comment]
Hi @sergioarmgpl If you can update the to-do of this task, that would be fantastic :) Thank youu

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
