### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Aarhus

### ISSUE THREAD

**Issue by kaspernissen** [cncf/tag-env-sustainability#483]
### Description

* **Location/Region:** Aarhus, Denmark
* **Organizers:** Cloud Native Aarhus meet-up group (primarily @Steiniche and @kaspernissen) 
* **Sponsors:** Hostsponsor Knowit
* **Date:** October 7th 2024
* **Event link:** tbd

### Details

Create more awareness around Environmental Sustainability. 

Currently we are looking into a meet-up with 2-3 talks by knowledgable speakers within Environmental Sustainability

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [x] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Hello @kaspernissen 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything.

**Comment by kaspernissen** [comment]
Hi @Nancy-Chauhan, 

I think we are good! The event has been published - and we have 15 signups atm. 
You are of course welcome to help amplify our social media posts. 🙏

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
