### ISSUE TITLE
[Action] KubeCon/CloudNativeCon EU 2023 TAG Talk

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#49]
#### Todos

- [x] Brainstorm session (outline topics and theme of the talk)
- [x] Describe session (write proposal)
- [x] Submit session (send proposal to CNCF)
- [x] Conduct session

#### References

* [KubeCon CloudNativeCon EU Website](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)

ref: tracking issue https://github.com/cncf/tag-env-sustainability/issues/43

**Comment by agardnerIT** [comment]
1. We're all confronted with an energy crisis. Highlighted by the war in Ukraine but in reality we've been living beyond our means for much longer.
2. We are using the cloud incorrectly. We have completely wrong-sized the cloud for years. Too often we "leave it running", "scale it up but not down" etc. Cloud providers benefit from this ($) but every running pod ultimately costs money and consumes real world resources.
3. Energy and water scarcity is and will continue to have real-world effects **today** that means companies will struggle to find, hire and maintain the people talent they need, in the places they need it.

- [France's "energy sobriety" initiative](https://www.nytimes.com/2022/10/06/business/france-energy-crisis-europe.html)
- [Industrial plants closing that may never re-open](https://www.reuters.com/business/energy/energy-crisis-chips-away-europes-industrial-might-2022-11-02/)

**Comment by berryq460** [comment]
As mentioned today in the meeting Feb.1, I propose we leverage the audience at Kubecon to build relationships with future potential members while accomplishing our mission to educate the open source community. We can accomplish this by:

-  Hosting at least 2 sustainability meetups at different times led by our members to discuss their interests and/or pain points around sustainability within their org today ( I can lead 1)
- Formalizing a new survey to get users feedback - can include a QR code at end of presentation for live surveying
-  Educating new members about the mission of this group, broader sustainability principles and evangelizing our group- we can all wear our logo on t shirts so we increase brand awareness and stir curiosity
- Propose we have formal website with a blog by Kubecon so we can point interested parties to at our event
