### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Brighton, UK

### ISSUE THREAD

**Issue by anewmandev** [cncf/tag-env-sustainability#497]
### Description

* **Location/Region:** Runway East, Brighton [York And Elder Works, 50 New England St, BN1 4AW]
* **Organizers:** adam@rootandbranch.io
* **Sponsors:** Root & Branch Digital Ltd
* **Date:** Weds 16th October
* **Event link:** https://www.meetup.com/gsf-brighton/events/303193268/

### Details

We have an existing community in Brighton (UK) where we host monthly events around digitital sustainability. 
I reached out to @JulieChenadec recently to make our October event part of the CNCF sustainability week. 
I would really love to host a speaker from the CNCF community so I am hoping we can make that happen.  
Update: we have a speaker / Q&A confirmed with Nour Rteil and Astrid Wynne.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [X] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
