### ISSUE TITLE
[Tracking] Environmental Sustainability Maturity Model

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#50]
#### Description

The idea is to build a v0.1 maturity model for environmental sustainability. This will be a living artifact and gets frequent updates, I guess. However, we have already received questions in this direction in terms of if there is any guidance. 

As an interesting example, there is the [Cartografos](https://github.com/cncf/cartografos) for the cloud native majority model.
And this nice flyer from KubeCon:

<img width="1047" alt="Bildschirm­foto 2022-11-16 um 16 59 40" src="https://user-images.githubusercontent.com/16919345/202230593-888a80da-b4b7-4456-ac80-f36b99280805.png">
<img width="1047" alt="Bildschirm­foto 2022-11-16 um 16 59 34" src="https://user-images.githubusercontent.com/16919345/202230600-692095e7-c58f-4abb-9332-c6c4fce459c1.png">

Initial proposal: https://github.com/cncf/tag-env-sustainability/discussions/38

### Milestones

1. Gather a team
2. Evaluate current possibilities and slice them into dimensions
3. Draft Model
4. Draft Flyer for KubeCon

### Input

- Cartografos format is IMO a good direction to define the shape and way it looks like
- The Landscape Document
- Other organization's current status

### Outcome

- A Sustainability Maturity Model v0.1
- A potential design of a flyer for KubeCon

#### Todos

- [ ] Call for action/contribution via Slack/Mail
- [ ] Setup a kickoff meeting to sharpen the scope and out of scope
- [ ] Share a working document to enable async reviews
- [ ] ...

## Document

https://docs.google.com/document/d/1IlxR09IuhrnCquSN-KV2Qaqq7qxYCuzzZo7ZDyvi-pY/edit?usp=sharing

**Comment by mkorbi** [comment]
I discussed a draft with some end users a while back. 
<img width="1066" alt="Bildschirm­foto 2022-11-19 um 14 23 46" src="https://user-images.githubusercontent.com/16919345/202852929-b2db3bea-1c3d-498f-908c-ae56835388c7.png">

Colors:
- Green: Possible
- Yellow: Possible with restrictions
- Red: Not yet possible in a useful way

**Comment by leonardpahlke** [comment]
I created a shared google docs document which we can use for the initial draft. As soon as we are happy with a "version1" we can continue collaboration over GitHub with PRs 🙂

doc: https://docs.google.com/document/d/1IlxR09IuhrnCquSN-KV2Qaqq7qxYCuzzZo7ZDyvi-pY/edit?usp=sharing

**Comment by mkorbi** [comment]
further input from the cloud native maturity model
https://www.cncf.io/blog/2023/01/20/what-is-the-cloud-native-maturity-model-and-why-do-i-care/

https://maturitymodel.cncf.io/

**Comment by jawache** [comment]
This is very interesting work, let me add in a few folks if you don't mind, I remember us having a think about this a while ago @dubrie, @scottcha? A maturity model - I can't remember the exact details, I think @dubrie you might have come up with some ideas.

The thing I liked about the approach was it's more focused on teams than products, so a maturity model for teams who build products, since if a team is green, using good green processes, then their products are going to likely be as green as possible (given their other tradeoffs).

I remember it something like:

1 - Nothing, doing nothing, thinking nothing about this space.
2 - Decided which metrics are important to track.
3 - Actively measuring those metrics during development/integration.
4 - Actively implementing features to reduce the measured metrics.
5 - Actively monitoring those metrics live in production apps.

**Comment by leonardpahlke** [comment]
@mkorbi I updated the milestone. Its now set to Kubecon NA.

**Comment by leonardpahlke** [comment]
We just touched on env sustainability maturity for CNCF projects in our weekly call (5th of July 2023) while discussing the WG Green Reviews charter. see #116 

> Create a general set of action items for CNCF project maintainers on how they can mature their project successively to improve their sustainability footprint

The above deliverable was removed from the working group charter, but could be a good upcoming sub-project of the working group after it is formed. (FYI @nikimanoledaki @guidemetothemoon)

**Comment by mkorbi** [comment]
FYI
The green software maturity matrix

https://docs.google.com/document/d/1wa2lliXQeH6HE1JHqwjTFuVndRUXzxGlbYXRtTQxF5o/mobilebasic

**Comment by mkorbi** [comment]
Here is the Update of the CN Maturity Model:
https://maturitymodel.cncf.io/#the-cloud-native-maturity-model-30-updated-in-autumn-2023

**Comment by leonardpahlke** [comment]
Are there any action that we like to draw out of this issue? If not we can close this.
