### ISSUE TITLE
[Action] WG Comms Rebrand

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#502]
### Description

After discussion in the main TAG meeting and the WG meeting we are agreed that re-branding (new naming) would be useful for the WG Comms team. This will help us align our goals better and give us a better direction. It will also be easier for others to know what we do!

The suggestion is "WG Environmental Sustainability Advocacy" or "WG Sustainability Advocacy"

### Outcome

New name for the WG which is changed in all relevant locations. This should also guide the WG roles as well as new plans for what we can achieve together! Things like the sustainability week fall nicely under this WG especially with the new name.

### To-Do

- [x] Change name in WG meetings and TAG meetings
- [x] Change name in the calendar CNCF and Google
- [x] Change name across the website
- [x] Change name on github in tags etc.
- [x] Change name in charter and anything else in github
- [x] Change name on the project board
- [x] Change name in the TOC report/update template
- [x] Change in any media/presentations
- [x] Change in slack channel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
+1 for  _WG Sustainability Advocacy_

**Comment by guidemetothemoon** [comment]
Agree with Valeria - WG Sustainability Advocacy sounds nice😊

**Comment by leonardpahlke** [comment]
+1 for WG Sustainability Advocacy

**Comment by nikimanoledaki** [comment]
+1 WG Sustainability Advocacy 🥳 🌱

**Comment by ams0** [comment]
+1 WG Sustainability Advocacy! Or WG Planet Advocacy :)

**Comment by claire-fletcher** [comment]
That is confirmed! We will start the rebrand after the roadmap meeting and kick off. We also announced it at the sustainability week event which was nice.

**Comment by claire-fletcher** [comment]
I have added the items we came up with in our planning meeting to the To-do list.

**Comment by guidemetothemoon** [comment]
Weekly meeting naming is updated in Google calendar. Created service desk ticket for CNCF to update naming and update the meeting time and frequency as per Google calendar. Ticket number: **CNCFSD-2545**

**Comment by vallss** [comment]
I can work on these two points if that's okay
- [ ]  Change name across the website
- [ ] Change in any media/presentations

cc @claire-fletcher @guidemetothemoon @Nancy-Chauhan

**Comment by vallss** [comment]
Change name in the TOC report/update template --> does anyone know where I can find the TOC report/update template so I can update it? cc @claire-fletcher @guidemetothemoon @Nancy-Chauhan

**Comment by claire-fletcher** [comment]
@leonardpahlke will update the TOC
