### ISSUE TITLE
[Tracking] Environmental Sustainability Survey & Results

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#51]
#### Description

We currently have a [survey](https://www.surveymonkey.com/r/TAG-Environmental-Sustainability-2022) out to collect input from the community on their challenges in applying sustainability as a factor within their IT landscape.

The survey will close at the end of November.

The results need to be analyzed and visualized, interpreted and placed into a mini report.

### Milestones

- [x] Create a survey before KubeCon and publish it
- [x] Communicate survey at KubeCon
- [x] Communicate survey at KCDs around Europe
- [x] Close Survey
- [x] Results are analyzed
- [x] Report is created
- [x] Report is communicated

### Input

- Survey results

### Outcome

- Report on the state of Sustainability within the Cloud Native community

#### Todos

- [x] Create a survey
- [x] Present survey at KubeCon NA
- [x] Talk to KCD organizers to enable them to communicate the survey too
- [x] Analyze the results of the survey
- [x] Write a report on the survey
- [x] Present and communicate the survey at KubeCon EU

**Comment by mkorbi** [comment]
Survey results received - anyone up to support us in interpretation the results and developed a report out of it?

**Comment by caradelia** [comment]
I can starting next week.

**Comment by leonardpahlke** [comment]
spreadsheet with the data: https://docs.google.com/spreadsheets/d/1VwIIwF1KLe2dzl7znfONjd8Q7Yn_IHxo/edit?usp=sharing&ouid=116491369110669949344&rtpof=true&sd=true

**Comment by berryq460** [comment]
Hi! I am also at Red Hat along with Cara and would love to help out with this!

**Comment by mkorbi** [comment]
I have started to summarize the results here: 
https://docs.google.com/presentation/d/1PTgODgWKX_N_xXwKmRsmaKLDQ-a0hv1fZs-KYhOQYIM/edit?usp=sharing

**Comment by berryq460** [comment]
Awesome work even during the holidays wow! Is there anything left to do. Im
currently on PTO in Japan. Will try my best but I'm definitely passionate
about this cause and want to help when Im back.

**Comment by mkorbi** [comment]
Heya a first draft is available: https://docs.google.com/presentation/d/1PTgODgWKX_N_xXwKmRsmaKLDQ-a0hv1fZs-KYhOQYIM/edit?usp=sharing

**Comment by leonardpahlke** [comment]
💯, this already looks great! I will have another closer look beginning of next week.

**Comment by berryq460** [comment]
This is awesome to see the final product: as mentioned on today's call, can we aim to include the following in the deck as well:

-  a mission slide for our group and a high level summary of the goals of this study, 
- what we learned from the study and how we plan to iterate in a future survey
- areas of further study we'd like to investigate that weren't in the scope of this survey

**Comment by mkorbi** [comment]
the draft is reworked and cleaned up. added slides about the TAG and future approach. Left it on some points more open to have more options.

**Comment by catblade** [comment]
Looks great.  Thanks for all the pretty graphs.

**Comment by leonardpahlke** [comment]
@mkorbi I created an empty document for the survey announcement blog post https://docs.google.com/document/d/1Y-U1GnKs_y_DKWKxSugjGSaXq7ORS1UUNFvHwjhuRMQ/edit#heading=h.73pgf6pbinj0

**Comment by mkorbi** [comment]
https://github.com/cncf/tag-env-sustainability/pull/80

**Comment by catblade** [comment]
Are we ready to close this?

**Comment by leonardpahlke** [comment]
I believe @mkorbi was working on a small blog post sharing the results
