### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Lorient

### ISSUE THREAD

**Issue by JulieChenadec** [cncf/tag-env-sustainability#518]
### Description

* **Location/Region:** Lorient, France
* **Organizers:** Sébastien DAVOULT, David AUFFRAY, Chamseddîne Saadoune
* **Sponsors:** CCI Morbihan
* **Date:** September 25
* **Event link:** (https://community.cncf.io/events/details/cncf-lorient-presents-cloud-native-lorient-5/)

### Details

Ce groupe s'adresse à tous les passionnés et curieux de l'univers cloud natif. Notre objectif : faciliter les échanges et l'apprentissage en rapport avec ces technologies pour tous les passionnés de l’écosystème cloud natif de la région Lorientaise.

### To-Do

- [x] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [x] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [x] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9
