### ISSUE TITLE
[Project Tracking] Learning path towards Sustainability in Cloud Native

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#52]
#### Description

The idea is to craft a comprehensive learning path for everyone new or interested in this topic. It should be the first step in enablement for open source contributors and lead them by pointing out relevant information and educational content.

#### Impact

Our target is to provide education. Having a starting point on hand to drop for the community will give an initial direction and hopefully make people think about how to apply this in their projects.

#### Scope

- Focusing on how to apply sustainability in your development and projects
- Giving input at which points for a typical oss project energy is wasted

**Out of Scope**

- Shouldn't go beyond practical and actually useable approaches
- No re-invention of ESG in general
- Exclude topics that are out of hand of an OSS project

#### Additional info and comments

- Reference to supporting material:
  - [Green Software Patterns](https://patterns.greensoftware.foundation/)
  - [Green Software for Practitioners (LFC131)](https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/)

#### Goals and Non Goals

The goal is to describe a learning path for the average DevOps/Platform Engineer, who usually has already cloud native systems (containerized environments) in their responsibility.

It's not a goal to build a training, but to put together what can be considered useful and describe the glue between to build a track path.

### Project Details

- **Project leads**: OPEN
  - *link project leads here*
- **TAG ENV Lead representative**: @mkorbi 
- **Project started**: *XX-XX-XX*
- **Project completed at**: *XX-XX-XX*
- **Project drive folder**: link 
- **Meeting Details**: 
  - *[link]([https://zoom.us/my/cncftagenvsustainability](https://www.google.com/url?q=https://zoom.us/my/cncftagenvsustainability&sa=D&source=calendar&ust=1708280600956315&usg=AOvVaw3qvZA1j9rdGeK2GJX_H_mA))*: `77777`
  - Meeting Notes: [link](https://docs.google.com/document/d/1VofzQRwvtt-4svcV_rd5UifX_4CrpwN8FokAcJH4CF0/edit#heading=h.141ku98j3mk3)
  - Schedule: *every two weeks on Tuesday at 5pm CET* see [calendar](https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com)

### TODO

- **Starting up**:
  - [ ] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
  - [ ] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
  - [ ] Slack Channel created (only if needed) 
  - [ ] Project Google Drive folder created 
    - [x] Meeting Notes document created
  - [ ] Meeting Time & Day scheduled 
- **Report to the TAG ENV every two weeks**:
  - Update summary given on *03-01-2024*
  - ...
- **Closing the project**:
  - [ ] Reached out to the TAG Lead representative to complete the project deliverables
  - [ ] Deliverables releases to the community if applicable
  - [ ] Project retrospective [issue opened](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=presentation%2C+triage-required&projects=&template=retrospective.md&title=%5BRETRO%5D+project+title)
  - [ ] Project retrospective completed

cc @cncf/tag-env-sustainability

**Comment by SaxenaAnushka102** [comment]
Hey @mkorbi! This sounds pretty cool. What kind of a learning module is this going to be? Can I get to know more about the topics to be covered?

**Comment by rolarblaze** [comment]
Hello @mkorbi this is an interesting project i would love to be part of once the structure and plan is rightly outline i will love to jump in

**Comment by kumarankit999** [comment]
Thanks @mkorbi ! It will be a very fantastic project. I would love to be in this project and contribute too.

**Comment by vallss** [comment]
Hi @mkorbi, this would be very useful. I started learning about Sustainability related to User Experience and then shifted to Cloud Native and Open Source and I think that writing down a base learning path could help people interested in the subject.

**Comment by AntonioDiTuri** [comment]
That is an amazing idea! At the TAG we are currently prioritizing other topics. 
Maybe we can start discussing a long term planning? I can create a follow-up issue for that :)

**Comment by russelltrow** [comment]
Hey, I'm the PM at the Green Software Foundation who looks after our Principles & Patterns projects. If this becomes a priority for the TAG I would love to collaborate.

**Comment by mkorbi** [comment]
Hey @russelltrow @AntonioDiTuri @vallss @kumarankit999 @rolarblaze, what do you think about a kick-off meeting past KubeCon? 
Drop me your mail in the CNCF Slack, you should find me by my full name and I will create a doodle.

**Comment by mkorbi** [comment]
Vote invite is send, for those where I didn't have the email, please self assign: https://fantastical.app/p/X8lUDKcu1GbnVT

**Comment by AntonioDiTuri** [comment]
Thanks for sending out and organizing the invitation. Looking forward!

**Comment by mkorbi** [comment]
We start noting down or thoughts and ideas, please feel free to add yours: https://docs.google.com/document/d/1VofzQRwvtt-4svcV_rd5UifX_4CrpwN8FokAcJH4CF0/edit?usp=sharing

**Comment by leonardpahlke** [comment]
Hey all, what is the status of this project - is it a project? Who is taking charge, do we need support? If there is progress, it would be great if we can report on the progress during the TAG meetings and record the project as an official project with a charter (short one) on our website.

**Comment by kumarankit999** [comment]
Very Apologies to see on this issue, you can @mkorbi reach out to me ankit6170kumar@gmail.com

**Comment by caradelia** [comment]
@mkorbi @leonardpahlke As this seems to be moving to a project, we will need to have a project template for. https://github.com/cncf/tag-env-sustainability/tree/main/projects

**Comment by leonardpahlke** [comment]
Yes, thats one of the to-do steps.

> - [ ] Project details added to the [repository](https://github.com/cncf/tag-env-sustainability/tree/main/projects)
> - [ ] Project details added to the [website](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/about)
> - [ ] Slack Channel created (only if needed)
> - [ ] Project Google Drive folder created
>     - [x] Meeting Notes document created
> - [ ] Meeting Time & Day scheduled

**Comment by caradelia** [comment]
@mkorbi @leonardpahlke I am going to add this an agenda item to discuss at next week's meeting.  I like the idea of this project, but without meeting the basic criteria of having a project lead, I recommend we pause the Learning Path efforts until our landscape is in a solid state along with our road map. And in the roadmap, we include the Learning Path for later this year- maybe summer.

**Comment by leonardpahlke** [comment]
I am closing this issue as this project around Cloud Native Sustainability learning path has been cancelled. If this idea or an idea that goes in the direction of this topic meets with interest again, we can open a new issue! Thanks all.
