### ISSUE TITLE
[Action] KubeCon EU Co-Located Event Proposal

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#523]
### Description

**Due by October 1st**

We are planning a half day co-located event which requires a proposal.

Previous: https://docs.google.com/document/d/1emm9WqvS881-LvNmEVlRwgoIRUg2K_nEn-QR6sBva8A/edit?usp=sharing

### Outcome

Proposal for our event.

### To-Do

- [ ] Decide the plans
- [ ] Coordinate with interested people
- [ ] Write up and submit proposal

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ams0** [comment]
@claire-fletcher happy to help, I have experience organizing the virtual mini-conference online and the amsterdam event in-person. I absolutely love the idea of having a Colocated event in London! We need to decide:

- half day or full day (I'd say half)

Let's team up and be prepared for London 2025! Looks like the deadline is gone tho https://docs.google.com/forms/d/e/1FAIpQLSeuHhmKdOynPDCJanswRMNgC-zloP4oFpbR8-F9aIiK_R_Fkg/viewform

I can ask if we can still propose something.
