### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024  Bangalore

### ISSUE THREAD

**Issue by humblec** [cncf/tag-env-sustainability#528]
### Description

* **Location/Region:** Bangalore
* **Organizers:** Prakash Mishra, Humble Devassy Chirammal , Kiran Mova
* **Sponsors:** TBD
* **Date:**  Proposed Date: 19-Oct-2024
* **Event link:**[CNCF Sustainability meet-up Bangalore 2024]( https://community.cncf.io/e/mm5vmv/)

### Details

With the learning we have and from the experience we made from last years' sustainability meet-up , we would like to have a panel, sessions, open forum in this meet-up. 

### To-Do

- [x] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [x] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [x] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Hey @humblec  Thank you for creating the issue , however I don't see any updates to the table for Bangalore, India. Am I missing something ?

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
