### ISSUE TITLE
[Tracking] Implement a Website for the TAG

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#53]
#### Description

The idea is to have a simple website that visualizes our outcomes, recommendations etc., in a more human-friendly way.

### Milestones

1. Prepare website 
2. Prepare website for Kubecon EU

#### Todos

- [x] create first draft
- [x] set website live
- [x] define general content
- [x] define content for Kubecon EU
- [x] add content, general & Kubecon EU

**Comment by agardnerIT** [comment]
I'm not a graphic / web designer but happy to help with prose and content.

**Comment by catblade** [comment]
@caradelia ping

**Comment by mkorbi** [comment]
@caradelia just created one within the Env gdrive
https://docs.google.com/document/d/1pP6RSc7QzdWUil_27eOLUEmI037-KaGDG3TzPz-uTyw

**Comment by berryq460** [comment]
Happy to help as well!

**Comment by SaxenaAnushka102** [comment]
Sounds cool! I'd love to contribute.

**Comment by leonardpahlke** [comment]
updated the description, @caradelia PTAL

**Comment by leonardpahlke** [comment]
@berryq460 & @SaxenaAnushka102 great to hear! I added some things to the [content document](https://docs.google.com/document/d/1pP6RSc7QzdWUil_27eOLUEmI037-KaGDG3TzPz-uTyw/edit), its open to edit to anyone 🙌  feel free to write directly or comment :)

**Comment by caradelia** [comment]
@leonardpahlke I need help on merging the Github page I created in my personal repo into the TAG. I will invite you to the repo if you could look at.

**Comment by leonardpahlke** [comment]
👍, I will request a repository under the CNCF organization and we can push it over

**Comment by leonardpahlke** [comment]
I talked to the CNCF and they are checking if we can get the website at sustainability.cncf.io. If thats possible we would have a similar setup as tag-contribex, see website folder in the tag repo https://github.com/cncf/tag-contributor-strategy/tree/main/website

**Comment by leonardpahlke** [comment]
@caradelia @berryq460 @SaxenaAnushka102 if you like to help on this effort feel free to add to this document https://docs.google.com/document/d/1pP6RSc7QzdWUil_27eOLUEmI037-KaGDG3TzPz-uTyw/edit 👍

**Comment by berryq460** [comment]
Reviewed the doc quickly. If not included yet I think we could aim to include a section dedicated to showing a key compelling data visualization or chart to drive the point home of what we are measured in our latest survey and what we hope to measure in a future survey.

Ex: It can be a clickable chart that goes to the pdf of the slide deck

**Comment by leonardpahlke** [comment]
We'll be setting up a website with a Github page repository soon, and depending on how the website shapes up over time, we might push it to sustainability.cncf.io.

Thanks @nate-double-u for handling this at the CNCF

**Comment by cjyabraham** [comment]
Hi All. I can set up sustainability.cncf.io for you. I manage many of the websites across the CNCF ecosystem, including sites like the [Glossary](https://glossary.cncf.io/), [Maturity Model](https://maturitymodel.cncf.io/), and [App Delivery](https://appdelivery.cncf.io/). We have a theme on those sites we can easily adapt for this purpose.

I would need to know what the Information Architecture needs to be to support your efforts going forward. What is the full vision for the site? You'll see each of the examples above use slightly different nav elements. Once you have all the content done for the site, let me know and I can start work.

**Comment by leonardpahlke** [comment]
@cjyabraham thank you! We started drafting up the topics we would like to put on the website. 
We came up with information about the charter, members, events where are at (for example where we meet up in person at Kubecon Eu, which talks are presented by us, which other talks at the conference in our domain, ...). We have some projects in the works at TAG where we're working on best practices, landscape and other things. We will probably expand at some point in the future the list of things we would like to put on the website. 

Looking at the pages listed above, I could see that we have an about page and a contribute page + an events page for now.

**Comment by cjyabraham** [comment]
Sounds good! Do you have a deadline you'd like this live by?

**Comment by leonardpahlke** [comment]
If possible it would be great to have latest in 2 weeks, so we have enough time to update the pages and get all setup before Kubecon EU

**Comment by cjyabraham** [comment]
Sounds doable. If you could just get the initial content and any images you'd like prepared in the next few days then I can use them to set up the initial pages.

Could you confirm the following?
- site name: TAG Environmental Sustainability
- url: sustainability.cncf.io
- logo will have the word SUSTAINABILITY where you currently see MATURITY MODEL here:

<img width="256" alt="Screen Shot 2023-03-22 at 2 00 46 PM" src="https://user-images.githubusercontent.com/463160/227037080-1021c50b-b24d-4069-b572-e554377005fe.png">

**Comment by leonardpahlke** [comment]
> If you could just get the initial content and any images you'd like prepared in the next few days then I can use them to set up the initial pages.

Sounds good. We should be able to get it ready end of the week. cc @caradelia 

> Could you confirm the following?

✅

**Comment by leonardpahlke** [comment]
that was quick :D thanks! I will update the content in the upcoming days

**Comment by cjyabraham** [comment]
No worries. I had just launched the appdelivery site so it was fresh in my mind 😂

Once we get the basic content in place we can reconfigure the topnav and sidebar navigation so that it serves the content.

**Comment by caradelia** [comment]
This is awesome! @leonardpahlke I can help populate the content

**Comment by cjyabraham** [comment]
You may want to set up a local instance as you make edits to see the changes immediately. You can [follow the README instructions to get that set up](https://github.com/cncf/tag-env-sustainability/blob/main/website/README.md).

**Comment by mkorbi** [comment]
Thank you @cjyabraham for setting up the page and getting us ready :)

**Comment by cjyabraham** [comment]
@leonardpahlke I've merged in [your PR](https://github.com/cncf/tag-env-sustainability/pull/68) and made a few other tweaks myself to tidy things up. As you continue to add more content we can refine things more as needed. Specifically we can turn on or off the left-sidebar nav for each section depending on whether it's needed. Also, if there are going to be multiple [Events](https://sustainability.cncf.io/events/) listed, we can add the date of each in their frontmatter so that they can be listed chronologically and have past events in their own section etc.

**Comment by mkorbi** [comment]
@cjyabraham would it be possible to trigger Netlify previews only on changes within /website?

**Comment by cjyabraham** [comment]
I believe this is how it should be working. Are you seeing something different?

**Comment by leonardpahlke** [comment]
this is done!
