### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Santiago

### ISSUE THREAD

**Issue by scanalesespinoza** [cncf/tag-env-sustainability#538]
### Description

* **Location/Region:** Santiago, Chile
* **Organizers:** Pablo Rene Esquerra Veas, Jesus A. Rodriguez B., Mary Montesinos, Efrain Esteban Duarte Campos, Sergio Canales
* **Date:** Oct. 22
* **Event link:** https://community.cncf.io/events/details/cncf-cloud-native-santiago-presents-cncf-cloud-native-sustainability-week-2024-santiago-meetup/

### Details

Aknowledge about the TAG ENV Sustainability.
Present two sesions related of how to make positive impact in the environment by apps and platform implementations.
Celebrate and involve the community.

### To-Do (Preparation)

- [x] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [x] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [ ] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### To-Do (During Execution)

- [ ] Use the [Artworks](https://www.figma.com/design/gydAB5esFpNxO3smhZTCkl/Sustainability-Week-Layouts---Shared?node-id=8-90&node-type=canvas) and [Presentation Template](https://docs.google.com/presentation/d/15Ywyw2YjNyckXs7lEWySrjC4fh7pLglUkDZOipLDQB4/edit#slide=id.g302f22217e4_2_173). You can use some slides in the template at the begining of the event for introducing the cloud native sustainability week event.
- [ ] Distribute the feedback survey to attendees. Use the [Survey Blueprint](https://docs.google.com/forms/d/e/1FAIpQLSeIsz3T5XHhQf9ZMhfmHAchvGX5_enteQ5j9ZmIsMoFjshfGg/viewform).
- [ ] Record the event with photos or video recordings.

### To-Do (After Event)

- [ ] Share the event records, summary via blog post, recordings to `#tag-env-cloud-native-sustainability-week` slack channel.
- [ ] Share the survey summary from attendees.
- [ ] Leave feedbacks/comments (KEEP DOING, MORE OF, START DOING, STOP DOING, LESS OF, IDEAS) about organzing the event in this issue.
- [ ] Submit the information of organizers, speakers to issue the credly badges. [to put the submission form here]

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
Hi @scanalesespinoza can you open a PR on the website to add all the information about the event? If you need any help with this, feel free to ask!

**Comment by scanalesespinoza** [comment]
Hi @vallss here it is: https://github.com/cncf/tag-env-sustainability/pull/543

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
