### ISSUE TITLE
[Tracking] Kubernetes ♻️ Practices & Scheduling

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#54]
#### Description

Kubernetes is the key driver and foundation of the cloud native universe. Within this project, we will work on the basic capabilities, best practices and scheduling mechanism as well as extensions to improve the K8s GHG impact.
Where are patterns, there are anti-patterns, where we improve for speed, resistance and security, there is space for configurations and setting with a negative impact on power consumption and the following chain.

Cluster sprawls, container sprawls, false scheduling, wrong resource limits/requests, and no de-scheduling all these are very default capabilities of Kubernetes, but most of them are not done at all or are very wrong, treating K8s like a VM system from the early 2000's.

We should try in the beginning to stay with the very basic capabilities of Kubernetes as well as anything that is in the context of scheduling.

Originally posted in the [discussions](https://github.com/cncf/tag-env-sustainability/discussions/23).

Related to the [maturity model.](https://github.com/cncf/tag-env-sustainability/issues/50)

### Milestones

1. Collection of best practices
2. A verbalized guide

### Input

- Current K8s best practices
- CN landscape and EnvSus landscape
- ...

### Outcome

A best practice guide.

#### Todos

- [ ] Collect best practices and their potential impact on power consumption, efficiency etc.
- [ ] Identify the missing pieces and declare them as such
- [ ] Write a best practice guide

**Comment by agardnerIT** [comment]
What and where can observability tooling (vendor or open source) provide help, guidance and insight here?

I imagine Observability tooling could highlight: `You're running a 30 node cluster at 15% capacity. We suggest scaling it down to X.`

**Comment by mkorbi** [comment]
Metrics and, therefore, observability tools are for many of those things a foundation. having insights across the cluster and actively triggering events that tell like that the current cluster scale/setting isn't optimal would be already a step and afaik can be done with some tools. Historical data to prevent failures: To optimize resource consumption is one thing, but if it fails because on a black Friday, it doesn't scale fast enough, this optimization will be reverted by the business very fast.

**Comment by leonardpahlke** [comment]
I created a shared google docs document which we can use for the initial draft. As soon as we are happy with a "version1" we can continue collaboration over GitHub with PRs 🙂 

doc: https://docs.google.com/document/d/1lgXe-37JKeIxrRQan9vzVdjzAu8SQzGXKiTOmU2jWkE/edit?usp=sharing

**Comment by darrylcauldwell** [comment]
Should the best practices include reference to the proof of concept work done by Bristol university researchers in 2019? https://ceur-ws.org/Vol-2382/ICT4S2019_paper_28.pdf

**Comment by leonardpahlke** [comment]
> Should the best practices include reference to the low carbon scheduler work done by Bristol university researchers in 2019? https://ceur-ws.org/Vol-2382/ICT4S2019_paper_28.pdf

its a good paper, we can mention it for sure :)

**Comment by leonardpahlke** [comment]
Thanks @mehmetmgrsl for your input 😄 and thanks @BGrasnick for adding this image to the document. I like it when information gets presented also visually. 

I'll add my ideas and comments to the document this week. After we have a little more information together, I would love it if we could all collaborate on a CNCF blog post and present the information we brainstormed to the wider community in a more consumable and enjoyable way.

(at)all, If you have ideas on this topic, please add your ideas to the document.

**Comment by leonardpahlke** [comment]
Its on my list. I created an empty document for us to draft a blog post :) https://docs.google.com/document/d/1J9fmpjpJGTRvQnuyzMXourXqupv1Of3FSomQHPjCfBg/edit#

**Comment by leonardpahlke** [comment]
> Its on my list

After Kubecon..

**Comment by xamebax** [comment]
I'm really happy to learn about this initiative as I'm a Kubernetes operator, and I've been doing a lot of thinking about making Kubernetes clusters I'm responsible for more sustainable, while also feeling overwhelmed by the number of potential actions. I have some ideas on how to approach this topic that I'd like to share.

## Effort / impact axis

![](https://cdn.business2community.com/wp-content/uploads/2018/10/impact-effort-matrix.jpg)
Source: https://cdn.business2community.com/wp-content/uploads/2018/10/impact-effort-matrix.jpg

There are many ways one can tweak a Kubernetes cluster in order to reduce its carbon intensity. These ways will require a different level of effort and will result in different gains. While we can hope that in the end, most organizations will implement all feasible changes to Kubernetes clusters, the truth is that most organizations won't have a sustainability budget. Sustainability is still seen as a direct result of cutting costs, or an afterthought. That means that developers/infrastructure engineers will have limited occasions to make an impact. I think it is then important to estimate the effort required and the potential impact each piece of advise has, so that people reading our suggestions feel better equipped to make the choices that fit the time they have available.
## Layers of Kubernetes

Another approach would be to separate the advice in layers: the provider layer, the application layer, and so on. Not every Kubernetes tweak that results in a greener cluster must be related to Kubernetes internals. For example, when running Kubernetes in the cloud, there are cases when simply moving to a different zone makes an impact bigger than multiple other tweaks combined. Then there are the node types - not just their CPU/RAM/disk size combinations, but also whether they are dedicated or spot/preemptible nodes. Are these choices about Kubernetes internals? You could answer both yes and no, but they relate to Kubernetes and can make an impact.
## Recommendations might not be universal

There are different flavors of Kubernetes, and they have differences. The cluster size and types of workload will also differ. Therefore, what will work for one organization, won't work for another. The classic "it depends" applies in this case, too. I think it's important to keep that in mind because what intuitively feels right might be counter-productive and actually lead to increasing a cluster's carbon intensity.

An example I've had on my mind is advice to keep Kubernetes nodes small. This fits the tried and true pattern of enabling more granular scaling. But, keeping nodes small might not always work to our advantage. Each new node will have some of its resources reserved by workloads such as DaemonSets used for observability (log collectors, Grafana agents, and so on), Pods coming from cloud providers in the case of managed Kubernetes, and so on. It feel like the more observability we want into the state of our cluster, the higher percentage of each small node will be reserved for these workloads, and the less of it can be utilized by our applications, thus leading to *de facto* overscaling. Add to this bigger workloads from your data and insights team, churn the metrics, and it turns out you'd be better off having fewer big nodes. But where does that line go? Is it worth finding it out? How would one do that? Is it even a problem worth thinking about?

Which brings me to...

## A data-driven approach

As a Kubernetes operator, I would love to see each example accompanied with data showing what impact do the changes have. For example, if we give advice to drop ingestion of unused metrics or restrict metric labels in Prometheus to avoid cardinality explosion and decrease load on the network layer (and on Prometheus), I'd like to see how much of an impact this would make in a cluster that runs 30, 300, 600 services. So that I can compare it to the cluster(s) I'm running and spend less time deciding if that's the way to go with my constrained time budget.

What I would also love to see, especially as an operator, is ideas for dashboards, queries, exporters, anything out of the box, however small, that makes collecting and presenting such data easier.

## Summary

I'm really eager to work on developing sustainable practices for running Kubernetes and I'm also happy running practical experiments to gather data. 🙂

**Comment by leonardpahlke** [comment]
Awesome!! @xamebax could you propose picking up the work on this issue in this discussion https://github.com/cncf/tag-env-sustainability/discussions/277. We are currently collecting ideas to get an overview what the community would like to work on. Thanks!

**Comment by JacobValdemar** [comment]
I would also like to help with this. I have time after January 2024. I have learned a lot from writing my master's thesis _Carbon Efficient Karpenter: Optimizing Kubernetes Cluster Autoscaling for Carbon Efficiency_ which I would love to share 💚

**Comment by mkorbi** [comment]
Migrated and moved this prosal over to https://github.com/cncf/tag-env-sustainability/issues/339 as project
