### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 New York City

### ISSUE THREAD

**Issue by karenhchu** [cncf/tag-env-sustainability#544]
### Description

* **Location/Region:** New York, NY, US
* **Organizers:** Karen Chu, Scott Rigby, Tony Marfil, Nancy Chauhan
* **Sponsors:** F5
* **Date:** Oct 15, 2024
* **Event link:** https://community.cncf.io/events/details/cncf-new-york-kubernetes-meetup-presents-cncf-cloud-native-sustainability-week-2024-nyc-meetup/ OR https://www.meetup.com/new-york-kubernetes-meetup/events/303965101/?eventOrigin=group_past_events

### Details

- 10 min: Intro to TAG ENV Sustainability & its projects (@Nancy-Chauhan )
- 30 min: How NASA scientists and Navteca technologists use Cloud Native to collaborate on addressing climate change (Shayna Solis & Aaron Skolnik, Navteca)
- 30 min: Towards Sustainable Cloud Security: A DevSecOps Practicioner's Suggestion (Aseem Shrey, SecureMyOrg)

### To-Do (Preparation)

- [x] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [x] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [ ] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### To-Do (During Execution)

- [x] Use the [Artworks](https://www.figma.com/design/gydAB5esFpNxO3smhZTCkl/Sustainability-Week-Layouts---Shared?node-id=8-90&node-type=canvas) and [Presentation Template](https://docs.google.com/presentation/d/15Ywyw2YjNyckXs7lEWySrjC4fh7pLglUkDZOipLDQB4/edit#slide=id.g302f22217e4_2_173). You can use some slides in the template at the begining of the event for introducing the cloud native sustainability week event.
- [ ] Distribute the feedback survey to attendees. Use the [Survey Blueprint](https://docs.google.com/forms/d/e/1FAIpQLSeIsz3T5XHhQf9ZMhfmHAchvGX5_enteQ5j9ZmIsMoFjshfGg/viewform).
- [x] Record the event with photos or video recordings.

### To-Do (After Event)

- [x] Share the event records, summary via blog post, recordings to `#tag-env-cloud-native-sustainability-week` slack channel.
- [ ] Share the survey summary from attendees.
- [ ] Leave feedbacks/comments (KEEP DOING, MORE OF, START DOING, STOP DOING, LESS OF, IDEAS) about organzing the event in this issue.
- [ ] Submit the information of organizers, speakers to issue the credly badges.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Comments

will update with more details as we confirm them in the next few days

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by karenhchu** [comment]
PR for website update here: https://github.com/cncf/tag-env-sustainability/pull/573

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
