### ISSUE TITLE
[BLOG] Event Wrap-Up: First Tokyo Local Meetup in CNCF Cloud Native Sustainability Week 2024

### ISSUE THREAD

**Issue by sunya-ch** [cncf/tag-env-sustainability#547]
### GitHub tag of Blog Authors

@sunya-ch

### GitHub tag of Blog Reviewers

updated once people start reviewing the blog

### GitHub tag of TAG ENV Lead that sponsors the blog

updated once a TAG ENV lead assigned themselve

### Abstract

An event wrap-up blog post for Cloud Native Sustainability Week 2024 - Local Meetup Tokyo.

### Scope

Focus on summarizing the activity in sustainability week local meetup in Tokyo

### Goals and Non Goals

Goals:
- summarize meetup
- share photos
- encourage for the next meetup
- promote the community

### Todo items starting the blog post process

- [x] [Author] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
- [x] [Author] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
- [ ] [TAG ENV Lead] One of the TAG ENV leads assigned themselves to wrangle the blog
- [ ] [TAG ENV Lead] Blog post outline and theme has been discussed
- [x] [Author] Blog post written and ready for review

### Todo items reviewing the blog post

- [x] [Author] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
- [ ] [Author] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
- [ ] [Author] Feedback and comments have been resolved.
- [ ] [Reviewers] reviewed blog post.
- [ ] [TAG ENV Lead] reviewed blog post.
- [ ] [TAG ENV Lead] ready to get published.
- [ ] [TAG ENV Lead] notified one of the ToC liaisons to sign off the blog post.
- [ ] [OPTIONAL TAG ENV ToC Liaison] reviewed blog post.

### Todo items reviewing the blog post

- [ ] [TAG ENV Lead] merged blog post.
- [ ] [OPTIONAL TAG ENV Lead] schedule the blog post on the CNCF blog next to the TAG ENV blog
- [ ] [Author] Wrote feedback about the blog post process as a comment under this issue

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by guidemetothemoon** [comment]
Blog post published: https://tag-env-sustainability.cncf.io/blog/2024-10-cloud-native-sustainability-week-2024-tokyo/
And announced on social media:
https://www.linkedin.com/posts/cncf-tag-environmental-sustainability_event-wrap-up-first-tokyo-local-meetup-in-activity-7253002125440409600-XRz1
https://x.com/CNCFEnvTAG/status/1847216171419943060

**Comment by leonardpahlke** [comment]
@sunya-ch looks like we can close this issue, right
