### ISSUE TITLE
[Action] Improve TAG thumbnails

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#549]
### Description

We have TAG thumbnails for youtube which are a bit outdated now. We can use our new branding (and new correct logo) to create new thumbnails keeping some consistency across the TAG.

Current thumbnails: https://drive.google.com/drive/folders/1QLjeOeYRztW4FKWubjYOmzAsoGEJKep3

### Outcome

New TAG thumbnails!

### To-Do

- [x] WG comms
- [x] WG green reviews (include their new logo!)
- [x] TAG overall meeting
- [x] TAG apac meeting
- [x] sustainability week meetings
- [x] Perhaps a generic one we can add to adhoc meetings/project meetings

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
@Ludovik95 there you go!

**Comment by Ludovik95** [comment]
@claire-fletcher I created on Google Slide the thumbnails for Youtube with the new design style at this link: https://docs.google.com/presentation/d/1YVvANEO69HI8IyI0c_pj5ycXVuCOtIHaLkp0F4fE3Ek/edit?usp=sharing

If they are okay I can copy them into the presentation you linked above (or into a new one, as you prefer) 😊

**Comment by claire-fletcher** [comment]
These are great! I can pop them into the drive folder I created

**Comment by claire-fletcher** [comment]
If you put it in the same folder as the old ones here: https://drive.google.com/drive/folders/1QLjeOeYRztW4FKWubjYOmzAsoGEJKep3

**Comment by Ludovik95** [comment]
Done ✨
