### ISSUE TITLE
[Tracking] Onboarding @ams0

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#564]
### Description

TAG ENV Lead onboarding. See nomination issue https://github.com/cncf/toc/issues/1458. Voting completed on October24th https://github.com/cncf/toc/issues/1458#issuecomment-2435263206

### onboarding steps

- [x] TAG ENV Leadership references updated on our [website](https://tag-env-sustainability.cncf.io/)
- [x] Meeting Notes Document(s) updated
- [ ] Update Google Drive Shared Access (only applicable for TAG ENV Chairs)
- [ ] Update CNCF Service Desk & CNCF Email Groups Access (only applicable for TAG ENV Chairs)
- [ ] Update TAG ENV Repository Settings ([cncf/people](https://github.com/cncf/people/) & [cncf-tags/](https://github.com/cncf-tags/org-admin))
- [x] Update Private Slack Channels
- [x] Update YouTube Channel Membership ([channel](https://studio.youtube.com/channel/UCMOopJuyyIWB8vXGct1ffNw))
- [x] Update Google Calendar Sharing & Edit Permissions (only applicable for TAG Chairs, TL and WG Chairs)

### Role (TAG Chair, TAG TL, WG Chair, WG TL, Project Lead)

TAG TL

### GitHub Profile

https://github.com/ams0

### Ask the contributor joining the TAG leadership team to agree to onboarding

@ams0 - please confirm onboarding by commenting under this issue! 🙌

**Comment by ams0** [comment]
Agree on onboarding, thanks @leonardpahlke !

**Comment by leonardpahlke** [comment]
- Added you to the shared google calendar. You can create meetings now (only Chairs and TAG TL can create events)
- Added you to the YT Channel.
