### ISSUE TITLE
[BLOG] Greener first-ever Sustainability London Meetup with Sustainability Week 2024!

### ISSUE THREAD

**Issue by rohitg00** [cncf/tag-env-sustainability#567]
### GitHub tag of Blog Authors

rohitg00, Santosh-Kumar-Perumal, VinodSRinCloud, MathewJoseph1993

### GitHub tag of Blog Reviewers

updated once people start reviewing the blog

### GitHub tag of TAG ENV Lead that sponsors the blog

updated once a TAG ENV lead assigned themselve

### Abstract

Greener first-ever Sustainability London Meetup with Sustainability Week 2024!

Organized by technology leaders Rohit Ghumare, Mathew Joseph, Vinod Sulochana Raveendran, Santosh Kumar Perumal, and Cloud Native Westminster, the event brought together distinguished speakers who shared insights on the intersection of technology and sustainability.

### Scope

https://docs.google.com/document/d/1DjLWBT6EBvtJSHAiBjouFquJ0pXNZAqWinhPaRkSecI/edit?usp=sharing

### Goals and Non Goals

https://docs.google.com/document/d/1DjLWBT6EBvtJSHAiBjouFquJ0pXNZAqWinhPaRkSecI/edit?usp=sharing

### Todo items starting the blog post process

- [x] [Author] described the abstract of the blog post, defined the scope, goals and non-goals, and defined the expected audience.
- [x] [Author] notified TAG ENV community to review the outline via Slack on the `tag-env-sustainability` channel.
- [ ] [TAG ENV Lead] One of the TAG ENV leads assigned themselves to wrangle the blog
- [ ] [TAG ENV Lead] Blog post outline and theme has been discussed
- [x] [Author] Blog post written and ready for review

### Todo items reviewing the blog post

- [ ] [Author] blog post PR opened (blog posts are added to the [`website/content/en/blog`](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/blog) folder for English content, images to [`website/static/images/blog/<YEAR>-<MONTH>-<title>/*.jpg`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static/images))
- [ ] [Author] gave a minimum of a week to collect public feedback, depending on reviews this will get extended. If there is a major event (conference, etc.) or holidays coming up, please extend accordingly.
- [ ] [Author] Feedback and comments have been resolved.
- [ ] [Reviewers] reviewed blog post.
- [ ] [TAG ENV Lead] reviewed blog post.
- [ ] [TAG ENV Lead] ready to get published.
- [ ] [TAG ENV Lead] notified one of the ToC liaisons to sign off the blog post.
- [ ] [OPTIONAL TAG ENV ToC Liaison] reviewed blog post.

### Todo items reviewing the blog post

- [ ] [TAG ENV Lead] merged blog post.
- [ ] [OPTIONAL TAG ENV Lead] schedule the blog post on the CNCF blog next to the TAG ENV blog
- [ ] [Author] Wrote feedback about the blog post process as a comment under this issue

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
Hi @rohitg00! I reviewed the google doc and left a small suggestion right on the last paragraph. Aside from this small change, the rest is ok for me. You can open a PR on the website 🙂 

cc @claire-fletcher @Nancy-Chauhan

**Comment by rohitg00** [comment]
@vallss 
Change accepted. Can you tell me what you meant by this?
`You can open a PR on the website 🙂`

**Comment by vallss** [comment]
Yep, in order to publish the blog post on the website under the Blog section it would be great if you or anyone who participated in the meetup create a PR similar to this one https://github.com/cncf/tag-env-sustainability/pull/548.
You can follow the same structure and change the content with the one you wrote in the Google doc. 

Let me know if you need any help

**Comment by rohitg00** [comment]
Will do it. Thanks

**Comment by vallss** [comment]
Thank you @rohitg00!

**Comment by vallss** [comment]
Hi @rohitg00! Any updates on this?
