### ISSUE TITLE
[Tracking] TAG ENV at KubeCon + CloudNativeCon Europe 2025

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#571]
### Description

Starting with the tracking issue early this time 😁
This issue is used to track TAG ENV activities during [KCCN EU 2025](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe).

### Outcome

TAG ENV presence, visibility and outreach at KCCN EU 2025.

### To-Do

Draft of potential activities and preparations that we need to do:

- [x] Should we organize an in-person meetup?
- [x] Should we print and bring stickers?
- [x] Maintainer talk - not accepted, could be a booth talk
- [x] TAG ENV booth
- [x] TAG ENV booth - create slides (ref. [example](https://docs.google.com/presentation/d/1h6keg8VqEm5E7R1rA5Yse9rXF9Ma8-BLp2EmrjNziDo/edit?usp=sharing) from previous event)
- [x] Create a list with talks and publish on the TAG ENV website
- [ ] Create a daily schedule overview with KCCN EU 2025 slide deck (ref. [example](https://docs.google.com/presentation/d/1A9c97HHlH3UlMXw7HytkTgGV27fxDu62/edit?usp=sharing&ouid=116749834652029584231&rtpof=true&sd=true) from previous event)
- [x] Are there possibilities for a co-located event, dedicated sustainability track or a permanent zone that the TAG can have throughout the event (maybe sponsored) to increase the visibility even more?
- [x] Other activities?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Comments

@claire-fletcher @Nancy-Chauhan @vallss @leonardpahlke FYI, assigning this to the WG Advocacy.

**Comment by ams0** [comment]
TAG App Delivery runs lighting talks at the booth (in SLC at least). Let's organize something similar for our TAG in London and/or in SLC? https://cloud-native.slack.com/archives/CL3SL0CP5/p1730125083761569

**Comment by claire-fletcher** [comment]
We can definitely bring stickers that we already have, new ones with the new logo (correctly oriented map) would be great

**Comment by vallss** [comment]
I can help with stickers, pins and any other gadget we want to bring there!

**Comment by claire-fletcher** [comment]
Note: the maintainer talk was not accepted for this year's conference. We will have a booth and can potentially run a small catch up from there instead!

**Comment by claire-fletcher** [comment]
I will take point as events lead for kubecon europe 2025 ensuring that all of these things happen.

**Comment by claire-fletcher** [comment]
Stickers: It implies on the kiosk email that the CNCF has made some

**Comment by nikimanoledaki** [comment]
Hello! 💚 The Green Reviews WG would like to add to the booth slides (see https://github.com/cncf-tags/green-reviews-tooling/issues/168). I requested access to the ones from last year - happy to copy it, update the theme, and start adding things!
