### ISSUE TITLE
[Proposal] Sustainability related blog & article collection

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#60]
#### Description
Set up a readme with blog posts and articles (which are publicly reachable) in the context of Cloud Native & Sustainability. This way, we can collect some good introductions and reference to it. It might also be that this could be part of the webpage (?) 

To not spam the repo we could process wise open per month a PR everyone can add their link, and merge it in the end. We are only open that PR if we have something to update.

#### Impact

This will help new contributors and everyone interested with some relevant reads. It will ease the process of getting started and having an overview. 

#### Scope

We have to focus on cloud native sources and no general ESG topics. We should only accept links to CNCF & OSS tool-related blog/articles.
Everyone can contribute. Maybe we can remember about this at every meeting.

### TODO

- [x] TAG Environmental Sustainability lead representative: @mkorbi 
- [ ] Project leader(s):
- [ ] Project Members:
- [x] Scope 
- [ ] Deliverable(s)
- [ ] Project Schedule
- [ ] Slack Channel (as needed)
- [ ] Meeting Time & Day:
- [ ] Meeting Notes (link)
- [ ] Meeting Details (zoom or hangouts link)
- [ ] Retrospective

**Comment by berryq460** [comment]
Since I already took hours to write this for the community as discussed in the meeting. Feel free to repurpose as a blog

https://docs.google.com/document/d/117Mt6sDInSxdsVA-vBI9Cwls67FvQbU2KR1WqqKY0U8/edit?usp=sharing

**Comment by leonardpahlke** [comment]
@berryq460 thanks for writing the blog post, I've added a few comments and suggested a few paragraphs I could add. I hope you don't mind. If you like, we can publish it on the CNCF blog and on our TAG ENV website sustainability.cncf.io :)

**Comment by leonardpahlke** [comment]
@mkorbi regarding the proposal _[Proposal] Sustainability related blog & article collection_

I interpret the proposal as an idea to publish sustainability news about cloud native every week / bi-week / month, mentioning blog posts and any other initiatives. I like that. I think we already passively collect a lot of resources in Slack that we "just" need to collect to write a little about and publish it on our website. 

Let's discuss this in Amsterdam!

cc @caradelia

**Comment by berryq460** [comment]
Awesome thanks I will accept your changes! Thanks for being open to it!

> @berryq460 thanks for writing the blog post, I've added a few comments and suggested a few paragraphs I could add. I hope you don't mind. If you like, we can publish it on the CNCF blog and on our TAG ENV website sustainability.cncf.io :)

**Comment by leonardpahlke** [comment]
@berryq460 Great :) let me know when you are ready and we can get the blog scheduled 👍 (no rush 😉)

**Comment by catblade** [comment]
What are you trying to accomplish with your post? 

I got halfway through the blog and added comments.  The base statement on what we do as a TAG is inaccurate, but there are also other common misconceptions about what the cloud is that are perpetuated in there that I would really like not in a blog post put out by this TAG.  @berryq460 , I would recommend you meet with someone who can help you with this blog and make it more accurate.

When we were getting together our charter, we ran MANY meetings to get that accurate (there were many revisions).  I would advise that there be at least ONE meeting you have with someone who is familiar with the cloud native field to help you with an accurate post.  Maybe at the next meeting you can get a volunteer.  Much of what this group is collaborative, so would be helpful.

**Comment by leonardpahlke** [comment]
@catblade I generally agree with your comments, but would appreciate more friendly wording.

@berryq460 I just skimmed the post again, as far as I can tell a lot has changed (that's not a bad thing), but I think we need to do another round of reviews to sharpen your post before we can publish it. Would you mind asking in the TAG slack channel for a review as soon as you are happy with the overall strcuture?

> What are you trying to accomplish with your post?

(@berryq460 correct me if I'm wrong) I think the blog post was intended to show non-technical people how they can contribute to TAG. I agree that we should make the blog post better in this regard, starting with the title "Intro to Cloud-Native Technology and Sustainability" and the structure (keep it short & simple: i.e. one sentence about the TAG, one or none about cloud native + sustainability -> quickly get to the core theme and message of the post).

**Comment by berryq460** [comment]
Sure we can have a meeting review. Based on feedback that there was already a getting starting guide, I changed the post to be of blog format of intro to cloud native and sustainability. No post will be made without reviewing for accuracy with experts, this was the plan to get feedback :)

**Comment by catblade** [comment]
@berryq460 I would recommend going to the next meeting in May (we have KubeCon this month, so that's the next meeting) or post and set up a meeting in the channel (still recommended for after KubeCon, as we have other efforts we should not be detracting from that are due then, like the landscape doc/web page/TAG meetups/TAG talks).  Have you engaged yet with the Strategy group to see advice there?

**Comment by catblade** [comment]
@berryq460  Also, we do have a TAG mission, so while I understand you may have pulled in other people,  I would recommend we stick with our current officially approved mission.  Any edits to that mission should be approved by the TAG.

**Comment by catblade** [comment]
> @catblade I generally agree with your comments, but would appreciate more friendly wording.

@leonardpahlke I was doing my best to be clear, but can certainly endeavor to add more friendly wording.

@berryq460, have you engaged with the strategy group to see if other groups are doing similar content?  And if there is in there a writeup already that you can model after?  I think it very helpful to pull ideas from a variety of sources and suspect there is already work on this with older TAGs.

**Comment by berryq460** [comment]
Hi, So I went through and accepted all your proposed changes. A couple tweaks need to be made and encourage the community to make them. I am contact with lead on CNCF Strategy side and she reviewed the blog and made edits and agrees it is tailored for this group and suits the mission and message.

**Comment by patricia-cahill** [comment]
This issue is out of date and the doc can't be accessed.  Suggestion to close and create a new issues

**Comment by leonardpahlke** [comment]
Since there is no traffic on this issue, lets close this.
