### ISSUE TITLE
[Action] TAG flyers for Kubecon EU

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#62]
#### Description

In the past, flyers have been well received at the conference as additional material (besides talks, chats, ...).
For Kubecon EU we would like to distribute flyers that contain interesting information about the TAG, how to get involved, what we plan to do, what we have worked on in the past and what we will talk about at the maintainer talk, ...

#### Todos

**pre-kubecon**
- [ ] [?] team up
- [ ] [?] define content for the handout
- [ ] [?] design handout 
- [ ] [@leonardpahlke] print handouts

**at-kubecon**
- [ ] [@leonardpahlke] distribute handouts across active TAG members (so everyone can give away some)
- [ ] [all] distribute handouts at the conference

**after-kubecon**
- [ ] [all] retro

cc @caradelia @mkorbi @catblade @nikimanoledaki

**Comment by leonardpahlke** [comment]
community has not shown a lot of interest in this effort
