### ISSUE TITLE
[Tracking] TAG ENV blog post process

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#90]
This issue is a tracking issue to work on a blog post process for the TAG. 
We do not yet have a blog post process defined (we do have one for white papers). 

Since this is not new territory for an open source group and is fairly common, I think we can adapt to the practices of other groups (Kubernetes community, etc.).
It would be great to create a new issue template which guides contributors to get the blog post written, reviewed and scheduled. 
This issue is considered done after we have this process discussed, defined and implemented.

**Comment by leonardpahlke** [comment]
example blog post issue tempate:

```
---
name: Blog Post
about: Blog website article template
title: '[BLOG] <blog-title>'
labels: 'blog'
assignees: ''

---

- **Author**: XXX
- **TAG ENV Representative**: XXX
- **Reviewers**: XXX, XXX

## Description

*Summarize what this blog post is about*

## Tasks

A more complete summary of tasks are described on XYZ.

- [ ] Outline Blog post
    - [ ] *Author* wrote a short outline of the article so it can be discussed (TAG representative, reviewers)
    - [ ] Blog post outline and theme has been discussed
- [ ] Blog post written and ready for review
- [ ] Review
    - [ ] *Author* shared blog post via GoogleDrive
    - [ ] Notified TAG Community for review via Slack on the `tag-env-sustainability` channel.
    - [ ] Waited for a week after the article has been shared to collect feedback.
    - [ ] Feedback and comments have been resolved
    - [ ] *TAG representative* & *reviewers* reviewed blog post.
    - [ ] _optional_ Notified *TAG representative* Team to schedule the blog post on the CNCF blog next to the TAG ENV blog

## Comments

`NONE`
```

**Comment by leonardpahlke** [comment]
for reference: CNCF blog guidelines: https://github.com/cncf/foundation/blob/main/blog-guidelines.md

**Comment by leonardpahlke** [comment]
> Scope as well

Agree

> and 1 week is not enough time, given that some people can be out.

That's ok

> Need to outline what "discussed" means.

I guess talk about it in this issue, in a TAG meeting and after we have something ask for opt ins via slack.

**Comment by leonardpahlke** [comment]
> Do we want to also link to the writing piece that TAG Security has and that @mkorbi had suggested regarding standards and guidelines that should be followed?

Yes 🙌, reusing parts or an entire process by a TAG or another OSS community group sounds good to me (as mentioned in the issue itself)
