### ISSUE TITLE
[Tracking Event] CNCF Global Week of Cloud Native Sustainability

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#95]
Hello, I would like to consolidate a topic that we have been discussing for some time in the TAG and other CNCF community channels. I now have enough input from the community to put it into a more complete form.

The topic cloud native environmental sustainability is still an upcoming topic in the industry and open source space. Therefore we need to focus in particular on understanding where we at, the landscape in short. Understanding the landscape happens by engaging with the community and industry and general. We are doing a great job at it but could potentially organize an event to support our engagement even more. Before KubeCon / CloudNativeCon EU 2023 and in particular during the conference this idea of an event shaped up. 

The [document](https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit?usp=sharing) explains the event in more detail.

### Event Abstract

**The CNCF Global Week of Cloud Native Sustainability leverages the structures of CNCF community groups to host a week of Cloud Native Sustainability events around the globe. In conjunction, TAG ENV will host a virtual event to talk about the group, goals, vision, projects, members and host TAG ENV external talks.**

### Event details

During the second week of October 2023, the broader Cloud Native community will organize meetups in their cities. Anyone can organize a Cloud Native Sustainability themed meetup that week and support this effort. During this week, TAG ENV will host a virtual meetup.

* **[CNCF Community Groups](https://community.cncf.io/)**: The CNCF has a program to host community meetings on Cloud Native. Over time, many chapters have emerged that meet regularly in small local community groups.
* **TAG ENV Virtual Event**: we can use from the CNCF the [bevy](https://www.bevy.com/) platform to organize and host a virtual event. We can get support by the CNCF organizing this virtual event.

I've been sharing on a channel with community group organizers about interest in organizing events. There are some interested and I can imagine that more will follow.

### Goals

* **Understand the current landscape**: Engaging with the community and industry to better understand the landscape of cloud native environmental sustainability.
* **Identify Knowledge Gaps**: Identifying areas of knowledge gaps and further exploration in cloud native environmental sustainability.
* **Foster project collaboration**: Facilitating collaboration among participants on ongoing projects and tools related to cloud native sustainability.
* **Raise awareness**: Increasing awareness and knowledge about cloud native environmental sustainability.
* **Promote TAG ENV and CNCF**: Promoting the #tag-environmental-sustainability and raising awareness about the CNCF in general.
* **Survey**: distributing a survey to gather information on end user adoption of cloud native sustainability.
* **Badges**: providing badges from [credly](https://www.credly.com/) for organizers and potentially speakers.

#### Next steps

- [x] (End of May) Reach out to folks for their interest
- [x] (Early June) Share the planning with interested folks, wait for feedback, and work it in.
- [x] (May, June) Find volunteers to help with the “event week organizer” tasks
- [x] OPTIONAL (June) schedule a meeting to discuss the event with everyone interested
- [x] (July, August) Event week organizers work on there tasks
- [x] (July, August, September) Local meetup organizers, organize their local meetup
- [x] (September, October) Event week organizers work on announcements
- [x] (October) CNCF Global Week of Cloud Native Sustainability
- [ ] (End of October) Event Retro
- [ ] (November) Event week organizers share their evaluation on the survey and the event

---

* **Timeline**: We target the second week of October (W41)
* **Document**: https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit?usp=sharing
* **Drive**: https://drive.google.com/drive/folders/1pdBQTxlpvDr0QFIuIpjfERau1IQNfdaX?ths=true

cc @k8tgreenley (community group event), @onlydole (ecosystem related)
cc @catblade @caradelia @mkorbi & myself (TAG ENV leads)

**Comment by AntonioDiTuri** [comment]
Thanks a lot for proposing this! I also think in-person events work better. Have you ever organized events before? I am not sure about the agenda cause I just joined recently, but I would be happy to help organizing one. Can we do it in Munich?

**Comment by nikimanoledaki** [comment]
This is an awesome idea!

Regarding the local event that I could help to organise here in Barcelona: a couple of folks and I are trying to revive the Cloud Native Barcelona community here that has been dormant since 2019 due to the pandemic. Hopefully we will be able to revive it and organise this here in person through that 😄

There are a couple of events that have done a similar international/local community format that we could learn from:
- [GrafanaCON](https://grafana.com/about/events/grafanacon/2023/?pg=events&plcmt=featured-events-1) is coming up in June and they are organising mini local events across many cities.
- The Green Software Foundation [Global Summit](https://summit.greensoftware.foundation/) in 2022 also did something similar where they had e.g. the closing ceremony in a virtual format, with local mini events across many cities as well.

Does that sound like what you have in mind, @leonardpahlke?

**Comment by leonardpahlke** [comment]
Just putting it out there: How about we target the second week of October (W41)?

**Comment by nikimanoledaki** [comment]
That would be between OSS Europe (September 19-21) and KubeCon NA (November 6-9) - not sure if that gives us enough time to prepare for everything 🤔

**Comment by nikimanoledaki** [comment]
+1 on this timeline - I was thinking the same 😅 We are looking at either October 2023 or all the way into Spring 2024.

Given that my limited experience with organising events/conferences, it is difficult for me to estimate how much time it would take to plan or how much time ahead we should plan this. What about you? Perhaps we should get an expert opinion to help plan the timeline :)

I'm also wondering if GSF is planning another Global Summit since another option could be to reach out to collaborate and incorporate our ideas there. That way we increase our scope and don't have to reinvent the wheel, in the spirit of collaborating more with other LF groups. 😄 WDYT?

**Comment by leonardpahlke** [comment]
> Given my limited experience with organising events/conferences, it is difficult for me to estimate how much time it would take to plan or how much time ahead we should plan this.

We should start planning soon and submit a more complete plan to the chapters. If we do this about 3 months in advance, we will have enough time. 

@nikimanoledaki FYI did you checked out this page? https://github.com/cncf/communitygroups/blob/main/best_practices.md 

> I'm also wondering if GSF is planning another Global Summit since another option could be to reach out to collaborate and incorporate our ideas there.

For this initiative I would like to engage our network within the CNCF. In general ofc, we are happy to collaborate if the GSF or any other foundation is planning something.

**Comment by sergioarmgpl** [comment]
Sounds pretty nice, count with me

**Comment by ar4mirez** [comment]
@leonardpahlke I'll love to support, count with me. I agree with February dates, its kind spaced out with the major events which give some room to attend in person without breaking anyone bank.

**Comment by divya-mohan0209** [comment]
Huge +1 to this idea. I'd be happy to help in anyway I can. 
If we are going with the currently proposed timelines and form of event, putting on my organizer hat, I can confirm that there will be challenges wrt budget & sponsorship.
Additionally, my proposal would be to have it as a co-located event at KubeCon EU, gauge the response, and then branch it out instead of starting it separately. This would serve more than a couple of purposes:
- Adequate time to plan the logistics of the event.
- Better chance at drawing audience since there'll already be folks with an all-attendee pass and with a stellar lineup, we'd be able to attract more folks.
- Better sponsorship opportunities.

**Comment by RinkiyaKeDad** [comment]
I'd be interested in helping support this as well!

**Comment by avillela** [comment]
Definitely interested in supporting this great cause. Not sure how much time I can commit as I don't want to stretch myself too thin. That said, I would love to help, even if it's in a small way!

**Comment by wojtekidd** [comment]
Great proposal. I won't be able to organize an event, but I'll start talking to local cloud native organizers in Poland. If I can connect with anyone and form a team, then I'll let u know.

**Comment by krol3** [comment]
Great initiative 💯 , congrats for that @leonardpahlke , I would be happy to help in my local community too.

**Comment by ramrodo** [comment]
I love the idea! Count on me to participate in the TAG environmental week in our local meetup.

**Comment by pichuang** [comment]
Great idea. The topic of Cloud Native Sustainability is indeed innovative and I believe it would be suitable for presentation within Cloud Native Taiwan User Group.

**Comment by kaspernissen** [comment]
Love the idea, @leonardpahlke 🙏 I'm sure we can help out in the realm of Cloud Native Nordics as well.

**Comment by SamYuan1990** [comment]
I like this idea. Keep eye on this.

**Comment by guidemetothemoon** [comment]
I totally support this idea and I would like to help in all the aspects, both in terms of tasks related to the TAG, the virtual event and organizing a local meetup here in Norway. I'm one of the co-organizers of Cloud Native and Kubernetes Oslo meetup group where we host monthly/bi-monthly meetups. This sounds like a great opportunity to arrange one where local companies and speakers can present on the sustainability related topics. I have a few companies in mind already and can take it up with the other co-organizers as soon as we get some more details clarified here.

When it comes to the timeline, I would agree that having a few months to prepare would be nice. If we go for February then it's a winter holiday month at school in Norway so for arranging our local meetup we would need to choose the dates that are outside of the winter holiday time span, which falls on 19.-23.February 2024.

I also liked the idea of having a global week of sustainability as part of KubeCon+CloudNativeCon EU to reach a broader audience but I would imagine that a strong backing from CNCF would be needed here to actually make room in schedule for attendees to prioritize. At the early stages of raising awareness for sustainability we see that not so many people choose to prioritize content related to this topic (yet).

Collaboration with like-minded organizations like GSF is also worth considering. They seem to have a solid base of speakers that have sessions related to sustainability which can be beneficial both for the virtual event and for the local events depending on where the speaker is located. It will also help us reach even broader audience and strengthen relationship with other groups that are working towards the same goals as we do😊

Anyway, will be happy to be involved in making this event happen!

**Comment by leonardpahlke** [comment]
> When it comes to the timeline, I would agree that having a few months to prepare would be nice.

Yes 💯, **I think the schedule for the second week of October that we have communicated now is best**. We have enough time, there are no big conferences and we still have time - it doesn't fall in the peak travel season, etc.

> I also liked the idea of having a global week of sustainability as part of KubeCon+CloudNativeCon EU to reach a broader audience but I would imagine that a strong backing from CNCF would be needed here to actually make room in schedule for attendees to prioritize.

I think that is a great idea. I can imagine that for one of the next KCCNs we could organize a cloud native sustainability side track / cloud native sustainability day. **This would be separate from this event.**

> Collaboration with like-minded organizations

Yes! I am in contact with two foundations, one in France and one in Finland. More collab is welcome.

**Comment by leonardpahlke** [comment]
We have created a document that explains the event in more detail: https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit?usp=sharing. Please take a look and use the comment/suggestion in Google Docs 🙏 Thank you.

I think this is great and am very happy that so many people are interested in supporting this effort 😊

**Comment by sysnet4admin** [comment]
@leonardpahlke 
Released KO(almost draft) version for sustainability landscape to share and sync-up in local team. 
https://www.linkedin.com/posts/hoonjo_cloudnativeambassador-tjurseqoetyyswm-sustainability-activity-7069932339069399040-FvC4
https://sysnet4admin.gitbook.io/cncf/cloud-native/sustainability/cloud-native-sustainability-landscape

**Comment by Bamistand** [comment]
Nice Idea! I am interested in supporting this

**Comment by seokho-son** [comment]
Hi @leonardpahlke :)
I have shared this activity with a Korean K8s contributor group (K8s SIG-Docs Korean localization team).
Along with @sysnet4admin and myself, [Virusuki](https://github.com/Virusuki) (Nam Uk Kim) is interested in Cloud Native Sustainability. He is willing to assist in organizing a local meetup in Korea.

**Comment by nikimanoledaki** [comment]
It's so exciting to see all the international / local support for this initiative 😍 👏 🌍 🌎 🌏 

There is some progress with reviving the local meetup in Barcelona so we should be able to support and host it as well. 🥳 🌱 

Thinking of what could be the next step for organising this. A couple of suggestions:

- We could create a new channel on the CNCF Slack e.g. #events-tag-env that is under the Comms WG which is specifically for planning events so that we don't spam the whole group. @leonardpahlke @caradelia wdyt?

- We could create a page on the website to track all of the events and how to get in touch with them (social media channel / Meetups / Twitter / CNCF Slack channel / etc) + add this to the [google doc](https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit?usp=sharing)

cc @staceypotter & @immavalls who may also be able to advise since they have a ton of experience with these things 💜

**Comment by divya-mohan0209** [comment]
cc @rohitg00 @saiyam1814

**Comment by rohitg00** [comment]
> cc @rohitg00 @saiyam1814 

Sounds amazing!

**Comment by ams0** [comment]
Amsterdam will be very keen on hosting a EnvSus-focused event (larger Meetup, perhaps with a workshop attached), we are now planning for September/October timeframe. It could be tricky to sync all events on the same week, but perhaps we can just select one of the weeks and we can all focus on finding the right location and speakers. Is there any global event that we can also attach to? Like the World Environment Day in June (source: https://www.un.org/en/climatechange/events).

**Comment by leonardpahlke** [comment]
❤️ to everyone, great to see that, so many are excited about this.

> It could be tricky to sync all events on the same week

Yes! That will be a challenge, but how great it would be. The second week of October 🌱 🚀 skyrocket cloud native sustainability.

I have created several issues for this effort. If you are organizing a local meetup, you do not need to look into this, but your support is greatly appreciated. These issues are aimed more at the general organization of the event. For example, one issue is about issuing badges, another is about creating welcome slides that everyone can use at their local meetups, etc.

Created issues:
- https://github.com/cncf/tag-env-sustainability/issues/126
- https://github.com/cncf/tag-env-sustainability/issues/127
- https://github.com/cncf/tag-env-sustainability/issues/128
- https://github.com/cncf/tag-env-sustainability/issues/129
- https://github.com/cncf/tag-env-sustainability/issues/130
- https://github.com/cncf/tag-env-sustainability/issues/131
- https://github.com/cncf/tag-env-sustainability/issues/132
- https://github.com/cncf/tag-env-sustainability/issues/133
- https://github.com/cncf/tag-env-sustainability/issues/134

Some of you are interested in helping with the overall organization. This is greatly appreciated as it is a lot of work 😁. We will meet this Thursday (June 22, see [calendar invite](https://tockify.com/cncf.public.events/detail/612/1687446000000?search=TAG%20Environmental%20Sustainability)) to coordinate on the topics. 

I am excited about this!

Leo

**Comment by sergioarmgpl** [comment]
I will participate with Cloud Native Guatemala :)

**Comment by Nancy-Chauhan** [comment]
I will love to host with Women in Cloud Native 🎉

**Comment by leonardpahlke** [comment]
Hello all,

Things are in motion 🌊. We are working on getting the event shaped up and organized. If you are curious about that, you can take a look at this [project board](https://github.com/orgs/cncf/projects/10/views/11). We’re planning a sync (like two sessions to cover all time zones) in early August to discuss the event and share info, so you’ll all know what’s going on before you plan your meetups.

If you have any questions now, feel free to drop a comment on this [issue](https://github.com/cncf/tag-env-sustainability/issues/134) (catch all question issue) or any one of the ones linked at the [project board](https://github.com/orgs/cncf/projects/10/views/11).

We have an initial [website page](https://tag-env-sustainability.cncf.io/cloud-native-sustainability-week/) about the event, which we will polish over the coming weeks.  Please take a moment to look at the table with all the meetups we have already captured. If the information is incorrect or out of date, please open a PR to update it (or let me know, so I can make the updates as I go). If you know someone who might be interested in hosting a meetup, they can just add themselves via a PR.

Have a great rest of the week all, talk soon 🙌

**Comment by leonardpahlke** [comment]
Hello everyone,
Next week, on Thursday, August 10, we will organize two meetings to discuss the event with all of you, the local meetup organizers, to clarify questions and so on. It would be great if you could make it, if not, that’s not a problem, we will upload the recording to YouTube afterward.

Meeting details:
* Time for the first meeting: [10am CET](https://everytimezone.com/s/98f0818d)
* Time for the second meeting: [6pm CET](https://everytimezone.com/s/16ba9a03)
* Agenda: https://docs.google.com/document/d/1ouII3Bd-SpF-USjB0IBx6xJuDPZq4Y6uZFcQNVtiPi4/edit
* Zoom: https://zoom.us/my/cncftagenvsustainability, passcode `77777`

I will share a link to the calendar invite as soon as it's added.
Thanks all, talk to you soon 🙌

**Comment by adityasonittyl** [comment]
I will love to host with CNCF Jaipur Chapter !! @leonardpahlke will connect Tom meeting on the same.

**Comment by leonardpahlke** [comment]
Thanks, everyone, for attending today's meetings! You can find the slides here:
[2023-08-10 cloud-native-sustainability-week-sync.pdf](https://github.com/cncf/tag-env-sustainability/files/12315572/2023-08-10.cloud-native-sustainability-week-sync.pdf)
YT recording https://youtu.be/m9uf9m5rI9k

**Comment by humblec** [comment]
@leonardpahlke I would like to host this chapter in Kerala, India as part of Cloud Native User Group here!

**Comment by leonardpahlke** [comment]
@humblec sounds great! Could you please open up a [PR to add your meetup to the list](https://github.com/cncf/tag-env-sustainability/edit/main/website/content/cloud-native-sustainability-week/_index.md). 🙌

**Comment by leonardpahlke** [comment]
Hello everyone,
In about one week, on Thursday, **September 28, we will organize two meetings to discuss the event with the local meetup organizers**, to brief y’all on everything we have been working on. It would be great if you could make it, if not, that’s not a problem, we will upload the recording to YouTube afterward.

Meeting details:
* Time for the first meeting: [10am CET](https://everytimezone.com/s/bd7d3542)
* Time for the second meeting: [6pm CET](https://everytimezone.com/s/e6df4268)
* Agenda: https://docs.google.com/document/d/1ouII3Bd-SpF-USjB0IBx6xJuDPZq4Y6uZFcQNVtiPi4/edit
* Zoom: https://zoom.us/my/cncftagenvsustainability, passcode 77777
You can find the calendar invite here: https://tockify.com/cncf.public.events/monthly?search=TAG%20Environmental%20Sustainability

Thanks all, talk to you soon :raised_hands:

**Comment by marceloamaral** [comment]
The Kepler blog post is live on the cncf blog page:
https://www.cncf.io/blog/2023/10/11/exploring-keplers-potentials-unveiling-cloud-application-power-consumption/

**Comment by leonardpahlke** [comment]
Thanks everyone, for helping with the cloud native sustainability week 💚. It was great to see how we all can collaborate on this topic together. We had way over 1000 in-person attendees at our meetups. And thousands of virtual attendees 🎉. Overall, we received a lot of good feedback and good ideas to further improve the event. 

I have opened up an issue (https://github.com/cncf/tag-env-sustainability/issues/290) to kick off the planning for the cloud native sustainability week 2024. **We are looking for a main organizer for the event**. 2️⃣0️⃣2️⃣4️⃣ 

Until the end of this year we will publish a blog post https://github.com/cncf/tag-env-sustainability/issues/279 to look back at the cloud native sustainability week 2023 and discuss our learnings :)
